US-196 QCM validation
sgmap/pix pull request #103
Opened 2016-11-04 10:30 UTC by bdavidxyz

2016-11-04 10:55 UTC, twickham commented
I've deployed this PR to http://196-rebased.pix.beta.gouv.fr. Please check it out

2016-11-04 12:37 UTC, bdavidxyz commented
coverage decreased, mais je vois pas bien pourquoi

2016-11-07 08:57 UTC, jbuget requested changes

2016-11-07 08:57 UTC, jbuget commented on api/app/services/solution-service.js
> +      if (answer.attributes.value.split(',').sort().join(',') === solution.value.split(',').sort().join(',')) {
n'y aurait-il pas moyen d'extraire ça dans une méthode bien nommée (je ne comprends pas du premier coup ce que ça fait, et c'est le même code à gauche et à droite du `===`) ?

2016-11-07 08:57 UTC, jbuget commented on api/tests/unit/services/solution-service_test.js
> +    it("should return the 'pending' if the question is not a QCU, even if the answer is correct", function () {
"the" ?

2016-11-07 08:57 UTC, jbuget commented on api/tests/unit/services/solution-service_test.js
> +    before(function (done) {
useless, non ?

2016-11-07 12:14 UTC, bdavidxyz commented on api/app/services/solution-service.js
> +      if (answer.attributes.value.split(',').sort().join(',') === solution.value.split(',').sort().join(',')) {
On comprends bien ce que ça fait. Ok pour la redondance, on pourrait mettre ça dans une méthode à part.

2016-11-07 12:14 UTC, bdavidxyz commented on api/tests/unit/services/solution-service_test.js
> +    it("should return the 'pending' if the question is not a QCU, even if the answer is correct", function () {
non sans le the c'est une erreur

2016-11-07 12:14 UTC, bdavidxyz commented on api/tests/unit/services/solution-service_test.js
> +    before(function (done) {
oui

2016-11-07 12:56 UTC, twickham commented
I've deployed this PR to http://196-rebased.pix.beta.gouv.fr. Please check it out

2016-11-07 13:19 UTC, twickham commented
I've deployed this PR to http://196-rebased.pix.beta.gouv.fr. Please check it out

2016-11-07 14:11 UTC, twickham commented
I've deployed this PR to http://196-rebased.pix.beta.gouv.fr. Please check it out

2016-11-07 16:59 UTC, jbuget approved these changes

2016-11-07 17:01 UTC, merged