US-197 : les QROC sont validées automatiquement à la fin d'un test
sgmap/pix pull request #112
Opened 2016-11-08 14:05 UTC by jilljenn

2016-11-09 13:41 UTC, twickham commented
I've deployed this PR to http://197-automate-validation-of-qroc.pix.beta.gouv.fr. Please check it out

2016-11-09 15:33 UTC, twickham commented
I've deployed this PR to http://197-automate-validation-of-qroc.pix.beta.gouv.fr. Please check it out

2016-11-09 16:15 UTC, jbuget requested changes

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +function removeAccentsSpacesUppercase (s) {
renommer la variable `s` en `accentuatedString` (parce qu'une variable ne devrait s'appeler par une lettre, sauf peut-être `i`dans une boucle for, et encore)

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +  userAnswer = removeAccentsSpacesUppercase(userAnswer);
Il est déconseillé de réaffecter une variable de paramètre.
Il vaut mieux déclarer une nouvelle variable `const unaccentuatedAnswer` ou un truc du genre.

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +  for(var i = 0; i < correctAnswersList.length; i++) {
Il est préférable d'utiliser les nouvelles boucles  for...of : 
```javascript
for (let correctAndwer of correctAnswersList) {
 // mon traitement
}
```

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +      if(correctAnswer[0] == '-') // Represents an item
toujours mettre les instructions dans des blocs de code `{}`

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +    if(correctAnswer[0] != '$') { // Represents sometimes the first line of good answers
supprimer les commentaires et extraire / renommer les objets concernés (méthodes / variables)

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +      if(userAnswer == removeAccentsSpacesUppercase(correctAnswer))
ne serait-il pas plus simple de faire directement `return userAnswer == removeAccentsSpacesUppercase(correctAnswer)` ?

2016-11-09 16:15 UTC, jbuget commented on api/app/services/solution-service.js
> +      if (fuzzyMatchingWithAnswers(answer.attributes.value, solution.value)) {
ne pas accéder directement `attributes`, mais passer par le `getter` du Model (answer est un objet de type Ember.Model).

```javascript
if (fuzzyMatchingWithAnswers(answer.get('value'), solution.value)) {
```

2016-11-09 16:15 UTC, jbuget commented on api/tests/unit/services/solution-service_test.js
> +  });
nickel ce petite test ^^

2016-11-09 16:15 UTC, jbuget commented on live/app/components/challenge-item.js
> +function getFirstValueOfDict(answers) {
éviter les abbréviations : "Dict" => "Dictionary"

2016-11-09 16:15 UTC, jbuget commented on live/mirage/data/answers/qroc-answer-ko.js
> +      value: 'hokuto no ken', // Erreur d'accent volontaire
erreur de commentaire ?

2016-11-09 16:15 UTC, jbuget commented on live/mirage/data/answers/qroc-answer.js
> +      value: 'la couteaudérie', // Erreur d'accent volontaire
la mettre en normale ?

2016-11-09 16:19 UTC, jbuget commented on api/app/services/solution-service.js
> +    if(correctAnswer[0] != '$') { // Represents sometimes the first line of good answers
Prévenir les Métiers que pour un QROC, dans les bonnes réponses, on ne met pas de `$` (parce que ça nous fout la grouille côté dev)

2016-11-14 09:23 UTC, jilljenn commented on api/app/services/solution-service.js
> +      if(userAnswer == removeAccentsSpacesUppercase(correctAnswer))
Non parce que si ce n'est pas true il ne faut pas renvoyer false, il faut continuer à explorer.

2016-11-14 09:43 UTC, twickham commented
I've deployed this PR to http://197-automate-validation-of-qroc.pix.beta.gouv.fr. Please check it out

2016-11-14 09:48 UTC, jbuget approved these changes

2016-11-14 10:34 UTC, twickham commented
I've deployed this PR to http://197-automate-validation-of-qroc.pix.beta.gouv.fr. Please check it out

2016-11-14 10:37 UTC, merged