US-221 UI/UX de l'écran de fin de test
sgmap/pix pull request #119
Opened 2016-11-09 12:53 UTC by bdavidxyz

2016-11-09 17:20 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-09 17:35 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-10 09:56 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-10 10:07 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-10 10:32 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-10 21:54 UTC, jbuget requested changes
- L'espace entre le bandeau bleu et "Vos résultats" (margin-bottom: 20px) n'est pas celui préconisé par Manu (margin-bottom: 30px)
- il faudrait mettre un espace en-dessous le bouton “revenir à la liste des tests" car là le bouton colle le bas de l'écran

2016-11-10 21:54 UTC, jbuget commented on live/app/styles/assessments/get-results.css
> +    color: #3e4149;
sortir la couleur dans une variable

2016-11-10 21:54 UTC, jbuget commented on live/app/styles/assessments/get-results.css
> +    font-family: 'Lato';
y a-t-il vraiment besoin de préciser la font, sachant que c'est celle globale ?

2016-11-10 21:54 UTC, jbuget commented on live/app/styles/assessments/get-results.css
> +  border-color: #f2f3f4;
sortir la couleur

2016-11-10 21:54 UTC, jbuget commented on live/bower.json
> -    "simple-markdown": "0.1.1",
trop cool ^^

2016-11-10 21:54 UTC, jbuget commented on live/tests/acceptance/195-validation-automatique-des-qcu-test.js
> +    expect($cell.attr('data-original-title')).to.equal('Réponse incorrecte');
cool le equal plutôt que le contains

2016-11-11 05:32 UTC, bdavidxyz commented on live/app/styles/assessments/get-results.css
> +    font-family: 'Lato';
Si, il y a besoin, car bootstrap force la font dans le tooltip sinon. 
J'ai rajouté une issue pour définir la font globale dans une variable du coup.

2016-11-11 06:14 UTC, bdavidxyz commented
ok pour la margin bottom, c'est corrigé.
Par contre je comprends pas bien l'espace en dessous le bouton, ça s'affiche très bien chez moi.
Je rajoute une issue pour ne pas perdre de temps.

2016-11-11 06:25 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-14 09:29 UTC, jbuget approved these changes

2016-11-14 09:36 UTC, twickham commented
I've deployed this PR to http://221-test-ending-ui.pix.beta.gouv.fr. Please check it out

2016-11-14 09:59 UTC, merged