Add ember-metrics to package.json
sgmap/pix pull request #136
Opened 2016-11-14 16:29 UTC by jilljenn

(That's all.)
Je ne connais pas trop la logique des pages d'Ember. Mais [voici la doc](https://github.com/poteto/ember-metrics#usage).

2016-11-14 17:05 UTC, jilljenn commented
J'avais un problème parce que tous les tests unitaires créent une route mais il ne faut pas mettre les analytics sinon ça requiert un `needs:metrics`. Donc j'ai trouvé [ce workaround](https://github.com/poteto/ember-metrics/issues/43#issuecomment-252081256). Maintenant il faut tester.

2016-11-14 17:13 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-14 17:42 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-14 18:31 UTC, jbuget requested changes
Plutôt que des request changes, c'est surtout des réponses à des interrogations.

2016-11-14 18:31 UTC, jbuget commented on live/app/router.js
> +  Router.reopen({
Est-on obligé de passer par la méthode `Router#reopen()` (qui est à mon sens un énorme hack de Ember, et un truc un peu sale) ?

2016-11-14 18:31 UTC, jbuget commented on live/app/router.js
> +    location: config.locationType,
doublon avec la déclaration de la classe

2016-11-14 18:31 UTC, jbuget commented on live/app/router.js
> +      Ember.run.scheduleOnce('afterRender', this, () => {
je ne comprends pas à quoi sert le `#scheduleOnce`

2016-11-14 18:31 UTC, jbuget commented on live/config/environment.js
> +          piwikUrl: '//stats.data.gouv.fr',
j'ai l'impression qu'il y a une faille de sécurité ici (rappel : le code est open source)

2016-11-15 10:49 UTC, jilljenn commented on live/config/environment.js
> +          piwikUrl: '//stats.data.gouv.fr',
Je me disais que le serveur n'accepterait que les requêtes provenant de l'adresse pix.beta.gouv.fr. Du coup il faut se demander comment tester.

2016-11-15 10:50 UTC, jilljenn commented on live/app/router.js
> +      Ember.run.scheduleOnce('afterRender', this, () => {
Je ne sais pas mais c'est le code par défaut du README : https://github.com/poteto/ember-metrics

2016-11-15 10:50 UTC, jilljenn commented on live/app/router.js
> +    location: config.locationType,
Ah oui je retire.

2016-11-15 10:50 UTC, jilljenn commented on live/app/router.js
> +  Router.reopen({
Hélas sinon il faut que tous les tests unitaires incluent `needs:metrics` ce serait un peu nul non ? Comment distinguer entre prod et test.

2016-11-15 13:07 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 13:38 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 14:01 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 14:23 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 14:41 UTC, MattiSG commented on live/config/environment.js
> +          piwikUrl: '//stats.data.gouv.fr',
Pourquoi est-ce que ce serait une faille de sécurité ?

Éventuellement, vous devriez forcer le protocole à `https` plutôt que de d'utiliser le scheme-less, mais il n'y a pas de faille ici plus qu'ailleurs. Toute solution de suivi d'audience est vulnérable à l'empoisonnement.

2016-11-15 14:43 UTC, MattiSG commented on live/config/environment.js
> +        name: 'GoogleAnalytics',
Attention, si vous utilisez Google Analytics vous devrez impérativement recueillir l'accord explicite de l'usager **avant** d'activer le suivi.

Références : https://beta.gouv.fr/suivi et https://github.com/sgmap/beta.gouv.fr/issues/342.

2016-11-15 15:01 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 15:12 UTC, twickham commented
I've deployed this PR to http://240-add-analytics.pix.beta.gouv.fr. Please check it out

2016-11-15 15:23 UTC, merged

2016-11-15 15:33 UTC, MattiSG commented
Du coup, je vous remets ça là et non plus dans un commentaire de diff :

**Attention, si vous utilisez Google Analytics vous devrez impérativement recueillir l'accord explicite de l'usager avant d'activer le suivi.**

Références : https://beta.gouv.fr/suivi et https://github.com/sgmap/beta.gouv.fr/issues/342.