US-257 homepage design
sgmap/pix pull request #138
Opened 2016-11-14 17:31 UTC by bdavidxyz

2016-11-14 17:54 UTC, twickham commented
I've deployed this PR to http://257-homepage-4.pix.beta.gouv.fr. Please check it out

2016-11-14 18:30 UTC, twickham commented
I've deployed this PR to http://257-homepage-4.pix.beta.gouv.fr. Please check it out

2016-11-14 21:39 UTC, jbuget requested changes
Quelques petites modifs vite fait

2016-11-14 21:39 UTC, jbuget commented on live/app/components/first-page.js
> +    const showOnly = this.get('showOnly');
mieux nommer `showOnly` (qui a une trop forte connoation de booléen) en`coursesMaxNumber` ou quelque chose du genre

2016-11-14 21:39 UTC, jbuget commented on live/app/components/first-page.js
> +      // do nothing
si le catch est vide, pourquoi encapsuler le tout dans un try catch (et cacher l'exception levée) plutôt que laisser l'exception péter et au pire imprimer une stack trace dans la console ?

2016-11-14 21:39 UTC, jbuget commented on live/app/routes/index.js
> +    ]).then((arr) => arr[0]);
renommer `arr` en `courses`

2016-11-14 21:39 UTC, jbuget commented on live/app/initializers/router.js
> +  application.inject('route', 'router', 'router:main');
je ne comprends pas le but de cet initializer. injecter le router dans tous les composants ?

2016-11-14 21:39 UTC, jbuget commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.blue{background: #ffbe00;}
`#ffbe00` == jaune

2016-11-14 21:39 UTC, jbuget commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.shadow{
not used

2016-11-14 21:39 UTC, jbuget commented on live/app/styles/components/corner-ribbon.css
> +  font-family: Lato;
ajouter `Arial, sans-serif` au cas où les fonts ne seraient pas chargées

2016-11-14 21:39 UTC, jbuget commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.blue{background: #ffbe00;}
et variabiliser la couleur

2016-11-14 21:39 UTC, jbuget commented on live/app/styles/components/first-page.css
> +/*--first-page-hero-height:  700px;*/
dead code

2016-11-14 21:39 UTC, jbuget commented on live/tests/acceptance/259-afficher-logo-beta-test.js
> +describe.skip('Acceptance | 259 - Afficher le logo BETA | ', function () {
normal le `skip` ?

2016-11-14 21:39 UTC, jbuget commented on live/tests/integration/components/corner-ribbon-test.js
> +      // Set any properties with this.set('myProperty', 'value');
dead code

2016-11-14 22:02 UTC, bdavidxyz commented on live/app/components/first-page.js
> +    const showOnly = this.get('showOnly');
non j'aime bien le showOnly qui spécifie bien que tout est chargé mais qu'on n'en montre que 4. Mais bon, je veux bien changer.

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/components/first-page.js
> +      // do nothing
par ce que c'est un cas de figure prévu et non imprévu. Je me sert de l'exception pour contrôler le flow (ouh!)

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/routes/index.js
> +    ]).then((arr) => arr[0]);
ok.

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/initializers/router.js
> +  application.inject('route', 'router', 'router:main');
oui ! très pratique pour savoir dans quelle route on est. Voir http://stackoverflow.com/questions/18302463/get-current-route-name-in-ember

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/styles/components/corner-ribbon.css
> +  font-family: Lato;
ok

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.shadow{
ok

2016-11-14 22:03 UTC, bdavidxyz commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.blue{background: #ffbe00;}
ok

2016-11-14 22:04 UTC, bdavidxyz commented on live/app/styles/components/corner-ribbon.css
> +.corner-ribbon.blue{background: #ffbe00;}
oui plus le nom que j'ai laissé à blue alors que c'est jaune !

2016-11-14 22:04 UTC, bdavidxyz commented on live/app/styles/components/first-page.css
> +/*--first-page-hero-height:  700px;*/
ok

2016-11-14 22:04 UTC, bdavidxyz commented on live/tests/acceptance/259-afficher-logo-beta-test.js
> +describe.skip('Acceptance | 259 - Afficher le logo BETA | ', function () {
non

2016-11-14 22:04 UTC, bdavidxyz commented on live/tests/integration/components/corner-ribbon-test.js
> +      // Set any properties with this.set('myProperty', 'value');
ok

2016-11-15 08:34 UTC, bdavidxyz commented on live/app/components/first-page.js
> +    const showOnly = this.get('showOnly');
je ne change pas, j'ai mis une issue https://github.com/sgmap/pix-live/issues/139 qu'on regardera plus tard

2016-11-15 08:34 UTC, bdavidxyz commented on live/app/components/first-page.js
> +      // do nothing
https://github.com/sgmap/pix-live/issues/139 également

2016-11-15 08:35 UTC, bdavidxyz commented on live/app/initializers/router.js
> +  application.inject('route', 'router', 'router:main');
j'ai rajouté le lien dans le code

2016-11-15 09:05 UTC, twickham commented
I've deployed this PR to http://257-homepage-4.pix.beta.gouv.fr. Please check it out

2016-11-15 09:29 UTC, jbuget approved these changes

2016-11-15 09:29 UTC, merged