US-190 avec ou sans internet
sgmap/pix pull request #217
Opened 2016-12-21 15:47 UTC by bdavidxyz

2016-12-21 15:59 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2016-12-21 16:16 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2016-12-21 16:23 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2016-12-26 11:36 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2016-12-28 01:50 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-03 14:29 UTC, jbuget requested changes
Quelques interrogations et des micro-modifs en mode "easy".

Il y a aussi plein de commentaires – je suis pas fan car tout code en commentaire est un gros risque de code obsolète avant / sans même qu'on s'en rende compte – mais j'ai pas envie de bloquer l'US pour ça.

2017-01-03 14:29 UTC, jbuget commented on api/.eslintrc
> +  include: true
Pourquoi est-on obligé d'autoriser le mot `include` ? question vraiment naïve : je ne connais pas la différence avec require et j'imagine que ESLint a une raison pour ne pas l'accepter de base.

2017-01-03 14:29 UTC, jbuget commented on api/.eslintrc
> +  include: true
Avec la modif de `api/lib/settings.js` je vois pour quoi on l'ajoute. Par contre, j'ai une remarque sur cette ligne, cf. ci-dessous.

2017-01-03 14:29 UTC, jbuget commented on api/lib/settings.js
> +global.include = function(file) {
Dans quel cas faut-il utiliser la méthode custom `include` plutôt que l'import standard `require` ?

2017-01-03 14:29 UTC, jbuget commented on api/tests/acceptance/application/challenge-controller_test.js
>        });
Merci pour la transformation :-)

2017-01-03 14:29 UTC, jbuget commented on api/tests/unit/utils/lodash-utils_test.js
> +    it('when no arg are given, should return false', function (done) {
Une question que je me pose, est-ce qu'on décide qu'on se force à utiliser `done` même quand on n'est pas dans un contexte asynchrone ? Dans ce cas et ceux qui suivent, par exemple, on fait un simple `expect` tout ce qu'il y a de plus synchrone. On peut peut-être s'économiser des lignes et de l'énergie en ommettant `done`, non ? WDYT ?

2017-01-03 14:29 UTC, jbuget commented on live/app/models/answer/value-as-array-of-boolean-mixin.js
> +// import _ from 'pix-live/utils/lodash-custom';
code mort

2017-01-03 14:29 UTC, jbuget commented on live/package.json
> +    "phantomjs-prebuilt":"2.1.14"
Du coup, il faut modifier le README à la racine pour supprimer dans la partie "installation" le prérequis de PhantomJS, non ?

2017-01-03 14:29 UTC, jbuget commented on live/tests/integration/components/challenge-stay-test.js
> +    // Set any properties with this.set('myProperty', 'value');
code mort ?

2017-01-04 09:44 UTC, bdavidxyz commented on api/tests/unit/utils/lodash-utils_test.js
> +    it('when no arg are given, should return false', function (done) {
si pas besoin de done(), on le supprime

2017-01-04 10:28 UTC, bdavidxyz commented on live/package.json
> +    "phantomjs-prebuilt":"2.1.14"
README à jour. Je vais envoyer un mail aux dev pour prévenir du changement de version. Je n'ai pas réussi à supprimer la dépendance globale.

2017-01-04 10:47 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-04 11:02 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-04 13:58 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-04 13:59 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-04 14:20 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-06 12:43 UTC, jbuget commented
I've deployed this PR to http://190-no-internet.pix.beta.gouv.fr. Please check it out

2017-01-06 14:48 UTC, merged