US-317 : Add adaptive scenarios for general adaptive tests
sgmap/pix pull request #241
Opened 2017-01-19 07:20 UTC by jilljenn

YEAAAH!

2017-01-19 10:00 UTC, jbuget requested changes
Des toutes petites modifs (renommage de variables).

J'ai vu que finalement tu as opté pour la solution "script python qui alimente la base" à la question à laquelle je n'ai pas répondue.

Comme ça, ça me paraît très bien. Après, c'est la réalité qui nous donerra tort ou raison.

En tout cas, beau boulot JJ ^^

2017-01-19 10:00 UTC, jbuget commented on api/lib/domain/models/data/scenario.js
> +  /* assessment: function () {
code mort

2017-01-19 10:00 UTC, jbuget commented on api/tests/acceptance/application/assessment-controller_test.js
> +    const inserted_scenarios = [{
renommer `inserted_scenarios` en `insertedScenarios`. camel case est le standard que nous avons adopté sur le projet (et aussi celui qui se répand le plus ces derniers temps sur JS)

2017-01-19 10:00 UTC, jbuget commented on scripts/add_scenarios.py
> +c.executemany('INSERT INTO scenarios VALUES (NULL, ?, ?, ?, datetime("now"), datetime("now"))', scenarios)
n'y aurait-il pas moyen de variabiliser `datatime("now")` pour avoir la même date dans les 2 colonnes (et faciliter une éventuelle recherche / requête SQL) ?

2017-01-19 10:00 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +        if(scenario == null) {
plutôt que `if (scenario == null)` je préfère la notation `if (scenario)` qui tient compte aussi du fait que scenario peut être `undefined`.

2017-01-19 10:00 UTC, jbuget commented on scripts/add_scenarios.py
> +conn = sqlite3.connect('../api/db/dev.sqlite3')
renommer `conn` en `connection`

2017-02-06 12:28 UTC, jilljenn commented on api/lib/domain/models/data/scenario.js
> +  /* assessment: function () {
Done.

2017-02-06 12:30 UTC, jilljenn commented on api/tests/acceptance/application/assessment-controller_test.js
> +    const inserted_scenarios = [{
Done. Sorry, l'habitude du Python :)

2017-02-06 12:31 UTC, jilljenn commented on scripts/add_scenarios.py
> +conn = sqlite3.connect('../api/db/dev.sqlite3')
Done.

2017-02-06 12:33 UTC, jilljenn commented on scripts/add_scenarios.py
> +c.executemany('INSERT INTO scenarios VALUES (NULL, ?, ?, ?, datetime("now"), datetime("now"))', scenarios)
En fait ça demande du Dynamic SQL et c'est un peu lourd : http://stackoverflow.com/a/3833421/827989 donc je ne préfère pas.

2017-02-06 12:35 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +        if(scenario == null) {
`if (!scenario)` tu veux dire ? Je viens de modifier.

2017-02-06 15:35 UTC, jilljenn commented
BTW tu veux sans doute que je rebase dev ? Je vais le faire ^^'

2017-02-06 18:37 UTC, jbuget commented
I've deployed this PR to http://317-adaptive-scenarios.pix.beta.gouv.fr. Please check it out

2017-02-09 13:11 UTC, bdavidxyz commented
Non on ne fait plus de rebasing pour l'instant, on fait du merge

2017-02-10 10:26 UTC, jilljenn commented
Le test adaptatif ne marche plus parce que le redéploiement a effacé la table `scenarios` ; mais vous pouvez quand même merge parce que je devrai de toute façon importer les scénarios vers staging.

2017-02-10 14:53 UTC, jbuget commented
I've deployed this PR to http://317-adaptive-scenarios.pix.beta.gouv.fr. Please check it out

2017-02-13 14:34 UTC, jbuget approved these changes

2017-02-13 14:35 UTC, merged