Correction bug croqm ind
sgmap/pix pull request #251
Opened 2017-01-24 11:04 UTC by MBrandone

ajout de test sur les CROQM ind, implementation et/ refacto de la verification des réponses

2017-01-24 11:15 UTC, jbuget commented
I've deployed this PR to http://correction-bug-CROQM-ind.pix.beta.gouv.fr. Please check it out

2017-01-25 08:13 UTC, jbuget requested changes

2017-01-25 08:13 UTC, jbuget commented on api/lib/domain/services/solution-service-qrocm-ind.js
>    match (yamlAnswer, yamlSolution) {
découper la méthode en sous-méthodes, car la fonction ne tient pas sur un écran, et que ça force à faire des efforts de compréhension inutiles et qui coûtent du temps. cf. `solution-service-qrocm-dep.js`

2017-01-25 08:13 UTC, jbuget commented on api/tests/unit/domain/services/solution-service_test.js
> +        {answer: '1', solution: '1'},
Configurer ton IDE pour respecter le style défini dans le fichier `.editorconfig` et ainsi éviter les faux diff

2017-01-27 10:16 UTC, MBrandone commented on api/lib/domain/services/solution-service-qrocm-ind.js
>    match (yamlAnswer, yamlSolution) {
Done. J'ai pu tester la puissance du Alt+Cmd+M sur IntelliJ.

2017-01-27 10:21 UTC, jbuget commented
I've deployed this PR to http://correction-bug-CROQM-ind.pix.beta.gouv.fr. Please check it out

2017-01-27 11:30 UTC, jbuget approved these changes

2017-01-27 11:32 UTC, jbuget commented
I've deployed this PR to http://correction-bug-CROQM-ind.pix.beta.gouv.fr. Please check it out

2017-01-27 14:50 UTC, jbuget commented
I've deployed this PR to http://correction-bug-CROQM-ind.pix.beta.gouv.fr. Please check it out

2017-01-27 14:53 UTC, merged