us-309 compare answers solutions QCM
sgmap/pix pull request #255
Opened 2017-01-24 15:00 UTC by MBrandone

2017-01-24 15:37 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-24 17:38 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-25 10:03 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-25 10:06 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-25 10:36 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-25 10:51 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-25 15:59 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-26 14:56 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-26 15:03 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 10:42 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 11:23 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 11:27 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 13:19 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 13:48 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 13:56 UTC, bdavidxyz commented
test case : 
 - [ ] n'afficher que pour QCM
 - [ ] click sur réponse => ouverture de la modale
 - [ ] accès par URL direct => ouverture de la modale
 - [ ] numéro index correct
 - [ ] instruction correcte
 - [ ] affichage image si présente
 - [ ] absence affichage image si non présente
 - [ ] proposition : QCM correcte non cochée : vert + gras
 - [ ] proposition : QCM correcte cochée : vert + gras
 - [ ] proposition : QCM incorrecte cochée : barré
 - [ ] proposition : QCM incorrecte non cochée : normal
 - [ ] les checkboxes qu'a tické l'utilisateur sont cochées, les autres non
 - [ ] fermeture via bouton fermer
 - [ ] fermeture via zone grise

2017-01-31 14:24 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 14:55 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 14:59 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:15 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:22 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:35 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:39 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:44 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 15:53 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 16:20 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 16:25 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 16:31 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 16:36 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 16:52 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 17:15 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 17:17 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 17:26 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 17:45 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 17:50 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-01-31 18:02 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-02-02 19:25 UTC, jbuget requested changes
On voit ça demain en mob-programming et lundi.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +const assessmentSerializer = include('lib/infrastructure/serializers/assessment-serializer');
Est-ce qu'on conserve la fonction `include` ou qu'on revient (malheureusement) à la fonction `require` (avec tous les `../`) ? 

Mes arguments pour un retour à `require`, principalement basé sur mon IDE :

- on ne peut plus naviguer directement par un ctrl-click
- du coup, on ne peut plus savoir juste au passage de la souris si le chemin est correct
- on ne bénéficie plus non plus de la complétion automatique
- le linter n'est pas content (encore un mot-clé global)
- j'ai perdu 20mn la première fois que je suis tombé dessus à chercher dans la doc de Node.js / Hapi.js d'où sortait ce mot-clé, qui n'en est pas un ?

Je me demande s'il n'existe pas de base un truc plus simple dans Node.js, toujours avec la méthode `require` pour donner le nom du package de l'application (en l'occurence "pix-api") et qu'il se débrouille tout seul, comme pour Ember.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +
saut de ligne en trop ---> préconisation : utiliser le formatage automatique, voire, configurer l'action "save" de l'IDE pour qu'à chaque sauvegarde (même si elle est automatique), le formatter et l'optimizer d'import passent directement.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +          answerRepository.findByAssessment(assessment.attributes.id).then((answers) => {
Il vaut mieux privilégier la méthode `Bookshelf.Model#get` plutôt que passer par la propriété `Bookshelf.Model.attributes`, qui peut potentiellement être dans un état `transient` à certain moment.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +            const answersLength = _.get(answers, 'length', 0);
Je ne comprends pourquoi on ne fait pas tout simplement `answers.length()`, même si je devine qu'il y a une bonne raison.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +                const challengesLength = _.get(course, 'challenges.length', 0);
Idem que ci-dessus sur l'usage de `_.get`

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +                  const modelAnswers = _.map(answers.models, (o) => o.attributes);
Variable mal nommée. Il faut toujours faire l'effort de nommer de façon explicite les variables. Ca ne coûte pas grand chose à faire, et ça facilite vachement la vie de ceux qui passent derrière. Là je ne comprends pas ce que signifie le 'o', sachant qu'on map des "answers". 

Même remarque que ci-dessus, ne pas utiliser `attributes` mais la bonne méthode dans Bookshelf.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +                      return reply(solutionSerializer.serialize(solution));
Je pense qu'il y a vachement moyen d'aplatir cette méthode avec des promesses ou async / await...

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +
Lignes blanches en trop.

2017-02-02 19:25 UTC, jbuget commented on api/lib/application/assessments/assessment-controller.js
> +
Méthode trop longue à mon goût : 50 lignes, et ça dépasse d'un écran. Obligé de bufferizer entre la signature et le retour de la méthode.

2017-02-02 19:25 UTC, jbuget commented on api/lib/infrastructure/repositories/answer-repository.js
> +          assessmentId: assessmentId
Avec ES6, on peut utiliser le raccourci `.where({ assessmentId })`.

Quand une clé d'un objet à la même nom que la variable contenant la valeur d'assignation, on peut se contenter de saisir que l'identifiant.

2017-02-02 19:25 UTC, jbuget commented on api/lib/infrastructure/repositories/answer-repository.js
> +        .then((answers) => resolve(answers))
La méthode `#then` prend une callback en argument. Ce qui permet de simplifier l'écriture comme suit : `.then(resolve)`.

2017-02-02 19:25 UTC, jbuget commented on api/lib/infrastructure/repositories/answer-repository.js
> +        .catch((err) => reject(err));
Idem : `.catch(reject)`

2017-02-02 19:25 UTC, jbuget commented on api/lib/infrastructure/serializers/solution-serializer.js
> +    super('solutions');
Bien vu ! C'est ma faute, j'aurais dû mettre un TU sur la classe qui a servi d'exemple. Du coup, il faut mettre un TU pour vérifier que le type est le bon.

2017-02-02 19:25 UTC, jbuget commented on api/tests/acceptance/application/assessment-controller_test.js
> +
Beaucoup de lignes vides en trop...

2017-02-02 19:25 UTC, jbuget commented on api/tests/unit/application/assessments/index_test.js
> +/* global before, beforeEach, describe, it, expect, sinon, after */
Quitte à mettre une ligne de code, autant que ce soir une ligne utile.
Désormais je remets systématiquement les imports car : 

- IDEA est content
- le linter est content
- mais surtout, je peux exécuter / débugger mes tests de façon indépendante (dans IDEA ou tout autre IDE)

Je n'ai pas encore réussi à exporter convenablement sinon et knex dans un fichier `setup.js` mieux foutu qu'actuellement, mais j'y songe. Mon idée : pouvoir faire simplement :

```javascript
const { describe, it, before, after, beforeEach, afterEach, nock, knex, sinon } = require('pix-api/tests/setup');
```

2017-02-02 19:25 UTC, jbuget commented on api/tests/unit/application/assessments/index_test.js
> +    before(function () {
code mort

2017-02-02 19:25 UTC, jbuget commented on api/tests/unit/application/assessments/index_test.js
> +      done();
lol

2017-02-02 19:25 UTC, jbuget commented on api/tests/unit/domain/services/solution-service_test.js
> +    solution.scoring = _.ensureString(scoring).replace(/@/g, '');  // XXX : does the adapter job
Je ne comprends pas le commentaire ?!

2017-02-02 19:25 UTC, jbuget commented on live/app/adapters/solution.js
> +  queryRecord(modelName, clazz, query) {
WHAT ???!!!

2017-02-02 19:25 UTC, jbuget commented on live/app/components/comparison-window.js
> +  // challenge comes from declaration
commentaire == code mort

2017-02-02 19:25 UTC, jbuget commented on live/app/routes/assessments/get-comparison.js
> +            answer,
on peut faire mieux grâce à `async / await`

2017-02-02 19:25 UTC, jbuget commented on live/app/routes/assessments/get-results.js
> +    openComparison: function (assessment_id, answer_id, index) {
je ne comprends pas le rôle de la variable `index`

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/app.css
> +@import url('vendor/ember-routable-modal/core');
J'aurais eu plutôt tendance à mettre ça dans le fichier `ember-cli-build.js`, comme on a fait pour Bootstrap

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/components/comparison-window.css
> +
code mort

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/components/comparison-window.css
> +
code mort

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/components/comparison-window.css
> +
ligne blanche en trop

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/components/get-results.css
> +
ligne en trop

2017-02-02 19:25 UTC, jbuget commented on live/app/styles/vendor/ember-routable-modal/dialog.css
> +    &:hover,
Privilégier l'écriture en classes plutôt que l'inlining façon PostCSS.

2017-02-02 19:25 UTC, jbuget commented on live/app/templates/assessments/get-comparison.hbs
> +    challenge=model.challenge
Est-ce que ce ne serait pas intéressant de passer par les [positionals-params](https://guides.emberjs.com/v2.11.0/components/passing-properties-to-a-component/#toc_positional-params) ?

2017-02-02 19:25 UTC, jbuget commented on live/app/templates/components/comparison-window.hbs
> +</div>
Je me questionne sur la maintenabilité de ce template. Est sinon, il y a beaucoup de lignes blanches en trop.

2017-02-02 19:25 UTC, jbuget commented on live/mirage/data/solutions/ref-solution.js
> +
lignes en trop

2017-02-02 19:25 UTC, jbuget commented on live/tests/acceptance/a3-voir-liste-tests-test.js
> +//
code mort

2017-02-02 19:25 UTC, jbuget commented on live/tests/integration/components/window-comparison-test.js
> +      // challenge = {};
code mort

2017-02-02 19:25 UTC, jbuget commented on live/tests/integration/components/window-comparison-test.js
> +      // expect(this.$('.comparison-window .assessment-results-result-text').text()).to.equal('blabla');
code mort

2017-02-03 15:21 UTC, jbuget approved these changes

2017-02-03 15:44 UTC, jbuget commented
I've deployed this PR to http://309-compare-answers-solutions.pix.beta.gouv.fr. Please check it out

2017-02-06 11:06 UTC, merged