334 switch formspree to pg
sgmap/pix pull request #259
Opened 2017-01-27 11:58 UTC by yojecode

2017-01-27 18:22 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-01-30 09:08 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-01-30 17:10 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-01-30 17:59 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-01-31 10:41 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 10:51 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 11:01 UTC, bdavidxyz commented on api/package.json
> +    "airtable": "0.4.3",
non, déjà corrigé

2017-02-02 11:13 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 13:39 UTC, bdavidxyz commented on api/tests/unit/domain/services/email-validator_test.js
> +    null,
j'aurais testé le cas 'undefined' aussi par acquix de conscience

2017-02-02 13:41 UTC, bdavidxyz commented on live/app/components/follower-form.js
> +        }, 1200);
mettre un commentaire. Pourquoi 1,2 secondes ? On remet le formulaire à l'état initial c'est ça ?

2017-02-02 13:43 UTC, yojecode commented on api/tests/unit/domain/services/email-validator_test.js
> +    null,
Ce cas est déjà testé juste avant !

2017-02-02 13:47 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 13:52 UTC, bdavidxyz commented on live/app/components/follower-form.js
> +    error: 'Votre adresse n’est pas valide',
pas la même apostrophe que "s'inscrire", plus bas

2017-02-02 13:53 UTC, MBrandone commented on live/app/components/followers.js
> +
A quoi sert ce composant ?

2017-02-02 13:54 UTC, bdavidxyz commented on live/tests/unit/services/email-validator-test.js
> +      '',
manque le cas 'undefined'

2017-02-02 13:55 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 13:56 UTC, bdavidxyz commented on live/app/components/followers.js
> +
Il peut avoir une utilisé si le hbs et le css sont utilisés, pas besoin d'avoir du comportement JS

2017-02-02 14:00 UTC, bdavidxyz commented on api/tests/unit/domain/services/email-validator_test.js
> +    null,
ok

2017-02-02 14:00 UTC, yojecode commented on live/tests/unit/services/email-validator-test.js
> +      '',
Pareil que là haut

2017-02-02 14:37 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 14:45 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 15:24 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 16:05 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-02 16:11 UTC, bdavidxyz commented on live/app/styles/globals/palette.css
> +  --follower-label-error: #f45c00;
bof bof de lier une couleur à un model

2017-02-02 16:16 UTC, bdavidxyz commented on live/app/styles/globals/palette.css
> +  --follower-label-error: #f45c00;
nouvelle issue https://github.com/sgmap/pix/issues/270

2017-02-14 20:56 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-15 10:45 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-17 11:27 UTC, bdavidxyz commented on api/lib/application/followers/follower-controller.js
> +function _assertFollowerNotExist(follower){
ajouter un espace au-dessus

2017-02-17 12:10 UTC, bdavidxyz commented on api/lib/domain/services/email-validator.js
> +    const pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
un lien vers StackOverflow peut être

2017-02-17 12:11 UTC, bdavidxyz commented on api/lib/plugins.js
> +//if (process.env.NODE_ENV === 'test') {}
à supprimer

2017-02-17 12:14 UTC, bdavidxyz commented on api/tests/unit/application/followers/follower-controller_test.js
> +      //Given
espace

2017-02-17 12:16 UTC, bdavidxyz commented on live/app/services/email-validator.js
> +    const pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
Un lien vers StackOverflow ou autre, pour savoir d'où vient cette regexp (à moins que ce soit nous qui l'ayons développée from scratch ?)

2017-02-17 12:16 UTC, bdavidxyz commented on live/config/environment.js
> +    ENV.APP.LOG_RESOLVER = true;
a priori on laisse tout à false

2017-02-17 12:18 UTC, bdavidxyz requested changes
voir les quelques commentaires

2017-02-20 11:51 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-20 12:05 UTC, bdavidxyz commented on api/lib/domain/services/email-validator.js
> +    const pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
idem, toujours pas de lien ?

2017-02-20 12:50 UTC, yojecode commented
Vu que c'est le même regex, j'ai mis le lien dans le fichier front.

Je vais le mettre partout dès que je reprends 

Envoyé de mon iPhone

> Le 20 févr. 2017 à 13:05, David Boureau <notifications@github.com> a écrit :
> 
> @bdavidxyz commented on this pull request.
> 
> In api/lib/domain/services/email-validator.js:
> 
> > @@ -0,0 +1,12 @@
> +module.exports = {
> +
> +  emailIsValid(email) {
> +    if (!email) {
> +      return false;
> +    }
> +
> +    const pattern = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
> idem, toujours pas de lien ?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-20 13:38 UTC, bdavidxyz approved these changes

2017-02-20 16:27 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-20 21:58 UTC, jbuget commented
I've deployed this PR to http://334-switch-formspree-to-pg.pix.beta.gouv.fr. Please check it out

2017-02-20 21:59 UTC, merged