US-360 : Ajout des acquis aux épreuves pour calculer le niveau de l'apprenant
sgmap/pix pull request #283
Opened 2017-02-08 18:05 UTC by jilljenn

(pas encore prêt, mais c'est pour me convaincre que j'avance)

2017-02-09 15:29 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-02-20 23:52 UTC, jilljenn commented
Il me manque encore :

- des tests unitaires pour getNextNode (facile) et propagateAcquix (plus coton déjà) ;
- nettoyer un peu le corps de la fonction parce que je sens que ça va moyennement vous plaire (peut-être factoriser dans assessmentService).

2017-02-20 23:55 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-02-27 18:09 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-02-27 18:14 UTC, jilljenn commented
Ça y est, on a des maths dans le JavaScript, ça ne rigole plus !

2017-02-27 18:49 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-02-27 19:02 UTC, jilljenn commented
Exemple : [GET /api/assessments/1](http://360-compute-level-of-assessment.pix.beta.gouv.fr/api/assessments/1)

    estimated-level: 2.5
    pix-score: 16
    not-acquired: ["@rechinfo2"]
    acquired: ["@support1", "@modèleEco2"]

2017-02-28 08:35 UTC, bdavidxyz commented on api/tests/acceptance/application/analysis-utils_test.js
> +
Pas assez de test unitaires au vu de la complexité de la fonction. Est-ce possible de rajouter des cas de figure dans le test U?

2017-02-28 08:36 UTC, bdavidxyz commented on api/tests/acceptance/application/analysis-utils_test.js
> +  describe('#proba', function () {
"Proba" n'est pas assez explicite. Proba de quoi ?

2017-02-28 08:36 UTC, bdavidxyz commented on api/tests/acceptance/application/analysis-utils_test.js
> +      { title: 'various arguments are passed', theta: Math.log(0.5), diff: 0, answer: 1/3 },
Difficile à comprendre pour un profane.

2017-02-28 08:39 UTC, bdavidxyz commented on api/tests/acceptance/application/assessment-controller-get_test.js
> +      // XXX: incomplete test, should also demonstrate that it returns the whole answer grape.
Enlever le XXX, désormais c'est bon on fait l'assertion sur toute la grappe des answers

2017-02-28 08:40 UTC, bdavidxyz commented on api/tests/acceptance/application/assessment-controller-get_test.js
> +      // XXX: incomplete test, should also demonstrate that it returns the whole answer grape.
le XXX est à 2 endroits, les supprimer ts les 2

2017-02-28 08:40 UTC, bdavidxyz commented on api/tests/acceptance/application/analysis-utils_test.js
> +      { title: 'various arguments are passed', theta: Math.log(0.5), diff: 0, answer: 1/3 },
Est-ce que quelqu'un qui s'y connaît y comprendrais quelque chose avec ces 2 cas de test ?

2017-02-28 08:41 UTC, bdavidxyz commented on api/lib/application/assessments/assessment-controller.js
> +                      if (answer.result == 'ok') {
Pas de == en JS !! _.isEqual, ou bien ===

2017-02-28 08:41 UTC, bdavidxyz commented on api/lib/application/assessments/assessment-controller.js
> +                    for(let level = 0; level <= 6; level += 0.5) {
fonction _.times en lodash. Normalement on n'utilise plus de boucle for.

2017-03-01 07:55 UTC, jilljenn commented on api/tests/acceptance/application/analysis-utils_test.js
> +
Ça calcule juste une formule. Y a pas de bête if à tester, tu lui donnes deux valeurs et il t'en renvoie une. Pas de risque d'exception. J'ai éclairci les intitulés des tests, et renommé.

2017-03-01 07:56 UTC, jilljenn commented on api/lib/application/assessments/assessment-controller.js
> +                    for(let level = 0; level <= 6; level += 0.5) {
Je sais mais faut que je fasse une itération sur les valeurs de 0 à 7 avec un pas de 0,5 et si je fais ça avec _.times le code sera illisible pour quelqu'un qui ne connait pas lodash. Là le for tout le monde le comprend.

2017-03-01 07:59 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-01 08:32 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-02 14:23 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-10 19:21 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-13 09:36 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +    assessment.attributes.estimatedLevel = estimatedLevel;  // For the reviewer: maybe this is a hack?
Comment faire ceci proprement ?

2017-03-13 10:39 UTC, jbuget requested changes

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/challenge-service.js
> +    _.forEach(challengeList, challenge => {
idem que ci-dessus : privilégier les méthodes du langage, donc `challengeList.forEach(challenge => { ... })`

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +        } else {
l'approche que je privilégie dans ce type de code identique, c'est : 

1. déclarer les variables avec la valeur par défaut
2. ne gérer qu'un seul `if`
3. ne gérer qu'une seule assignation

```javascript
// déclaration des valeurs par défaut, qu'on peut repérer directement
left outcome = 0;
let wellNommedValue = -1;

// un seul "if" qui met bien en avant le cas traité
if (answer.get('result') === 'ok') {
  outcome = 1;
  wellNommedValue = 1;
}

// le traitement n'est joué qu'une seule fois
performanceHistory.push({difficulty, outcome});
acquiredKnowledgeTags.push(..._propagateKnowledge(knowledgeData.knowledgeTagSet, mainKnowledgeTag, wellNommedValue));
```

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    const nbKnowledgeTags = firstFiveLevels.map(level => nbKnowledgeTagsByLevel[level]).reduce((a, b) => a + b);
ici, le callback reduce est dupliqué, je pense qu'on peut sortir la méthode `add` et faire du coup un `reduce(add)`

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +  populateScore(assessment, answers, knowledgeData) {
Woy ! elle fait mal celle-là :-)

1. mettre des tests unitaires : t'es dans un service, t'as la main sur tout. au pire tu stub / mock.
2. une fois que tu as tes tests, découper ta méthode en sous-méthodes bien nommées
3. refactorer : avoir une seule façon de faire des boucles for (utiliser la méthode standard `Array#forEach()`, remplacer `if (challenge !== 'undefined')` par `if (challenge)` directement

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    assessment.attributes.estimatedLevel = estimatedLevel;  // For the reviewer: maybe this is a hack?
normalement `assessment`est de type `Bookshelf.Model`. Tu ne devrais pas t'amuser à tripoter `attributes` mais faire des `set('property', value)`.

```javascript
assessment.set('estimatedLevel', estimatedLevel);
```

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/challenge-service.js
> +      if(challenge.knowledgeTags !== undefined && challenge.knowledgeTags.length > 0) {
Si tu fais du JavaScript propre, tu ne devrais JAMAIS à avoir à utiliser le mot clé `undefined`.

En l'occurrence, je ferais : 

```javascript
if (challenge.knowledgeTags && challenge.knowledgeTags.length > 0)) { 
  ... 
}
```

ou pour le coup utiliser la méthode qui va bien dans lodash (dont j'ai oublié le nom).

2017-03-13 10:39 UTC, jbuget commented on api/lib/domain/services/challenge-service.js
> +      challengesById: challengesById,
rappel : on n'a pas besoin d'assigner de valeur à des propriétés portant le même nom. Ex :

```javascript
return {
  challengesById,
  knowledgeTagSet
};

```

2017-03-13 10:39 UTC, jbuget commented on api/tests/acceptance/application/analysis-utils_test.js
> +
Je plussoie David. Les tests, ce n'est pas que pour gérer les exceptions. Ça, ce n'est que du sucre. Le réel intérêt des tests est ailleurs :

- aider à la conception (quand on fait du TDD)
- documenter le code (on parle même de "documentation vivante")
- se couvrir d'un harnais de sécurité pour refactorer, corriger et faire évoluer le code en toute sérénité / productivité

Il est plus simple de comprendre par l'exemple du code qu'en déchiffrant les méthodes et symboles utilisés.

2017-03-16 14:38 UTC, jilljenn commented on api/tests/acceptance/application/analysis-utils_test.js
> +
Une formule de maths reste une formule de maths. Pour l'expliquer il faut des commentaires.

2017-03-16 14:43 UTC, jilljenn commented on api/tests/acceptance/application/analysis-utils_test.js
> +
De toute façon je ne me sers plus de ce code mais je vais m'en servir bientôt, tu veux que je supprime ?

2017-03-16 14:59 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +    assessment.attributes.estimatedLevel = estimatedLevel;  // For the reviewer: maybe this is a hack?
Je viens de remplacer, ça ne fonctionne plus. Je vais chercher pourquoi.

2017-03-16 15:16 UTC, jilljenn commented on api/tests/acceptance/application/analysis-utils_test.js
> +
Supprimé. Je le rechargerai lors d'une future PR.

2017-03-16 15:16 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +    assessment.attributes.estimatedLevel = estimatedLevel;  // For the reviewer: maybe this is a hack?
Ça marche !

2017-03-16 15:17 UTC, jilljenn commented on api/lib/domain/services/challenge-service.js
> +    _.forEach(challengeList, challenge => {
OK.

2017-03-16 15:17 UTC, jilljenn commented on api/lib/domain/services/challenge-service.js
> +      if(challenge.knowledgeTags !== undefined && challenge.knowledgeTags.length > 0) {
OK.

2017-03-16 15:18 UTC, jilljenn commented on api/lib/domain/services/challenge-service.js
> +      challengesById: challengesById,
Je ne savais pas ! Merci.

2017-03-16 15:19 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +  populateScore(assessment, answers, knowledgeData) {
Je croyais qu'il fallait aussi tester les sous-méthodes mais j'ai cru comprendre que tu me disais qu'il n'y avait pas besoin si seule une fonction l'utilisait.

2017-03-23 12:45 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +        } else {
`wellNamedValue`* mais d'accord, j'ai bien compris la leçon, merci :)

2017-03-23 12:50 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +        } else {
Attention, dans un cas j'ajoute à `acquiredKnowledgeTags`, dans l'autre j'ajoute à `notAcquiredKnowledgeTags` !

2017-03-23 12:56 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +    const nbKnowledgeTags = firstFiveLevels.map(level => nbKnowledgeTagsByLevel[level]).reduce((a, b) => a + b);
Fait avec `_add`.

2017-03-23 13:10 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-23 13:12 UTC, jilljenn commented
Souci : après merge, je peine à réparer cette erreur :

    TypeError: Attempted to wrap get which is already wrapped

dû aux `sinon.stub(courseRepository, 'get')`.

2017-03-23 13:22 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-03-24 21:51 UTC, jilljenn commented
C'est bon !

2017-04-04 15:29 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-04-07 13:51 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-04-07 15:29 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-04-20 02:11 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-04-20 09:13 UTC, jbuget approved these changes

2017-04-20 13:14 UTC, jbuget commented
I've deployed this PR to http://360-compute-level-of-assessment.pix.beta.gouv.fr. Please check it out

2017-04-20 13:15 UTC, jbuget commented
Là aussi il y aura pas mal de refactoring à faire dans le futur, mais pour la santé de tous et du projet il faut avancer. On prendra le temps de refactorer de façon itérative quand on viendra à toucher le code associé #BSR.

2017-04-20 13:22 UTC, merged