Cleanup refactor index page
sgmap/pix pull request #288
Opened 2017-02-15 09:28 UTC by jbuget

2017-02-15 14:48 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 14:56 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 15:43 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 16:07 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 16:19 UTC, bdavidxyz commented on live/app/components/course-item.js
> +  // Private
Pourquoi "private"

2017-02-15 16:21 UTC, bdavidxyz commented on live/app/routes/index.js
> +  tmpCourse: null,
Unused variable ?

2017-02-15 16:23 UTC, bdavidxyz commented on live/app/templates/components/course-item.hbs
> +    <button {{action "startCourse" course}} class="course-item__action course-item__action--start button">
Non, le commentaire est clair, il faut garder le style="cursor: pointer;" si on veut que ça marche sur iPhone

2017-02-15 16:24 UTC, bdavidxyz commented on live/tests/integration/components/course-list-test.js
> +describe.only('Integration | Component | course list', function () {
Non. "only" va skipper les autres tests

2017-02-15 16:24 UTC, bdavidxyz requested changes
Quelques trucs bloquants, bien que je n'ai pas encore fait de review en profondeur.

2017-02-15 16:43 UTC, jbuget commented on live/app/templates/components/course-item.hbs
> +    <button {{action "startCourse" course}} class="course-item__action course-item__action--start button">
Ah zut, j'avais pas lu le commentaire. J'ai juste vu qu'il y avait un lien sourcé, c'est pour ça que je l'ai laissé. Je corrige.

2017-02-15 16:46 UTC, jbuget commented on live/app/components/course-item.js
> +  // Private
C'est Pierre qui a proposé de mettre une section `// private` dans laquelle on met les propriétés d'un composant, pour les rendre explicites. J'étais prêt à m'asseoir sur ma phobie des commentaires pour suivre cette pratique. Autre proposition : "on s'efforce de toujours déclarer en premier lieu les propriétés d'un composant (et on ne met pas de commentaires)"

2017-02-15 16:46 UTC, jbuget commented on live/app/routes/index.js
> +  tmpCourse: null,
bien vu, merci !

2017-02-15 16:47 UTC, jbuget commented on live/tests/integration/components/course-list-test.js
> +describe.only('Integration | Component | course list', function () {
argh.... désolé

2017-02-15 16:56 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 16:58 UTC, jbuget commented
Elle a pris cher ma couverture de code avec le découpage en composants...

2017-02-15 17:27 UTC, bdavidxyz commented on live/app/components/course-list.js
> +  // private
pourquoi private ?

2017-02-15 17:29 UTC, bdavidxyz commented on live/app/components/course-list.js
> +      if (this._isMobile() && !localStorage.getItem('pix-mobile-warning')) {
soit mettre le commentaire "display warning only once to user"
soit mettre une sous-fonction "userNotAlreadyWarned"

2017-02-15 17:31 UTC, bdavidxyz commented on live/app/routes/courses/create-assessment.js
>      // FIXME: manage the case when assessment's course has no challenge
retirer le FIXME. Le cas où l'assessment n'a pas de challenge est déjà géré, il suffit que backend renvoie "null" dès le premier coup, et ça marche.

2017-02-15 17:33 UTC, bdavidxyz commented on live/app/styles/components/challenge-stay.css
> +@media (min-width: 700px) {
rajouter un XXX sur le fait qu'il n'y a pas encore d'accord sur la syntaxe. 

Du coup on trouve les 2 versions dans le code : nested, et non-nested. bof, bof.

2017-02-15 17:33 UTC, bdavidxyz commented on live/app/styles/components/course-item.css
> +.course-item__action--start:hover {
Quelle science du BEM

2017-02-15 17:33 UTC, bdavidxyz commented on live/app/styles/components/first-page.css
> -
Joli drop, 3 points

2017-02-15 17:38 UTC, bdavidxyz commented on live/app/styles/index.css
> +  .index-page-hero__box-item {
même remarque que ci-dessus.

2017-02-15 17:38 UTC, bdavidxyz commented on live/app/styles/index.css
> +  .index-page-hero__main-value-prop {
Idem

2017-02-15 17:39 UTC, bdavidxyz commented on live/app/styles/index.css
> +@media (min-width: 992px) {
Idem

2017-02-15 17:39 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-challenges__cards .container {
Wooops on sort de BEM

2017-02-15 17:39 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course {
Woooooops encore pire (3 selecteur au lieu d'un)

2017-02-15 17:40 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-picture {
Wooooooooops, et de 4 :)

2017-02-15 17:40 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-content {
hors BEM

2017-02-15 17:40 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-name {
hors BEM

2017-02-15 17:40 UTC, bdavidxyz commented on live/app/styles/index.css
> +@media (min-width: 992px) {
Non nested

2017-02-15 17:41 UTC, bdavidxyz commented on live/app/styles/index.css
> +.index-page-about a {
Non BEM

2017-02-15 17:42 UTC, bdavidxyz commented on live/app/templates/components/modal-mobile.hbs
> +  <div class="modal fade js-modal-mobile" tabindex="-1" role="dialog" id="js-modal-mobile">
Si jamais il y a d'autres relecteur : cette modal-mobile sera le prochain truc que je clean, tellement on fait des trucs immondes dessus. Mais bon, c'était notre première modale. Donc on laisse tel quel pour cette PR.

2017-02-15 17:43 UTC, bdavidxyz commented on live/tests/integration/components/course-item-test.js
> +      // given
+12 pour le given when then systématique :)

2017-02-15 18:47 UTC, jbuget commented on live/app/components/course-list.js
> +  // private
je supprime. on est OK pour la convention proposée tout à l'heure ?

2017-02-15 18:48 UTC, jbuget commented on live/app/components/course-list.js
> +      if (this._isMobile() && !localStorage.getItem('pix-mobile-warning')) {
-1000 pour le commentaire
+1 pour l'extraction dans une méthode bien nommée

2017-02-15 18:48 UTC, jbuget commented on live/app/routes/courses/create-assessment.js
>      // FIXME: manage the case when assessment's course has no challenge
ok

2017-02-15 18:53 UTC, jbuget commented on live/app/styles/components/challenge-stay.css
> +@media (min-width: 700px) {
// XXX c'est pour les cas vraiment compliqués / spéciaux, avec un lien / la source, pas pour des commentaires généraux rapport à l'organisation

euh.. tout le monde ne fait pas des media queries nested, ou alors je veux la preuve.

on a les 2 versions (et même 3) parcequ'on n'a pas de standards et que toi et moi on n'est pas aligné sur ce point / la stratégie.

En attendant, j'ai pris le parti de sortir les @media des classes que je croise MAIS de les laisser au plus proche de leur classe. La "solution naïve pile au milieu".

2017-02-15 18:54 UTC, jbuget commented on live/app/styles/components/first-page.css
> -
auto-drop grâce à un merveilleux reformattage automatique à chaque save action (elle aussi automatisée) ;-)

2017-02-15 18:55 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .container {
legacy trop imprégné (c'est pas faute d'avoir cherché à virer ce truc)

2017-02-15 18:57 UTC, jbuget commented on live/app/styles/index.css
> +  .index-page-hero__main-value-prop {
pas de standard défini

2017-02-15 18:57 UTC, jbuget commented on live/app/styles/index.css
> +  .index-page-hero__box-item {
-1 car pas de standard défini.

2017-02-15 19:18 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course {
idem

2017-02-15 19:18 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-picture {
idem

2017-02-15 19:19 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-content {
idem

2017-02-15 19:19 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .course-item .course .course-name {
idem

2017-02-15 19:19 UTC, jbuget commented on live/app/styles/index.css
> +@media (min-width: 992px) {
standard non défini

2017-02-15 19:19 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-about a {
legacy

2017-02-15 19:25 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-15 19:28 UTC, jbuget commented on live/app/styles/index.css
> +.index-page-challenges__cards .container {
la vrai remarque, c'est que cette classe est désormais obsolète, car située dans `course-list.css`. C'est un oubli de ma part. J'aurais dû la supprimer.

2017-02-15 19:47 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-16 10:40 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-16 11:04 UTC, jbuget commented
J'ai tenté de nettoyer le plus de choses en rapport avec la page d'accueil, mais je n'ai pas pu raisonnablement aller tout partout. 

- Je me suis cassé les dents (#souffrance #shame) sur la modale d'avertissement de support incomplet pour les devices mobile. 

- J'ai tenté de passer en BEM le plus de choses possibles. Je pense être parvenu à BEMifier un max de truc, en particulier dans les composants que j'ai sortis, mais il me reste toujours 3 ou 4 classes que je n'ai pas pu améliorer.

- Je pense qu'on peut désormais supprimer `first-page` qui est devenu un double composant : `course-list` et `course-item`.

Remarque : j'ai supprimé l'option dans la `course-list` permettant de fixer un nombre max de courses et dont on ne se sert pas.

- Au passage, je crois que ça corrige le bug #242 

- J'ai nettoyé un peu (en passant par un adapter custom) la façon d'accéder au "next-challenge" d'une évaluation.

- Enfin, j'ai homogénéisé les @media dans le CSS (sauf `email-form`dans la mesure où @yojecode travaille activement dessus). Dans le mesure où nous n'avons pas encore de standard d'équipe (ni de stratégie pour parvenir à l'appliquer), j'ai opté pour une solution à mi-chemin entre les 2 courants de pensées actuels : j'ai sorti les @media des classes mais je les ai à chaque fois mis juste en dessous de la classe en question. En attendant qu'on prenne le temps et le courage de décider EN EQUIPE et de façon définitive.

Je propose de s'en tenir là (modulo les tous petits oublis ou les petits trucs sales que j'aurais introduits) pour cette PR et de la merger si possible rapidement.

WDYT ?

2017-02-17 08:46 UTC, bdavidxyz commented on live/app/components/course-item.js
> +  course: null,
En théorie, pas besoin de le déclarer du tout.
En pratique, je préfère ce course: null.
Il nous manque un wiki de référence pour les pratiques Ember.

2017-02-17 08:48 UTC, bdavidxyz commented on live/app/components/course-list.js
> +function _userNotAlreadyWarnedAboutMobileIncompleteSupport(that) {
:1st_place_medal:

2017-02-17 08:48 UTC, bdavidxyz commented on live/app/components/course-list.js
> +function _displayWarningModel() {
"modal" et non "model"

2017-02-17 08:51 UTC, bdavidxyz commented on live/app/styles/index.css
> +  .index-page-hero__box-item {
pas d'accord : le code a déjà des nested queries, donc il faut s'aligner sur ce qui est déjà fait.
Qui plus est tout le monde par ailleurs le fait.

La bonne raison de fond est : ne pas avoir des sélecteurs CSS éparpillés partout.

2017-02-17 08:54 UTC, bdavidxyz submitted a review, later dismissed
Décidemment ça coince pour les nested media queries. Pas envie de me retrouver avec des sélecteur CSS éparpillés partout. C'est pourquoi tout le monde sur les Slack/Quora/Reddit/Stackoverflow conseille la version nested. 

Seul IDEA n'est pas au courant, mais ce n'est pas une raison pour pénaliser le projet.

Si on aime bien les standard on aime bien la version nested.

Je peux proposer

: => on accepte la PR (il reste qd mm 2 ou 3 remarques en +)
=> on sort postCSS
=> on nest les media queries

2017-02-20 13:38 UTC, jbuget commented
I've deployed this PR to http://cleanup-refactor-index-page.pix.beta.gouv.fr. Please check it out

2017-02-20 13:40 UTC, merged