first commit
sgmap/pix pull request #290
Opened 2017-02-15 10:44 UTC by MBrandone

2017-02-17 14:33 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-17 17:04 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-20 14:59 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-20 15:46 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-21 10:53 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-21 13:49 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-21 13:52 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-21 14:37 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-21 14:52 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-22 13:43 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-22 16:45 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-22 16:55 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-22 17:42 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-22 21:48 UTC, jbuget requested changes
Quelques micro-micro changements requis.
Dès qu'ils seront corrigés (<10mn), ce sera bon pour moi... à condition que la PR soit bien déployée en Review App !
Il semble y avoir un problème de déploiement... :-(

2017-02-22 21:48 UTC, jbuget commented on live/app/styles/components/comparison-window.scss
> +.comparison-window__header {
bien vu

2017-02-22 21:48 UTC, jbuget commented on live/tests/integration/components/comparison-window-test.js
> +      expect(this.$()).to.have.length(1);
Il est préférable d'utiliser la méthode `chai#lengthOf` : http://chaijs.com/api/bdd/#method_lengthof

2017-02-22 21:48 UTC, jbuget commented on live/tests/integration/components/comparison-window-test.js
> +      // given
`// given` est inutile ici. On peut retirer la clause (et la ligne blanche) partout où il n'y en a pas besoin.

2017-02-22 21:48 UTC, jbuget commented on live/tests/integration/components/qroc-solution-panel-test.js
> +    expect(this.$()).to.have.length(1);
idem que précédent sur `#lengthOf` au lieu de `length`

2017-02-22 21:48 UTC, jbuget commented on live/tests/integration/components/qroc-solution-panel-test.js
> +    // given
il s'agit d'une clause `// when` et la ligne `const input = this.$('input');` doit plutôt être dans le `// then`

2017-02-22 21:48 UTC, jbuget commented on live/tests/integration/components/qroc-solution-panel-test.js
> +});
Wahou ! c'est hyper clair ! Bravo :-)

2017-02-23 09:17 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-23 09:53 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-23 10:17 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-23 11:09 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-23 16:36 UTC, bdavidxyz commented on live/app/styles/components/qroc-solution-panel.scss
> +  font-family: var(--font-lato);
Attention c'est du Sass maintenant, il faut merger en local et faire les changements nécessaire

2017-02-24 14:48 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-24 14:49 UTC, florianEnoh commented on api/tests/acceptance/application/assessment-controller-get-nonadaptive_test.js
>          knex('assessments').insert([inserted_assessment]).then((rows) => {
CamelCase is better :) Cf: inserted_assessment

2017-02-24 14:49 UTC, florianEnoh commented on live/app/components/qroc-solution-panel.js
> +    return this.get('answer.value');
this.get('answer.value') a été déjà définie dans answer (Cf ligne 9)

2017-02-24 14:49 UTC, florianEnoh commented on live/app/components/qroc-solution-panel.js
> +    if (solutionVariants === null || solutionVariants === undefined){
Tu peux remplacer ce test par juste : if(solutionVariants) n'est-ce pas ?
cc @jbuget

2017-02-24 14:49 UTC, florianEnoh commented on live/app/components/qroc-solution-panel.js
> +    return solution;
Les 3 lignes peuvent être réduites en une seule instruction de la sorte :
return solutionVariants.slice(0, str.indexOf('\n'));

2017-02-24 14:49 UTC, florianEnoh commented on live/app/styles/components/qroc-solution-panel.scss
> +  font-family: var(--font-lato);
Tu auras après refacto : font-family: $font-lato;

2017-02-24 14:49 UTC, florianEnoh commented on live/tests/integration/components/qroc-solution-panel-test.js
> +      const assessment = Ember.Object.extend({ id: 'assessment_id' }).create();
Je ne connaissais pas cette notation. Elle sert à quoi stp ??? @MBrandone @jbuget

2017-02-24 15:07 UTC, MBrandone commented on live/app/components/qroc-solution-panel.js
> +    if (solutionVariants === null || solutionVariants === undefined){
bien vu (if(!solutionVariants))

2017-02-24 15:17 UTC, MBrandone commented on live/app/components/qroc-solution-panel.js
> +    return solution;
ok, mais on a pas toujours le '\n' dans les réponses possibles, dans le cas où il y a qu'une seule bonne réponse possible

2017-02-24 15:17 UTC, MBrandone commented on live/app/styles/components/qroc-solution-panel.scss
> +  font-family: var(--font-lato);
done

2017-02-24 15:29 UTC, jbuget commented
I've deployed this PR to http://323-compare-answers-solutions-QROC-QROCm.pix.beta.gouv.fr. Please check it out

2017-02-24 17:06 UTC, closed without merging