Enlarge challenges instructions width to 990px
sgmap/pix pull request #291
Opened 2017-02-15 15:21 UTC by yojecode

2017-02-17 08:42 UTC, bdavidxyz commented on live/app/styles/app.css
> +#assessment-challenge .container {
Non, on n'utilise jamais le sélecteur d'ID. On n'utilise pas non plus 2 sélecteur en théorie, ou alors on met un "XXX" en expliquant pourquoi.

2017-02-17 08:42 UTC, bdavidxyz commented on live/app/styles/app.css
> +  #assessment-challenge .container {
Non, on n'utilise jamais le sélecteur d'ID. On n'utilise pas non plus 2 sélecteur en théorie, ou alors on met un "XXX" en expliquant pourquoi.
Pourquoi la media queries n'est-elle-pas nested ?

2017-02-17 08:43 UTC, bdavidxyz requested changes
voir remarques

2017-02-17 09:07 UTC, yojecode commented on live/app/styles/app.css
> +  #assessment-challenge .container {
Le fait est que les éléments sont déjà impactés par boostrap.
J'utilise donc cette méthode pour :
- augmenter le poids de l'élément
- être sûr qu'il ne s'applique qu'à ce cas de figure

Mais ok pour mettre des XXX

2017-02-17 09:42 UTC, bdavidxyz commented on live/app/styles/app.css
> +/*XXX: On augmente le poids avec la class du parent afin d'overrider la class*/
afin d'overrider la classe ".container" qui vient de Bootstrap. C'est ça ?

2017-02-17 09:43 UTC, bdavidxyz commented on live/app/styles/app.css
> +@media (min-width: 1024px) {
IDEA n'est pas un standard de dev

2017-02-17 09:43 UTC, yojecode commented on live/app/styles/app.css
> +/*XXX: On augmente le poids avec la class du parent afin d'overrider la class*/
Oui exact

2017-02-17 09:44 UTC, yojecode commented on live/app/styles/app.css
> +@media (min-width: 1024px) {
Et donc ?

2017-02-17 09:46 UTC, jbuget commented
I've deployed this PR to http://295-agrandir-consignes-reponses.pix.beta.gouv.fr. Please check it out

2017-02-17 09:50 UTC, jbuget commented
I've deployed this PR to http://295-agrandir-consignes-reponses.pix.beta.gouv.fr. Please check it out

2017-02-17 10:34 UTC, yojecode commented on live/app/styles/app.css
> +#assessment-challenge .container {
changed !

2017-02-17 10:38 UTC, jbuget commented
I've deployed this PR to http://295-agrandir-consignes-reponses.pix.beta.gouv.fr. Please check it out

2017-02-20 08:38 UTC, jbuget requested changes

2017-02-20 08:38 UTC, jbuget commented on .gitignore
> +**/.gitkeep
Non ! il ne faut pas ignorer les .gitkeep. C'est une [convention adoptées par les utilisateurs de Git](http://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep), et qui permet de commiter des arborescences ([chose impossible dans le fonctionnement de Git](https://git.wiki.kernel.org/index.php/Git_FAQ#Can_I_add_empty_directories.3F)).

2017-02-20 08:43 UTC, merged

2017-02-20 08:46 UTC, jbuget commented
I've deployed this PR to http://295-agrandir-consignes-reponses.pix.beta.gouv.fr. Please check it out