[CLEANUP] Remove PostCSS
sgmap/pix pull request #292
Opened 2017-02-17 15:41 UTC by bdavidxyz

2017-02-17 16:27 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 16:39 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 16:56 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 17:05 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 17:15 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 17:22 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 17:49 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 17:59 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 18:34 UTC, jbuget reviewed
Nice ! juste, une remarque sur la config de sass dans le ember-cli.

2017-02-17 18:34 UTC, jbuget commented on live/ember-cli-build.js
> +    sassOptions: {}
je pense que depuis Ember 2.11, il n'y en a pas besoin. tu peux essayer et confirmer (ou infirmer) stp ?

2017-02-17 19:15 UTC, bdavidxyz commented on live/ember-cli-build.js
> +    sassOptions: {}
je vais tester, mais c'est pas mal de le laisser pour signifier que le build se fait en Sass.

2017-02-17 19:23 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 19:38 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-17 19:47 UTC, bdavidxyz commented
Help j'ai un bug sur la RA

Allez sur la page d'accueil et cliquez sur "Démarrer un test"... rien ne se passe, gasp :-(

Dans la console :

Unexpected token < in JSON at position 0

2017-02-18 15:19 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-18 16:50 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-18 16:56 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-18 17:37 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 08:14 UTC, jbuget submitted a review, later dismissed
Je ne comprends vraiment pas le rôle du prefilter, qui me semble être la cause du bug. Par ailleurs, c'est vraiment dommage de ne pas avoir fait cette PR après avoir intégré la PR de refactoring #288 , car qu'on commence par l'une ou l'autre, il faudra faire un gros merge. Je pense très sincèrement et fortement qu'il est préférable de merger #288 puis #292 dans cet ordre, au risque de se faire vraiment très mal.

2017-02-20 08:14 UTC, jbuget commented on live/app/initializers/ajax-prefilter.js
> +export default {
Je pense que l'origine du bug est là. 

Une partie de la communication front--back est portée par Nginx. Il ne faut pas manipuler les URL. Le seul endroit autorisé au niveau applicatif est dans un adapter. Par ailleurs, on ne devrait jamais manipuler directement l'object jQuery (ou son alias `$`) pour tout ce qui est traitement AJAX. C'est la charge d'Ember. Et quand bien même c'est pas une mauvaise idée (ex : `/assessments/:assesment_id/challenges/next`), il faut passer par la surcharge de jQuery gérée par Ember : `Ember.$`.

Et sinon, question de fond, c'est quoi le but de ce bout de code ?

2017-02-20 08:14 UTC, jbuget commented on live/ember-cli-build.js
> +    sassOptions: {}
tu le vois direct que c'est fait en Sass : via les extensions de fichiers, via le package.json et via le terminal quand le bouzin transpile. à part ça : http://emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_ember-no-longer-supplied-via-code-bower-code

2017-02-20 08:46 UTC, bdavidxyz commented on live/app/initializers/ajax-prefilter.js
> +export default {
j'ai supprimé ce truc

2017-02-20 08:55 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 09:02 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 11:25 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 13:45 UTC, jbuget requested changes
Ce sera bon pour moi (tu pourras mettre un lgtm) dès qu'on aura mergé les fichiers en conflits et redispatcher les @media queries en nested sous les bonnes classes, histoire de clore définitivement et proprement le sujet.

2017-02-20 15:58 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 16:13 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 18:03 UTC, jbuget commented
I've deployed this PR to http://372-remove-postcss.pix.beta.gouv.fr. Please check it out

2017-02-20 18:13 UTC, jbuget approved these changes

2017-02-20 18:13 UTC, merged