Split get-result in sub components
sgmap/pix pull request #293
Opened 2017-02-17 17:52 UTC by yojecode

2017-02-20 18:21 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-21 09:41 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-21 15:59 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-21 17:53 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-22 17:40 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-23 17:12 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-24 11:13 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-02-27 09:49 UTC, jbuget requested changes
Des petits trucs, rien d'énorme

2017-02-27 09:49 UTC, jbuget commented on live/app/components/comparison-window.js
> +    if(!this.get('answer.result')) return ;
Il y en a vraiment besoin de cette ligne ? Ember ne gère-t-il pas le cas tout seul comme un grand ?
PS : il manque des espaces ;-)

2017-02-27 09:49 UTC, jbuget commented on live/app/components/result-item.js
> +      this.sendAction('openComparison', assessmentId, answerId, index);
Ne serait-il pas judicieux de transmettre directement les objets Model plutôt que forcer le composant papa à repasser par le store ? (rappel : le non est acquis et je m'attends à être challengé)

2017-02-27 09:49 UTC, jbuget commented on live/app/routes/assessments/get-results.js
>      openComparison: function (assessment_id, answer_id, index) {
même remarque que plus haut, ne serait-il pas mieux de passer directement les objets Model en paramètres ?

2017-02-27 09:49 UTC, jbuget commented on live/app/styles/components/comparison-window.scss
> +.assessment-comparison__title {
Le fichier et son composant s'intitulent "comparison-window".
Ne serait-il pas judicieux d'intituler les classes de la même façon ?
En particulier, dans ce cas, ça "semble" facile.

2017-02-27 09:49 UTC, jbuget commented on live/app/styles/components/get-results.scss
> +  &:hover {
il me semblait qu'on s'était mis d'accord pour ne nester que les @media queries. Est-ce qu'on décide d'incorporer les "statuts" de classes ? (c'est une vraie question)

2017-02-27 09:49 UTC, jbuget commented on live/app/styles/components/get-results.scss
> +.assessment-results__link-back{
merci pour cette passe de BEM :-)

2017-02-27 09:49 UTC, jbuget commented on live/app/styles/components/result-item.scss
> +.result-list__icon {
créer une issue pour nettoyer et BEMifier tout ça.
attention au nesting !

2017-02-27 09:49 UTC, jbuget commented on live/app/templates/assessments/get-results.hbs
> +      {{#link-to 'index' class='assessment-results__index-link__element' tagName='button'}}
si j'ai bien compris BEM, une classe ne doit pas contenir 2 descriptifs d'éléments

2017-02-27 09:49 UTC, jbuget commented on live/app/templates/components/comparison-window.hbs
> +          <div data-toggle="tooltip" data-placement="top" title="{{resultItemContent.title_tooltip}}">
`title_tooltip` ne devrait-il pas être écrit plutôt en `camelCase` ?

2017-02-27 09:49 UTC, jbuget commented on live/app/templates/components/get-result.hbs
> +    <!--/div-->
code mort

2017-02-27 09:49 UTC, jbuget commented on live/tests/acceptance/j1-compare-answer-solution-qcm-test.js
> +      //expect($(LABEL_CORRECT_AND_CHECKED)).to.have.lengthOf(0);
c'est normal que l'assertion soit en commentaire ? si oui, ---> code mort, sinon ---> risque de bug ?

2017-02-27 09:49 UTC, jbuget commented on live/tests/unit/components/result-item-test.js
> +        initComponent.call(this);
j'ai l'impression qu'il n'y a aucun intérêt à définir une méthode `initComponent` dans ce cas là. Je vois même des inconvénients : 
- ça rajoute des lignes de code ---> "moins y a de code, mieux on se porte"
- ça oblige d'utiliser `call(this)` ---> bad smell

WDYT ?

2017-02-28 10:40 UTC, yojecode commented on live/app/components/comparison-window.js
> +    if(!this.get('answer.result')) return ;
Il me semble que j'ai dû rajouter cette ligne parce que je n'avais pas le comportement attendu car il rentre dans la boucle dès que quelque lui est passé en paramètre

2017-02-28 10:40 UTC, yojecode commented on live/app/components/result-item.js
> +      this.sendAction('openComparison', assessmentId, answerId, index);
Le composant parent lui-même ne fais rien de plus qu'une transition avec comme arguments ces id.
Oui c'est possible, à condition de refactorer au moins deux composants : La route (parent) et le model openComparison et c'est couteux. 

Vu le temps déjà passé dessus, je propose plutôt une issue afin de faire une passe dessus lorsqu'on devra faire évoluer le composant comparison

2017-02-28 10:52 UTC, yojecode commented on live/app/styles/components/get-results.scss
> +  &:hover {
Je suis pour le fait nester un max de propriétés, statuts, media queries relatives à un même objet.
D'une part pour lecture et d'autres parts pour le gain de temps en terme d'instructions à taper au clavier. l'héritage fait parti dans ce cas pour ainsi dire de la Sass-way !

2017-02-28 10:52 UTC, yojecode commented on live/app/styles/components/get-results.scss
> +.assessment-results__link-back{
:)

2017-02-28 10:52 UTC, yojecode commented on live/app/templates/components/comparison-window.hbs
> +          <div data-toggle="tooltip" data-placement="top" title="{{resultItemContent.title_tooltip}}">
bien vu :)

2017-02-28 10:52 UTC, yojecode commented on live/app/templates/components/get-result.hbs
> +    <!--/div-->
Le fichier en lui-même n'est plus utilisé. donc il sera supprimé

2017-02-28 10:52 UTC, yojecode commented on live/tests/acceptance/j1-compare-answer-solution-qcm-test.js
> +      //expect($(LABEL_CORRECT_AND_CHECKED)).to.have.lengthOf(0);
Je l'avais laissé en attendant ton avis sur l'utilisation de to.exist ou lenghtOh(0).
Je supprime le code mort !

2017-02-28 10:52 UTC, yojecode commented on live/tests/unit/components/result-item-test.js
> +        initComponent.call(this);
Je prévois finalement de mettre l'initialisation du composant dans un before.

2017-02-28 13:36 UTC, yojecode commented on live/app/styles/components/comparison-window.scss
> +.assessment-comparison__title {
Done !

2017-02-28 13:37 UTC, yojecode commented on live/app/styles/components/result-item.scss
> +.result-list__icon {
ok

2017-02-28 17:10 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-03-03 10:31 UTC, jbuget approved these changes

2017-03-03 10:48 UTC, jbuget commented
I've deployed this PR to http://341-afficher-resultat-test-ordre.pix.beta.gouv.fr. Please check it out

2017-03-06 16:53 UTC, merged