[#XXX][BUGFIX] Régression de getAssessmentSolutions dans le cas adaptatif
sgmap/pix pull request #297
Opened 2017-02-19 15:34 UTC by jilljenn

Et ajout des tests unitaires pour getAssessmentSolutions, qui étaient manquants.

2017-02-19 18:08 UTC, jbuget commented
I've deployed this PR to http://bugfix-get-assessment-solutions.pix.beta.gouv.fr. Please check it out

2017-02-20 10:42 UTC, bdavidxyz commented on api/tests/acceptance/application/assessment-controller_test.js
> +          // Keep scenarios for the other functions
scenarii

2017-02-20 10:43 UTC, bdavidxyz commented on api/lib/application/assessments/assessment-controller.js
> +                  const responsePattern = answers.map(answer => (answer.attributes.result == 'ok') ? 'ok' : 'ko').join('-');
illisible. Pas de double equal (==) en JavaScript !!

2017-02-20 10:44 UTC, bdavidxyz commented on api/lib/domain/services/assessment-service.js
> +    Answer.where('id', 'IN', answerIds).orderBy('createdAt').fetchAll().then((answers) => { // FIXME
pourquoi FIXME ? Expliquer

2017-02-20 10:49 UTC, bdavidxyz requested changes
voir les qq remarques, c'est bon sinon

2017-02-20 17:08 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +    Answer.where('id', 'IN', answerIds).orderBy('createdAt').fetchAll().then((answers) => { // FIXME
Je pense que c'était parce que je n'avais pas mis le `createdAt` au bon endroit à l'époque et c'était hyper important (je l'avais mis après le `fetchAll`). De toute façon je viens de le mettre dans `answerRepository.findByAssessment`, c'est beaucoup plus propre.

2017-02-20 17:50 UTC, jilljenn commented
J'en ai profité pour créer un nouveau module `assessment-service-utils` et faire le café.

2017-02-20 18:10 UTC, jbuget requested changes
Je pense que ce n'est pas du tout un bon pattern d'avoir un truc du genre `*-service-*manager-*utils`. Je pense qu'on aurait pu se contenter de garder ces méthodes dans assessment-service. Et si jamais on souhaite les extraire dans un bidule-service-utils, alors
je m'attends à avoir des TU sur `#getResponsePattern(answers)`. Toujours dans ce même cas, je m'attends aussi à avoir une issue déclarée pour l'absence de TU sur `#getNextChallengesFromScenarios`

2017-02-20 18:10 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +      .then(nextChallengeId => resolve(nextChallengeId))
je pense qu'il est possible de faire directement : 
```javascript
.then(resolve)
.catch(reject);
```

2017-02-20 18:10 UTC, jbuget commented on api/lib/domain/services/assessment-service-utils.js
> +function getResponsePattern(answers) {
il manque les TU qui vont bien...

2017-02-20 18:10 UTC, jbuget commented on api/lib/domain/services/assessment-service-utils.js
> +  // if answers are correct, incorrect, partial, the response Pattern will be: 'ok-ko-ko'
... en plus, avec les TU, plus besoin de commentaires (puisqu'il suffit de regarder les cas de tests)

2017-02-20 18:10 UTC, jbuget commented on api/lib/domain/services/assessment-service-utils.js
> +function getNextChallengeFromScenarios(responsePattern) {
là aussi il manque des TU (par contre il sont beaucoup moins faciles que la méthode précédente, donc je me contenterai d'une issue pour cette méthode)

2017-02-20 18:51 UTC, jilljenn commented on api/lib/domain/services/assessment-service-utils.js
> +function getNextChallengeFromScenarios(responsePattern) {
C'est vrai qu'on doit pouvoir s'inspirer des tests existants pour le contrôleur pour faire des tests unitaires pour getNextChallengeFromScenarios ! (Mais on est d'accord que même s'ils restaient dans `assessment-service`, il faudrait des tests unitaires ?) J'ai fait ça parce que du code de getAssessmentSolutions pouvait taper dans les mêmes fonctions pour éviter de dupliquer du code.

2017-02-20 19:00 UTC, jilljenn commented on api/lib/domain/services/assessment-service.js
> +      .then(nextChallengeId => resolve(nextChallengeId))
Super élégant !

2017-02-20 19:17 UTC, jbuget commented
I've deployed this PR to http://bugfix-get-assessment-solutions.pix.beta.gouv.fr. Please check it out

2017-02-20 19:20 UTC, jilljenn commented
Cette PR résout #287 et sera améliorée par #299.

2017-02-20 22:00 UTC, jbuget approved these changes

2017-02-20 22:01 UTC, merged