Boldify challenge instruction
sgmap/pix pull request #314
Opened 2017-02-24 15:45 UTC by yojecode

2017-02-24 16:15 UTC, jbuget commented
I've deployed this PR to http://388-augmenter-gras-challenge-instruction.pix.beta.gouv.fr. Please check it out

2017-02-24 17:16 UTC, jbuget commented
I've deployed this PR to http://388-augmenter-gras-challenge-instruction.pix.beta.gouv.fr. Please check it out

2017-02-27 17:22 UTC, jbuget commented
I've deployed this PR to http://388-augmenter-gras-challenge-instruction.pix.beta.gouv.fr. Please check it out

2017-02-28 15:21 UTC, bdavidxyz commented on live/app/styles/components/challenge-statement.scss
> +  -webkit-font-smoothing: antialiased !important;
Non pas de préfixage, c'est le travail d'auto prefixr. Est-ce qu'il y a un bug si les préfixes ne sont pas inclus ?

2017-02-28 15:22 UTC, bdavidxyz commented on live/app/styles/components/challenge-statement.scss
> +  -moz-osx-font-smoothing: grayscale;
Pas de préfixe vendeur

2017-02-28 15:22 UTC, bdavidxyz commented on live/config/environment.js
> +      'Lato:300,400,700,900', // main font
Attention chaque font "pèse" dans le chargement, il faut être sûr et certain de l'utilisation de chaque poids. Est-ce le cas ? Ici ça vaudrait presque le coup de citer des exemples d'utilisation de chacun.

2017-02-28 15:23 UTC, bdavidxyz requested changes
Non, pas de préfixe vendeur. Si il y en a besoin, c'est que Autoprefixr n'est pas inclu dans le projet et qu'il faut d'urgence le rajouter https://github.com/kimroen/ember-cli-autoprefixer

2017-02-28 17:21 UTC, yojecode commented on live/config/environment.js
> +      'Lato:300,400,700,900', // main font
ok

2017-02-28 17:25 UTC, yojecode commented on live/app/styles/components/challenge-statement.scss
> +  -moz-osx-font-smoothing: grayscale;
OK compris !
Du coup ça serait quoi la syntaxe dans ce cas précis ? je ne trouve pas d'exemple dans le projet :(

2017-02-28 21:43 UTC, bdavidxyz commented on live/config/environment.js
> +      'Lato:400,700,900', // main font, Challenge instructions
400 = default font (body, instructions...)
700 = some bold text (window comparison, warning mobile)
900 = only for strong emphasis (this screen and that screen)

2017-02-28 21:43 UTC, bdavidxyz commented on live/ember-cli-build.js
> +      browsers: ['last 2 versions'],
super

2017-02-28 21:43 UTC, bdavidxyz commented on live/package.json
> +    "ember-cli-autoprefixer": "0.6.0",
excellent

2017-02-28 21:43 UTC, bdavidxyz submitted a review, later dismissed
C'est presque bon

2017-03-01 16:37 UTC, jbuget commented on live/config/environment.js
> +      'Lato:400,700,900', // main font, Challenge instructions
Est-ce que ce ne serait pas encore mieux d'avoir une variable Sass pour la taille des polices. Perso, l'intégration de Google-Fonts en l'état ne me choque pas dans la mesure où elle correspond à la doc : https://github.com/damiencaselli/ember-cli-google-fonts#declare-fonts.

2017-03-01 16:45 UTC, jbuget commented on live/config/environment.js
> +      'Lato:400,700,900', // main font, Challenge instructions
j'ai créée une issue #321 pour mieux gérer les font-size en utilisant des variables Sass.

2017-03-01 16:48 UTC, jbuget commented
I've deployed this PR to http://388-augmenter-gras-challenge-instruction.pix.beta.gouv.fr. Please check it out

2017-03-01 17:32 UTC, jbuget commented
I've deployed this PR to http://388-augmenter-gras-challenge-instruction.pix.beta.gouv.fr. Please check it out

2017-03-02 08:53 UTC, merged