Refacto and clean warning-page component
sgmap/pix pull request #316
Opened 2017-02-27 15:42 UTC by yojecode

2017-02-27 17:41 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-02-28 10:22 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-02-28 15:13 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  if (!_.isInteger(s) || !s || s === null)  return 0;
Non, ce n'est pas cohérent. !s renvoie true si s est null. !_.isInteger renvoie true si s est null.

Je pense qu'il faut généraliser le _.isNotString et _.isNotArray de live/app/utils/lodash-custom.js

En créant une fonction _.isNotInteger, et je pense que le seul appel de if (_.isNotInteger(s)) suffit

2017-02-28 15:15 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  _getTime(allocatedTime){
Le standard choisi sur le projet est de mettre un espace avant le {, et un espace avant la première parenthèse

2017-02-28 15:16 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  _getSeconds(seconds){
idem

2017-02-28 15:16 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  _getMinutes(minutes){
idem

2017-02-28 15:16 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  if(type=='jauge') {
pas de double equal en JS ! Attention aux espaces (voir plus bas)

2017-02-28 15:17 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  _formatTimeToHuman(allocatedTime){
attention aux espaces

2017-02-28 15:17 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    const glue = (time[0]<1 || time[1]<1)? '' : ' et ';
idem je rajouterais des espaces avant/après les opérateurs

2017-02-28 15:19 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  allocatedTime: Ember.computed('time', function(){
Est-ce que allocatedTime sert encore à quelque chose ?

2017-02-28 15:20 UTC, bdavidxyz commented on live/tests/unit/components/warning-time-page-test.js
> +    it('should return 1:00 when passing 60', function () {
qui ça "it" ? Quelle propriété ?

2017-02-28 15:20 UTC, bdavidxyz commented on live/tests/unit/components/warning-time-page-test.js
> +    it('should return 1:01 when passing 61', function () {
Quelle propriété ?

2017-02-28 15:20 UTC, bdavidxyz commented on live/tests/unit/components/warning-time-page-test.js
> +    it('should return 1:10 when passing 70', function () {
Qui ça ?

2017-02-28 15:20 UTC, bdavidxyz commented on live/tests/unit/components/warning-time-page-test.js
> +    it('should return 2:01 when passing 121', function () {
qui ?

2017-02-28 15:20 UTC, bdavidxyz reviewed
See many comments below

2017-02-28 15:21 UTC, bdavidxyz requested changes
See many comments below

2017-02-28 17:41 UTC, yojecode commented on live/app/components/warning-page.js
> +  if (!_.isInteger(s) || !s || s === null)  return 0;
Je suis ok pour créer _.isNotInteger ça fait plus propre.
Juste faire remarquer qu'il y a quand même un test pour vérifier si 's' est null donc le cas ou null renverrais true est aussi couvert n'est-ce pas ?

2017-02-28 17:42 UTC, yojecode commented on live/app/components/warning-page.js
> +  allocatedTime: Ember.computed('time', function(){
Oui

2017-02-28 17:50 UTC, yojecode commented on live/app/components/warning-page.js
> +  _formatTimeToHuman(allocatedTime){
??

2017-02-28 21:33 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    return (seconds<1)? '' : seconds + this._pluralize(' seconde', seconds);
espaces

2017-02-28 21:33 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    return (minutes<1)? '' : minutes + this._pluralize(' minute', minutes);
espaces ?

2017-02-28 21:34 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +  if(type === 'jauge') {
bizarre ce type === jauge. A voir si on ne devrait pas séparer en 2 fonctions utilitaires distinctes. Est-ce que tu peux mettre un exemple pour chaque cas ?

2017-02-28 21:35 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    if(! allocatedTime || allocatedTime === 0) return '';
!a vaut true si a vaut 0, donc ! allocatedTime suffit

2017-02-28 21:36 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    return fmtMSS(this.get('time'), 'jauge');
bof, il vaut mieux créer une fonction différente pour chaque cas d'utilisation.

2017-02-28 21:36 UTC, bdavidxyz commented on live/app/components/warning-page.js
> +    return fmtMSS(this.get('time'), 'jauge');
Pas bloquant ceci dit.

2017-02-28 21:38 UTC, bdavidxyz commented on live/app/utils/lodash-custom.js
> +  isNotInteger: function (x) {
Trop compliqué. Il suffit de retourner !_.isInteger

2017-02-28 21:40 UTC, bdavidxyz commented on live/tests/unit/utils/lodash-custom-test.js
> +  describe('#isNotInteger(s)', function () {
Test pas obligatoire, on fait confiance à LoDash ici si il s'agit juste de retourner le contraire de _.isInteger

2017-02-28 21:40 UTC, bdavidxyz commented on live/app/utils/lodash-custom.js
> +  isNotInteger: function (x) {
Il manque au-dessus de la fonction  /* istanbul ignore next */

2017-02-28 21:41 UTC, bdavidxyz requested changes
Encore qq trucs à revoir, on verra demain à l'incubateur

2017-02-28 22:30 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-03-01 00:21 UTC, jbuget commented on live/app/components/warning-page.js
> +    return (seconds<1)? '' : seconds + this._pluralize(' seconde', seconds);
je propose de configurer l'auto-formattage au save-action (sur IDEA c'est ici : http://stackoverflow.com/a/28748557/2120773)

2017-03-01 00:25 UTC, jbuget commented on live/tests/unit/utils/lodash-custom-test.js
> +  describe('#isNotInteger(s)', function () {
mon avis perso : je préfère voir un TU, même pour une fonction qui fait une ligne et un truc aussi débile que retourner un "non-machin" que pas de test. pour moi, ce test ne me dérange pas (en plus c'est pas compliqué et ça sert de "documentation vivante")

2017-03-02 11:18 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-03-02 11:27 UTC, jbuget commented on live/app/utils/lodash-custom.js
> +  isNotInteger: function (x) {
dans la mesure où cette méthode est testée, il n'y a pas besoin d'indiquer à Istanbul de ne pas tenir compte de ce code dans son calcul de couverture de code.

2017-03-02 11:34 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-03-02 11:40 UTC, bdavidxyz commented on live/tests/unit/utils/lodash-custom-test.js
> +
Mieux vaut pas de test que l'oubli des cas nominaux

2017-03-02 11:40 UTC, bdavidxyz submitted a review, later dismissed
manque au moins un cas de test

2017-03-02 11:57 UTC, jbuget commented
I've deployed this PR to http://370-clean-warning-timing-challenge.pix.beta.gouv.fr. Please check it out

2017-03-02 12:04 UTC, merged