390 bugfix remove loader blanc
sgmap/pix pull request #326
Opened 2017-03-06 13:20 UTC by yojecode

2017-03-07 13:24 UTC, jbuget commented
I've deployed this PR to http://390-bugfix-remove-loader-blanc.pix.beta.gouv.fr. Please check it out

2017-03-07 15:35 UTC, bdavidxyz commented on live/app/templates/courses.hbs
> +<div class="page courses-page">
non ce n'est pas la convention choisie. L'élément racine doit avoir le nom du composant JS. donc là "courses" comme nom de classe CSS.

2017-03-07 15:35 UTC, bdavidxyz commented on live/app/templates/index.hbs
non ce n'est pas la convention choisie. L'élément racine doit avoir le nom du composant JS. donc là "index" comme nom de classe CSS.

2017-03-07 15:35 UTC, bdavidxyz commented on live/app/templates/project.hbs
> +<div class="page project-page">
non ce n'est pas la convention choisie. L'élément racine doit avoir le nom du composant JS. donc là "project" comme nom de classe CSS.

2017-03-07 15:36 UTC, bdavidxyz commented on live/app/templates/assessments/get-comparison.hbs
>  {{comparison-window
non, c'était plus joli avec l'indentation

2017-03-07 15:36 UTC, bdavidxyz requested changes
voir commentaires

2017-03-10 09:00 UTC, jbuget commented on live/app/templates/courses.hbs
> +<div class="page courses-page">
Le nom de la classe correspond au nom du fichier dans le cas d'un composant.
Dans le cas d'une route, il faut suffixer par "-page".

cf. https://github.com/sgmap/pix/wiki/Standards-CSS#cas-dune-page-ou-view-component

2017-03-13 15:00 UTC, jbuget commented on live/app/templates/courses.hbs
> +<div class="page courses-page">
les classes ont été renommées dans la PR #333.

2017-03-13 15:00 UTC, jbuget commented on live/app/templates/index.hbs
les classes ont été renommées dans la PR #333.

2017-03-13 15:00 UTC, jbuget commented on live/app/templates/project.hbs
> +<div class="page project-page">
les classes ont été renommées dans la PR #333.

2017-03-13 15:02 UTC, jbuget commented on live/app/templates/assessments/get-comparison.hbs
>  {{comparison-window
l'indentation est toujours présente. c'est juste qu'elle vaut 2 espaces (comme dans .editorConfig) plutôt que 4.

2017-03-13 15:05 UTC, merged