Refactoring de qcm-comparison en composant
sgmap/pix pull request #332
Opened 2017-03-09 10:22 UTC by yojecode

2017-03-10 10:12 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-10 15:48 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-10 17:59 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-13 15:31 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-13 16:14 UTC, bdavidxyz commented on live/app/styles/components/qcm-solution-panel.scss
> +  color: #13c9a0;
variabiliser la couleur

2017-03-13 16:15 UTC, bdavidxyz commented on live/tests/acceptance/j2-compare-answer-solution-qroc-test.js
> +describe.skip('Acceptance | j2 - Comparer réponses et solutions pour un QROC | ', function () {
non. Le skip doit être enlevé

2017-03-13 16:17 UTC, bdavidxyz commented on live/tests/unit/utils/value-as-array-of-boolean-test.js
> +    { when: 'Empty String', input: '', expected: [] },
👍 bravo pour le "when"

2017-03-13 16:18 UTC, bdavidxyz commented on live/tests/unit/utils/proposals-as-array-test.js
> +    { data: '', expected: [] },
j'ajoute une issue, on doit faire aussi rentrer dans la discussion la présence obligatoire du "when". Pas la peine de corriger pour cette PR

2017-03-13 16:22 UTC, bdavidxyz commented on live/tests/unit/utils/proposals-as-array-test.js
> +    { data: '', expected: [] },
https://github.com/sgmap/pix/issues/339

2017-03-13 16:23 UTC, bdavidxyz commented on tests/unit/mixins/value-test.js
> +test('it works', function(assert) {
bizarre. code mort ?

2017-03-13 16:23 UTC, bdavidxyz commented on tests/unit/mixins/value-test.js
> +module('Unit | Mixin | value');
c'est quoi ce mixin ?

2017-03-13 16:24 UTC, bdavidxyz commented on live/tests/acceptance/j1-compare-answer-solution-qcm-test.js
>  import { expect } from 'chai';
Ce test devrait être entièrement supprimé, non ?

2017-03-13 16:25 UTC, bdavidxyz requested changes
voir commentaires

2017-03-14 09:55 UTC, yojecode commented on live/app/styles/components/qcm-solution-panel.scss
> +  color: #13c9a0;
Done

2017-03-14 09:55 UTC, yojecode commented on live/tests/acceptance/j1-compare-answer-solution-qcm-test.js
>  import { expect } from 'chai';
Non dans la mesure où ce test va couvrir une partie de la modale sauf le ce qui touche au QCM-solution

2017-03-14 09:55 UTC, yojecode commented on live/tests/acceptance/j2-compare-answer-solution-qroc-test.js
> +describe.skip('Acceptance | j2 - Comparer réponses et solutions pour un QROC | ', function () {
Exact!

2017-03-14 09:55 UTC, yojecode commented on live/tests/unit/utils/proposals-as-array-test.js
> +    { data: '', expected: [] },
Ok

2017-03-14 09:55 UTC, yojecode commented on tests/unit/mixins/value-test.js
> +test('it works', function(assert) {
bizarre, supprimé :)

2017-03-14 09:55 UTC, yojecode commented on tests/unit/mixins/value-test.js
> +module('Unit | Mixin | value');
No idea, magic mixin

2017-03-14 10:02 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 10:10 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 10:46 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 10:58 UTC, bdavidxyz commented on live/tests/unit/utils/lodash-custom-test.js
isNonEmptyString dans la description est la bonne version

2017-03-14 10:58 UTC, bdavidxyz commented on live/tests/unit/utils/lodash-custom-test.js
> +  describe('#isNotEmptyArray', function () {
isNonEmptyArray

2017-03-14 10:59 UTC, bdavidxyz requested changes
petite coquille, voir commentaires

2017-03-14 11:07 UTC, yojecode commented on live/tests/unit/utils/lodash-custom-test.js
done

2017-03-14 11:07 UTC, yojecode commented on live/tests/unit/utils/lodash-custom-test.js
> +  describe('#isNotEmptyArray', function () {
done

2017-03-14 11:13 UTC, bdavidxyz commented on live/tests/acceptance/c1-recapitulatif-test.js
> +  it('c1.8 Pour une réponse dont l\'utilisateur a bien répondu mais trop tard, le tableau récapitulatif donne' +
césure de ligne inutile

2017-03-14 11:13 UTC, bdavidxyz commented on live/tests/unit/models/answer/value-as-array-of-boolean-mixin-test.js
> +    { when: 'Resist to order empty space and empty value', input: ',4, 2 , 2,1,  ,', expected: [true, true, false, true] },
manque une virgule: resist to order, empty space and empty value

2017-03-14 11:14 UTC, bdavidxyz requested changes
voir commentaires

2017-03-14 11:15 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 13:51 UTC, yojecode commented on live/tests/acceptance/c1-recapitulatif-test.js
> +  it('c1.8 Pour une réponse dont l\'utilisateur a bien répondu mais trop tard, le tableau récapitulatif donne' +
:(

2017-03-14 13:52 UTC, yojecode commented on live/tests/unit/models/answer/value-as-array-of-boolean-mixin-test.js
> +    { when: 'Resist to order empty space and empty value', input: ',4, 2 , 2,1,  ,', expected: [true, true, false, true] },
ok

2017-03-14 13:55 UTC, bdavidxyz approved these changes

2017-03-14 13:59 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 16:22 UTC, MBrandone commented on live/app/components/comparison-window.js
>      return contentReference[this.get('answer.result')] || contentReference['default'];
C'est un peu lourd pour ce return et un peu confus à première vue, à voir si on essaye de clarifier, même en prennant plus de lignes.

2017-03-14 16:22 UTC, MBrandone commented on live/app/components/qcm-solution-panel.js
> +
J'aime bien le principe de 'single return statement', ça peut rendre le code plus lisible parfois. Ici j'aurai fait 

```javascript
const solution = this.get('solution.value');
let solutionArray = []
if (_.isNonEmptyString(solution)) {
  solutionArray = valueAsArrayOfBoolean(solution);
}
return solutionArray;
```

Chaud pour savoir ce  que vous en pensez.

2017-03-14 16:22 UTC, MBrandone commented on live/app/components/qcm-solution-panel.js
> +
@jbuget @bdavidxyz

2017-03-14 16:22 UTC, MBrandone commented on live/app/utils/labeled-radios.js
> + */
Je suis pas super fan de commentaires et j'ai pas trouvé des tests pour labeledRadios. Ça sent mauvais.

2017-03-14 16:22 UTC, MBrandone commented on live/app/utils/proposals-as-array.js
> +
La fonction calculate a l'air un peu complexe et pas testée.

2017-03-14 16:22 UTC, MBrandone commented on live/tests/acceptance/c1-recapitulatif-test.js
Cool, quand j'ai mergé tout à l'heure je me demandais pourquoi on skippait ces tests, mais on va enlever les skip sur cette PR

2017-03-14 16:22 UTC, MBrandone commented on live/tests/acceptance/j1-compare-answer-solution-qcm-test.js
>  import { expect } from 'chai';
J'ai l'impression qu'on ne teste rien spécifiquement au qcm ici du coup. Peut-etre qu'il faudrait renommer le fichier alors, pour qu'on comprenne qu'il teste uniquement la presence des composants de la modale.

2017-03-14 16:22 UTC, MBrandone commented on live/tests/integration/components/qcm-solution-panel-test.js
> +
Les lignes 51 à 67 se répètent dans le fichier si je ne me trompe pas, il faudrait les sortir des it et les mettre juste en-dessous du describe.

2017-03-14 16:37 UTC, MBrandone commented on live/app/utils/proposals-as-array.js
> +
Une issue a été rajouté

2017-03-14 16:46 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 17:30 UTC, jbuget commented
I've deployed this PR to http://399-refactoring-qcm-comparion.pix.beta.gouv.fr. Please check it out

2017-03-14 17:32 UTC, merged

2017-03-14 17:32 UTC, florianEnoh commented on live/app/utils/labeled-radios.js
> + */
Fichier supprimé

2017-03-14 17:32 UTC, florianEnoh commented on live/app/utils/proposals-as-array.js
> +
Ok je te laisse créer la review :)

2017-03-14 17:32 UTC, florianEnoh commented on live/tests/integration/components/qcm-solution-panel-test.js
> +
Je regarde ce que je peux faire pour toi