[#] [CLEANUP] Refactoring de l'intégration de Airtable.
sgmap/pix pull request #344
Opened 2017-03-14 16:40 UTC by jbuget

2017-03-14 17:25 UTC, bdavidxyz commented on api/lib/application/courses/course-controller.js
>          const challengeIds = courses.reduce((a, b) => {
a, b : c'est le moment d'en profiter pour un petit refactoring

2017-03-15 10:05 UTC, bdavidxyz commented on api/lib/application/courses/course-controller.js
> +    _fetchCourses(request.query)
Pas très robuste, si jamais il n'y a pas de request.query

2017-03-15 10:05 UTC, bdavidxyz commented on api/lib/infrastructure/airtable.js
> +   */
Super la JSDoc. On tend vers la généralisation ?

2017-03-15 10:07 UTC, bdavidxyz commented on api/tests/unit/application/courses/course-controller_test.js
>        sinon.stub(CourseSerializer, 'serializeArray', _ => courses);
Pas trop fan de l'utilisation du caractère "underscore" alors qu'on a lodash. On peut utiliser () ?

2017-03-15 10:08 UTC, bdavidxyz commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
> +function _buildChallenge(id, instruction, proposals) {
Pas assez de valeur. Il suffit dans ce cas là de mettre directement { id, instruction, proposals } dans l'appelant au lieu de faire appel à la fonction

2017-03-15 10:15 UTC, bdavidxyz commented on api/tests/unit/infrastructure/repositories/course-repository_test.js
> +  return { id, name, description };
idem que ci-dessus, la fonction n'a pas assez de valeur

2017-03-15 10:18 UTC, bdavidxyz commented on api/tests/unit/infrastructure/repositories/solution-repository_test.js
>        // given
On devrait mettre dans le wiki le given/when/then comme obligatoire, ça fait bizarre de voir des tests avec et des tests sans.

2017-03-15 10:18 UTC, bdavidxyz commented on api/tests/unit/infrastructure/serializers/airtable/challenge-serializer_test.js
> +    it('should revert attachments order because airtable return data in wrong order', function() {
Pas trop d'accord, on devrait dire Airtable et airtable. Mais bon, c'est pas trop important;)

2017-03-15 10:18 UTC, bdavidxyz requested changes
quelques coquilles / questions

2017-03-15 10:22 UTC, jbuget commented on api/tests/unit/infrastructure/serializers/airtable/challenge-serializer_test.js
> +    it('should revert attachments order because airtable return data in wrong order', function() {
un gros remplacer fait à la hâte

2017-03-15 10:23 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/solution-repository_test.js
>        // given
quand il y a 1 seule ligne, ça me faiot bizarre. mais pourquoi pas

2017-03-15 10:29 UTC, MBrandone commented on api/lib/infrastructure/airtable.js
> +  /**
Petite question, pourquoi on définit les variables comme ça dans ce fichier ?

2017-03-15 10:29 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/course-repository_test.js
> +  return { id, name, description };
elle permet d'éviter d'avoir à faire à chaque fois : 
{
  id: courseId,
  name: 'course name',
  description: 'course description'
}

on s'économise des lignes et le fait de devoir déclarer les propriétés à chaque fois.
ça raccourci, simplifie, homogénise le code dans les cas de tests.
si ça choque, je retire.

2017-03-15 10:30 UTC, bdavidxyz commented on api/tests/unit/infrastructure/repositories/course-repository_test.js
> +  return { id, name, description };
ok, on peut laisser

2017-03-15 10:31 UTC, bdavidxyz commented on api/tests/unit/infrastructure/serializers/airtable/challenge-serializer_test.js
> +    it('should revert attachments order because airtable return data in wrong order', function() {
comme quoi, Sublime Text...

2017-03-15 10:31 UTC, jbuget commented on api/tests/unit/application/courses/course-controller_test.js
>        sinon.stub(CourseSerializer, 'serializeArray', _ => courses);
j'ai pas touché cette ligne.
c'est vrai que ça peut être risqué avec Lodash.
dommage, car c'est une convention ES6 :-/
je remplace par des "()"

2017-03-15 10:32 UTC, jbuget commented on api/lib/infrastructure/airtable.js
> +   */
pas certain, là c'est un cas très particulier car le machin a plein de paramètres et peut être compliqué à utiliser

2017-03-15 10:32 UTC, jbuget commented on api/lib/application/courses/course-controller.js
> +    _fetchCourses(request.query)
justement, si y a pas de request.query, c'est comme si on faisait un `select all`. je m'appuie sur Airtable.

2017-03-15 11:25 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
C'est du rien du tout, mais je pense qu'on met jamais de parenthèse pour la description de la fonction qu'on test

2017-03-15 11:26 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
On a gardé un return avec eventually et pas de done() ici, c'est normal ?

2017-03-15 11:28 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
petit return qui traine et pas de done

2017-03-15 11:29 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
same as before

2017-03-15 11:33 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/course-repository_test.js
return avec avec eventually et pas de done

2017-03-15 13:17 UTC, jbuget commented on api/tests/unit/infrastructure/serializers/airtable/challenge-serializer_test.js
> +    it('should revert attachments order because airtable return data in wrong order', function() {
:trollface:

2017-03-15 13:29 UTC, jbuget commented
I've deployed this PR to http://cleanup-airtable-integration.pix.beta.gouv.fr. Please check it out

2017-03-15 13:40 UTC, bdavidxyz approved these changes

2017-03-15 13:43 UTC, merged