[#][FEATURE] sauvegarder le temps écoulé pour chaque épreuve
sgmap/pix pull request #357
Opened 2017-03-30 13:45 UTC by yojecode

2017-03-31 18:11 UTC, jbuget commented
I've deployed this PR to http://361-save-elapsed-time.pix.beta.gouv.fr. Please check it out

2017-04-01 09:05 UTC, jbuget commented
I've deployed this PR to http://361-save-elapsed-time.pix.beta.gouv.fr. Please check it out

2017-04-05 15:19 UTC, jbuget requested changes

2017-04-05 15:19 UTC, jbuget commented on live/app/components/challenge-item-generic.js
> +    Ember.Logger.info(this.get('_elapsedTime'), 'toto');
je pense qu'on peut retirer ce log

2017-04-05 15:19 UTC, jbuget commented on live/app/components/challenge-item-generic.js
> +    return false;
je ne comprends pas pourquoi on renvoie toujours `false`. je ne comprends pas l'intérêt de cette ComputedProperty.

2017-04-05 15:19 UTC, jbuget commented on live/app/components/challenge-item-generic.js
> +  _start: function () {
remplacer le mode `toto: function() {}` par `toto() {}` pour être cohérent avec ce qui est fait avant / après  ?

2017-04-05 15:19 UTC, jbuget commented on live/app/routes/assessments/get-challenge.js
> +  _createAnswer(answerValue, answerTimeout, currentChallenge, assessment, answerElapsedTime) {
j'ai cru que cette méthode était une action, je pense qu'on peut la rapprocher des autres méthodes privées ci-dessus, non ?

2017-04-05 15:19 UTC, jbuget commented on live/app/components/challenge-item-generic.js
> +    if (ENV.environment !== 'test') {
y a pas moyen de faire mieux que `if (ENV === 'test')` ? ex : définir une propriété `challengeTimerEnable` dans `environment.js` qu'on surcharge uniquement pour l'environnement de test. Ainsi, on verrait apparaître plutôt un truc propre du style : 

```javascript
if (ENV.challengeTimerEnabled) {
  // treatment
}
```

2017-04-06 08:34 UTC, yojecode commented on live/app/components/challenge-item-generic.js
> +    Ember.Logger.info(this.get('_elapsedTime'), 'toto');
done

2017-04-06 08:35 UTC, yojecode commented on live/app/components/challenge-item-generic.js
> +    return false;
Je l'utilise pas en fait, c'est un oubli

2017-04-06 08:35 UTC, yojecode commented on live/app/components/challenge-item-generic.js
> +  _start: function () {
Ok pour le principe

2017-04-06 08:41 UTC, yojecode commented on live/app/components/challenge-item-generic.js
> +    if (ENV.environment !== 'test') {
Good sharp eye

2017-04-06 08:42 UTC, yojecode commented on live/app/routes/assessments/get-challenge.js
> +  _createAnswer(answerValue, answerTimeout, currentChallenge, assessment, answerElapsedTime) {
OK

2017-04-06 08:56 UTC, jbuget commented
I've deployed this PR to http://361-save-elapsed-time.pix.beta.gouv.fr. Please check it out

2017-04-06 10:16 UTC, jbuget approved these changes

2017-04-06 10:18 UTC, merged