[#][FEATURE] Recaptcha when user subscription back (US-422)
sgmap/pix pull request #432
Opened 2017-05-29 16:54 UTC by Hypernikao

2017-05-29 17:11 UTC, jbuget commented
I've deployed this PR to http://recaptcha-when-user-subscription-back.pix.beta.gouv.fr. Please check it out

2017-05-29 19:44 UTC, jbuget commented
I've deployed this PR to http://recaptcha-when-user-subscription-back.pix.beta.gouv.fr. Please check it out

2017-05-29 21:51 UTC, jbuget reviewed
Attention aux espaces. Je pense que tu n'as pas ou mal configuré ton .editor-config / IDEA.

2017-05-29 21:51 UTC, jbuget commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +const INVALID_RECAPTCHA_TOKEN = 'INVALID_RECAPTCHA';
je remplacerai la string par `const INVALID_RECAPTCHA_TOKEN = 'invalid-or-unknown-recaptcha'` pour donner plus de sens encore

2017-05-29 21:51 UTC, jbuget commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +const RECAPTCHA_TOKEN = '03AOPBWq981qDlqqeuJvRRPOdV_jUsJKV7K9y8EdroTMzC50kWInTzGqEdKAhaSRozRS2Z84XzrpmcGmmF1qxC06lGPxbBfYOon_dVIie98Dr-sclrLJ69D6C3E5r9DLxNvKZjSF9cEmp7HdJzHR1Bw5-fqoqAw-9daY05zEU7abA6
pas la peine de mettre tout un vrai token ; un truc du genre : `const VALID_RECAPTCHA_TOKEN = 'a-valid-recaptch-token-should-be-a-string-of-512-numalpha-characters'` me paraîtrait plus parlant pour se faire une idée de l'algo.

2017-05-29 21:51 UTC, jbuget commented on api/package.json
> +    "request-promise": "^4.2.1",
est-ce qu'il y en a toujours besoin?

2017-05-29 21:51 UTC, jbuget commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +            'error-codes': []
Google renvoie vraiment tableau vide ? ou pas de champs ? ou null ?

2017-05-29 21:52 UTC, jbuget commented
Attention aussi au titre de la PR qui ne va pas (manque un espace entre les 2 tags, est écrit en anglais et ne contient pas le numéro de l'US à la fin.

2017-05-30 09:32 UTC, Hypernikao commented
Ok pour les remarques sur le nommage de la PR, je n'avais pas terminé en fait.
Cependant l'US-ID est déjà présent bizarre que tu ne l'ai pas vu

2017-05-30 09:32 UTC, Hypernikao commented on api/package.json
> +    "request-promise": "^4.2.1",
Oui en effet

2017-05-30 09:32 UTC, Hypernikao commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +const INVALID_RECAPTCHA_TOKEN = 'INVALID_RECAPTCHA';
Ok

2017-05-30 09:32 UTC, Hypernikao commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +const RECAPTCHA_TOKEN = '03AOPBWq981qDlqqeuJvRRPOdV_jUsJKV7K9y8EdroTMzC50kWInTzGqEdKAhaSRozRS2Z84XzrpmcGmmF1qxC06lGPxbBfYOon_dVIie98Dr-sclrLJ69D6C3E5r9DLxNvKZjSF9cEmp7HdJzHR1Bw5-fqoqAw-9daY05zEU7abA6
Done

2017-05-30 09:32 UTC, Hypernikao commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
> +            'error-codes': []
il ne renvoie tout simplement pas cette clé 'error-codes'

2017-05-30 09:43 UTC, jbuget commented
I've deployed this PR to http://recaptcha-when-user-subscription-back.pix.beta.gouv.fr. Please check it out

2017-05-31 08:24 UTC, jbuget commented
I've deployed this PR to http://recaptcha-when-user-subscription-back.pix.beta.gouv.fr. Please check it out

2017-05-31 14:58 UTC, jbuget commented
I've deployed this PR to http://recaptcha-when-user-subscription-back.pix.beta.gouv.fr. Please check it out

2017-05-31 21:23 UTC, jbuget requested changes
Je bloque pour le test vide. A part ça, well done :-)

2017-05-31 21:23 UTC, jbuget commented on api/tests/acceptance/application/users-controller-save_test.js
> +    it(`should return 422 HTTP status code, when captcha is `, function() {
je pense que ce test soit vide...

2017-05-31 21:23 UTC, jbuget commented on api/lib/infrastructure/validators/grecaptcha-validator.js
> +          const recaptchaError = new error.InvalidRecaptchaTokenError('Invalid reCaptcha token');
juste pour info, on écrit "[reCAPTCHA](https://www.google.com/recaptcha/intro/invisible.html)" ;-)

2017-05-31 21:23 UTC, jbuget commented on api/tests/unit/application/users/user-controller_test.js
> +          codeMethodSpy = sinon.spy(codeMethod);
je ne suis pas certain qu'on soit obligé de déclarer `codeMethod`. je pense que `codeMethodSpy = sinon.spy()` suffit. à moins que j'ai raté quelque chose.

2017-05-31 21:23 UTC, jbuget commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
>        it('should return a rejected promise when user response token is invalid', function() {
je renommerai en "should log an error and return a rejected promise when user response token is invalid". peut-être aussi séparer le test en 2 : le rejet en erreur et le log. à toi de voir.

2017-06-01 08:13 UTC, Hypernikao commented on api/tests/acceptance/application/users-controller-save_test.js
> +    it(`should return 422 HTTP status code, when captcha is `, function() {
En fait ce test avait été supprimé, je sais pas comment tu l'as retrouvé.
⭕️

2017-06-01 08:25 UTC, Hypernikao commented on api/tests/unit/application/users/user-controller_test.js
> +          codeMethodSpy = sinon.spy(codeMethod);
Done !

2017-06-01 08:26 UTC, Hypernikao commented on api/tests/unit/infrastructure/validators/grecaptcha-validator_test.js
>        it('should return a rejected promise when user response token is invalid', function() {
Ok pour le renommage

2017-06-01 08:27 UTC, Hypernikao commented on api/lib/infrastructure/validators/grecaptcha-validator.js
> +          const recaptchaError = new error.InvalidRecaptchaTokenError('Invalid reCaptcha token');
oui

2017-06-01 08:30 UTC, Hypernikao commented
Les modifications ont été faites. je te laisse LGTY

2017-06-01 12:39 UTC, jbuget approved these changes

2017-06-06 13:09 UTC, closed without merging