[#447] [BUG] Les boutons radio des QCM ne s'affichent plus sous IE11 (US-561).
sgmap/pix pull request #447
Opened 2017-06-21 13:09 UTC by Akhilian

2017-06-21 13:43 UTC, jbuget commented
I've deployed this PR to http://561-fix-radio-list-on-ie11.pix.beta.gouv.fr. Please check it out

2017-06-22 14:44 UTC, jbuget requested changes
LGTM

2017-06-22 14:44 UTC, jbuget approved these changes

2017-06-26 11:58 UTC, merged

2017-06-29 15:02 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [JV voir les puces des listes à puces (réponses QCU + choix des fichiers à télécharger) sous Edge/Explorer](https://trello.com/c/7cW0VJMa/561-jv-voir-les-puces-des-listes-%C3%A0-puces-r%C3%A9ponses-qcu-choix-des-fichiers-%C3%A0-t%C3%A9l%C3%A9charger-sous-edge-explorer)