[][] En tant qu'utilisateur loggué, je veux voir la liste des compétences
sgmap/pix pull request #451
Opened 2017-06-29 09:41 UTC by Hypernikao

2017-07-03 08:28 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-03 08:37 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-03 14:22 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-03 15:48 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-06 08:20 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Utilisateur logué, JV voir mon profil vide (1ere fois, en cours)](https://trello.com/c/7TMq6CrH/562-etq-utilisateur-logu%C3%A9-jv-voir-mon-profil-vide-1ere-fois-en-cours)

2017-07-06 08:35 UTC, Akhilian commented
Remarque générale: Pensez à utiliser un `rebase` plutôt qu'un merge lorsque vous avez des modifications de dev que vous voulez ré-utiliser. Ça évitera qu'on review du code déjà revue :p

2017-07-06 09:24 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-06 10:17 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-06 10:21 UTC, Akhilian commented on api/lib/application/users/user-controller.js
> +function _handleWhenInvalidAuthorization(errorMessage) {
Les fonctions privées ne sont pas groupées (il y en a au dessus et en dessous).
On les regroupe ?

2017-07-06 10:21 UTC, Akhilian commented on live/app/utils/result-icon-url.js
> +    return null;
Aucun test ne devient rouge si jamais on modifie le `return null;`

2017-07-06 10:21 UTC, Akhilian commented on live/app/components/competence-area-list.js
> +  _competencesByArea: groupBy('_sanitizedCompetences', 'areaName'),
Ce serait mieux de faire un groupBy basé sur l'idée. Comme le name est une chaine de caractères, c'est moyen (espaces, symboles, etc ...).

2017-07-06 10:21 UTC, Akhilian commented on live/app/models/user.js
> +  competenceAreas: Ember.computed('competences', async function() {
On propose `competenceByAreas`

2017-07-06 10:21 UTC, Akhilian commented on live/app/models/user.js
> +  competenceAreas: Ember.computed('competences', async function() {
Aïe, pas de tests :/
Unitaire si possible, intégration sinon.

2017-07-06 10:21 UTC, Akhilian commented on live/app/routes/compte.js
> +    return store.queryRecord('user', {});
Ce truc est testé seulement via l'acceptance.
A voir si un test unitaire a de la valeur (pas sûr).

2017-07-06 10:21 UTC, Akhilian commented on live/app/styles/components/_competence-area-item.scss
> +  @include device-is('mobile') {
Hum, c'est pas mobile first ça.
Est-ce que ça vaudrait le coup d'en faire un standard ?

2017-07-06 10:21 UTC, Akhilian commented on live/app/components/competence-area-item.js
> +export default Ember.Component.extend({
On pourrait le renommer en `area-item` directement ou si on veux garder l'idée qu'il y a des compétences dans l'area, alors un truc du genre `competence-by-area-item` ou `area-with-area-item`

2017-07-06 10:21 UTC, Akhilian commented on live/app/templates/components/competence-area-list.hbs
> +    {{competence-area-item competenceArea=competenceArea}}
A renommer comme signaler plus haut.

2017-07-06 10:21 UTC, Akhilian commented on live/app/templates/profile.hbs
> +      coucou
On vire le coucou qui traine ?
Style inline :p

ON TEF SE FICHIÉ :D

2017-07-06 10:21 UTC, Akhilian commented on live/mirage/factories/user.js
> +    return faker.random.uiid();
A priori, c'est uuid() => https://github.com/marak/Faker.js/

#BROEyeOfTheTiger

2017-07-06 10:21 UTC, Akhilian commented on live/mirage/scenarios/default.js
> +   */
On peux enlever le commentaire par défaut ;)

2017-07-06 10:21 UTC, Akhilian commented on live/tests/integration/components/profile-panel-test.js
> +    it('should render a competency profile block', function() {
D'habitude, on parle plutôt de `competence` plutôt que `competency`

2017-07-06 10:21 UTC, Akhilian commented on live/tests/test-helper.js
> +  //   Is any code triggering an artifical delay in tests – like `setTimeout` or `Ember.run.later`?
On dirait c'est un drop de tes pensées @kemenaran ? ^^
On peut virer ?

2017-07-07 15:54 UTC, Hypernikao commented on live/app/styles/components/_competence-area-item.scss
> +  @include device-is('mobile') {
Yes on peut en discuter

2017-07-07 16:55 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-07 17:31 UTC, jbuget commented on live/mirage/scenarios/default.js
> +   */
maintenant que vous l'avez lu, oui ^^

2017-07-07 17:31 UTC, jbuget commented on live/app/components/competence-area-item.js
> +export default Ember.Component.extend({
je plussoie `area-item`

2017-07-10 08:17 UTC, Hypernikao commented on live/mirage/scenarios/default.js
> +   */
Oui c'est du commentaire généré

2017-07-10 08:48 UTC, Hypernikao commented on live/app/components/competence-area-item.js
> +export default Ember.Component.extend({
hum je penche pour quelque chose de plus explicite : competence-by-area-item

2017-07-10 09:33 UTC, Hypernikao commented on live/app/routes/compte.js
> +    return store.queryRecord('user', {});
Je pense que pour l'instant l'acceptance fait le taf, je viens de me timeboxer pour faire un test unitaire dessus mais il y a  peu de valeur.

2017-07-10 09:43 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-10 13:33 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-11 17:50 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-12 16:03 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-12 17:39 UTC, jbuget requested changes

2017-07-12 17:39 UTC, jbuget commented on live/app/components/competence-by-area-item.js
> +    const sortedList = _.sortBy(competencesList, [function(o) {
l'usage de lodash m'embête un peu, sachant qu'[il y a tout ce qu'il faut dans ES6](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/sort). 

Par ailleurs, je privilégierais une _fat arrow_ avec une variable bien nommée (ça sent le copier-coller vite fait).

2017-07-13 13:57 UTC, jbuget commented
I've deployed this PR to http://562-front-competences-logged-user.pix.beta.gouv.fr. Please check it out

2017-07-17 08:18 UTC, merged