[#457] [FEATURE] Ajout du score et du niveau par compétences sur le profil utilisateur côté API (US-574).
sgmap/pix pull request #457
Opened 2017-07-05 08:27 UTC by MBrandone

2017-07-05 09:12 UTC, MBrandone commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ consommateur de l'API /users, je veux pouvoir consulter mon niveau par compétence](https://trello.com/c/WvgDSahq/574-etq-consommateur-de-lapi-users-je-veux-pouvoir-consulter-mon-niveau-par-comp%C3%A9tence)

2017-07-05 09:18 UTC, jbuget commented
I've deployed this PR to http://574-get-level-by-skill.pix.beta.gouv.fr. Please check it out

2017-07-05 10:18 UTC, jbuget commented
I've deployed this PR to http://574-get-level-by-skill.pix.beta.gouv.fr. Please check it out

2017-07-05 11:59 UTC, jbuget requested changes
Je mets en "changes required" par rapport aux champs en camelCase plutôt que kebab-style. A part ça, des petites pétouilles. Great job :-)

2017-07-05 11:59 UTC, jbuget commented on api/lib/infrastructure/serializers/jsonapi/profile-serializer.js
> +        competenceData.attributes['pixScore'] = competence.pixScore;
je pense qu'il faut remplacer `pixScore` par `pix-score `

2017-07-05 11:59 UTC, jbuget commented on api/tests/acceptance/application/assessment-controller-post_test.js
> +              'user-name': 'Jon Snow',
c'est toujours d'actualité ces attributs ?

2017-07-05 11:59 UTC, jbuget commented on api/tests/acceptance/application/assessment-controller-post_test.js
> +              'user-name': 'Jon Snow',
encore d'actualité ?

2017-07-05 11:59 UTC, jbuget commented on api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
> +      getScoredAssessmentStub.restore();
proposition : à partir de 5 stubs, utiliser la [feature sandbox de sinon](http://sinonjs.org/releases/v1.17.7/sandbox/)

2017-07-05 11:59 UTC, jbuget commented on api/tests/unit/application/assessments/assessment-controller-save_test.js
> +      assessmentDeserializeStub.restore();
moins de `restore()` que de `stub()`=> risque d'effets de bords

2017-07-05 11:59 UTC, jbuget commented on api/tests/unit/domain/services/profile-service_test.js
> +        getAdaptiveCourseStub.restore();
même proposition que ci-dessus : utiliser [sinon.sandbox](http://sinonjs.org/releases/v1.17.7/sandbox/)

2017-07-05 13:30 UTC, jbuget commented
I've deployed this PR to http://574-get-level-by-skill.pix.beta.gouv.fr. Please check it out

2017-07-06 08:50 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ consommateur de l'API /users, je veux pouvoir consulter mon niveau par compétence](https://trello.com/c/WvgDSahq/574-etq-consommateur-de-lapi-users-je-veux-pouvoir-consulter-mon-niveau-par-comp%C3%A9tence)

2017-07-06 09:06 UTC, jbuget approved these changes

2017-07-06 09:16 UTC, jbuget commented
I've deployed this PR to http://574-get-level-by-skill.pix.beta.gouv.fr. Please check it out

2017-07-07 08:15 UTC, merged