[#] [FEATURE] Redirection automatiquement à la connexion vers /board ou /compte en fonction du type de compte (US-590)
sgmap/pix pull request #485
Opened 2017-08-11 09:25 UTC by Hypernikao

2017-08-11 09:33 UTC, Hypernikao commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Prescripteur, JV pouvoir accéder à l'espace dédié de mon organisation.](https://trello.com/c/Dm9toHNQ/590-etq-prescripteur-jv-pouvoir-acc%C3%A9der-%C3%A0-lespace-d%C3%A9di%C3%A9-de-mon-organisation)

2017-08-11 09:36 UTC, jbuget commented
I've deployed this PR to http://590-automatic-redirect-to-board-when-organization.pix.beta.gouv.fr. Please check it out

2017-08-11 16:15 UTC, jbuget commented
I've deployed this PR to http://590-automatic-redirect-to-board-when-organization.pix.beta.gouv.fr. Please check it out

2017-08-14 13:49 UTC, Akhilian requested changes

2017-08-14 13:49 UTC, Akhilian commented on api/lib/infrastructure/repositories/organization-repository.js
> +        return (organizations) ? organizations.models : [];
Il manque un test pour la valeur par défaut :/
Le test "should return an empty Array, when organization id is not found" ne passe pas rouge lorsque l'on change ça.

2017-08-14 13:49 UTC, Akhilian commented on api/tests/unit/infrastructure/repositories/organization-repository_test.js
> +            expect(organization).to.deep.equal([]);
N'oubliez pas de faire passer le test rouge ;)

2017-08-14 13:49 UTC, Akhilian commented on live/app/routes/login.js
> +function isUserLinkedToOrganization(user) {
_isUserLinkedToOrganization() pour marquer une méthode privée ?
Eventuellement déplacer la fonction en bas, vu qu'on a envie de la lire que lorsqu'on en a besoin, pas forcément à chaque ouverture du fichier.

2017-08-14 13:49 UTC, Akhilian commented on live/tests/unit/authenticators/simple-test.js
> +        'has-organization': false,
Le 'has-organization' n'existe pas sur l'endpoint, on peut l'enlever ici :)

2017-08-14 13:49 UTC, Akhilian commented on live/app/routes/login.js
> +          this.transitionTo(this.routeIfNotAuthenticated);
J'ai l'impression que le `.catch()` ici ne sert à rien.
On a déjà un `.catch()` dans le signin-form qui se charge de gérer l'erreur de connexion en affichant un message d'erreur.

2017-08-14 13:49 UTC, Akhilian commented on live/tests/unit/routes/login-test.js
> +  describe('Behavior when error occured', function() {
A priori, cette partie des tests est superflue. On test déjà dans le signin-form (même message qu'avant).

2017-08-17 13:54 UTC, florianEnoh commented on api/lib/infrastructure/repositories/organization-repository.js
> +        return (organizations) ? organizations.models : [];
Oui c'est bon

2017-08-17 13:54 UTC, florianEnoh commented on api/tests/unit/infrastructure/repositories/organization-repository_test.js
> +            expect(organization).to.deep.equal([]);
En fait le FetchAll, retourne un tableau vide lorsqu'il ne trouve rien. C'est pratique dans ce cas d'espèce

2017-08-17 13:54 UTC, florianEnoh commented on live/app/routes/login.js
> +function isUserLinkedToOrganization(user) {
Ok

2017-08-17 13:54 UTC, Hypernikao commented on live/app/routes/login.js
> +          this.transitionTo(this.routeIfNotAuthenticated);
Exact

2017-08-17 13:54 UTC, Hypernikao commented on live/tests/unit/authenticators/simple-test.js
> +        'has-organization': false,
En effet !

2017-08-17 13:54 UTC, Hypernikao commented on live/tests/unit/routes/login-test.js
> +  describe('Behavior when error occured', function() {
Supprimé

2017-08-17 14:04 UTC, jbuget commented
I've deployed this PR to http://590-automatic-redirect-to-board-when-organization.pix.beta.gouv.fr. Please check it out

2017-08-17 14:10 UTC, Akhilian approved these changes

2017-08-17 14:11 UTC, merged