[#] [FEATURE] création d'un instantané du profil de compétence (Api) (US-641)
sgmap/pix pull request #489
Opened 2017-08-21 16:46 UTC by Hypernikao

2017-08-22 16:25 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-22 20:09 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-23 11:05 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-23 15:14 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-23 23:16 UTC, jbuget requested changes
Très bon boulot. Une question sur un code retour d'erreur (400 VS 422). Quelques propositions de changements mineurs qui utilisent le sucre syntaxique offert par ES6, notamment sur les promesses.

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +  create: function(request, reply) {
privilégier la forme : 

```javascript
create(request, reply) => {
  // ...
}
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +    if(!_hasAnAtuhorizationHeaders(request)) {
Il manque des espaces. Fixer ton linter / formatter Visual Code ou IntelliJ IDEA

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +        return UserRepository.findUserById(userId);
Dans la mesure où la méthode est hyper longue et on qu'on appelle une méthode static publique, privilégier la forme contractée : 

```javascript
.then(UserRepository.findUserById)
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((foundUser) => {
Privilégier la forme contractée / déstructurée : 

```javascript
.then(({id}) => profileService.getByUserId(id))
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((profile) => {
Privilégier la forme contractée : 

```javascript
then(profileSerializer.serialize)
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((serializedProfile) => {
Je propose de factoriser les 5 lignes suivantes en : 

```javascript
then(profile => SnapshotService.create({organizationId, profile}))
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +const _replyErrorWithMessage = function(reply, errorMessage, statusCode) {
Il est de bon aloi de déclarer les méthodes privées / utilitaires avant leur utilisation. Je suis étonné que le linter laisse passer ça.

2017-08-23 23:16 UTC, jbuget commented on api/lib/domain/services/snapshot-service.js
> +      .then((snapshot) => {
Privilégier la forme contractée : 

```javascript
then(snapshot => snapshot.get('id'))
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/domain/services/snapshot-service.js
> +      .catch((err) => {
En l'état ce catch ne sert à rien.

2017-08-23 23:16 UTC, jbuget commented on api/lib/infrastructure/repositories/organization-repository.js
> +      .then(organizations => {
La forme contractée donnerait : 

```javascript
.then(organizations => !!organizations)
```

2017-08-23 23:16 UTC, jbuget commented on api/lib/infrastructure/repositories/snapshot-repository.js
> +      .save();
Je suis d'avis de mettre le `.save` sur la même ligne.

2017-08-23 23:16 UTC, jbuget commented on api/tests/acceptance/application/snapshot-controller_test.js
> +      .then(() => {
Je pense qu'on peut diviser par 2 la taille du `before()` tout en améliorant / simplifiant la lecture du code.

2017-08-23 23:16 UTC, jbuget commented on api/tests/acceptance/application/snapshot-controller_test.js
> +          expect(response.statusCode).to.equal(400);
Si c'est un problème sur la validité des données, alors ce n'est pas une `400` mais une `422`.

cf. https://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm

2017-08-23 23:16 UTC, jbuget commented on api/lib/application/snapshots/snapshot-controller.js
> +  }
Je trouve la méthode trop longue. La preuve objective, je n'arrive pas à l'afficher d'un coup sur mon écran (sans dézoomer). A voir si mes propositions de contraction la rende plus digeste. Sinon la découper en sous-traitement, en particulier la gestion des erreurs.

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +  create: function(request, reply) {
done :)

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +    if(!_hasAnAtuhorizationHeaders(request)) {
C'est bizarre car j'exécute le lint avant de pusher. et d'ailleurs le build est censé échoué si problème de lint nan ?

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +        return UserRepository.findUserById(userId);
en effet

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((profile) => {
On regarde cela, j'ai des doutes

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((serializedProfile) => {
Shame

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/infrastructure/repositories/snapshot-repository.js
> +      .save();
Oui en effet, j'avais du chaînage d'instruction que j'ai viré et je ne l'ai pas remonté

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/infrastructure/repositories/organization-repository.js
> +      .then(organizations => {
!! C'est beau !!

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/domain/services/snapshot-service.js
> +      .catch((err) => {
Ok

2017-08-24 10:15 UTC, florianEnoh commented on api/lib/application/snapshots/snapshot-controller.js
> +      .then((foundUser) => {
Ok

2017-08-24 10:15 UTC, Hypernikao commented on api/lib/application/snapshots/snapshot-controller.js
> +  }
Done

2017-08-24 10:15 UTC, Hypernikao commented on api/lib/application/snapshots/snapshot-controller.js
> +const _replyErrorWithMessage = function(reply, errorMessage, statusCode) {
⭕️

2017-08-24 10:15 UTC, Hypernikao commented on api/tests/acceptance/application/snapshot-controller_test.js
> +      .then(() => {
En pending pour l'instant

2017-08-24 10:29 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-24 10:32 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-24 11:36 UTC, jbuget approved these changes

2017-08-24 14:58 UTC, jbuget commented
I've deployed this PR to http://641-profile-snapshot-api.pix.beta.gouv.fr. Please check it out

2017-08-24 14:59 UTC, merged

2017-08-29 09:11 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Utilisateur de l'API, JV pouvoir créer un instantané de mon profil](https://trello.com/c/WLZmTjQ1/641-etq-utilisateur-de-lapi-jv-pouvoir-cr%C3%A9er-un-instantan%C3%A9-de-mon-profil)

2017-08-29 09:11 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Utilisateur de l'API, JV pouvoir créer un instantané de mon profil](https://trello.com/c/WLZmTjQ1/641-etq-utilisateur-de-lapi-jv-pouvoir-cr%C3%A9er-un-instantan%C3%A9-de-mon-profil)