[#491] ETQ utilisateur connecté, je veux être redirigé vers mon espace depuis la home (US-606).
sgmap/pix pull request #491
Opened 2017-08-23 16:10 UTC by Akhilian

2017-08-23 16:14 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Utilisateur loggué , JV ne plus devoir aller sur /compte pour accéder à mon compte, mais y accéder depuis pix.beta.gouv.fr](https://trello.com/c/6jImmISL/606-etq-utilisateur-loggu%C3%A9-jv-ne-plus-devoir-aller-sur-compte-pour-acc%C3%A9der-%C3%A0-mon-compte-mais-y-acc%C3%A9der-depuis-pixbetagouvfr)

2017-08-24 11:31 UTC, jbuget commented
I've deployed this PR to http://606-autoredirect-from-home-to-logged-home.pix.beta.gouv.fr. Please check it out

2017-08-24 15:04 UTC, jbuget commented
I've deployed this PR to http://606-autoredirect-from-home-to-logged-home.pix.beta.gouv.fr. Please check it out

2017-08-25 10:19 UTC, jbuget commented
I've deployed this PR to http://606-autoredirect-from-home-to-logged-home.pix.beta.gouv.fr. Please check it out

2017-08-28 13:18 UTC, jbuget requested changes
Des questions / suggestions et des micro-changes.

2017-08-28 13:18 UTC, jbuget commented on live/app/components/user-logged-menu.js
> +    this.get('store').findRecord('user', this.get('session.data.authenticated.userId'))
Je pense qu'on peut utiliser [le service fourni par Ember-Simple-Auth](https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md) pour nous faciliter la vie. 

Mais ça ne bloque pas la story.

2017-08-28 13:18 UTC, jbuget commented on live/app/routes/inscription.js
> +          return this.get('store').queryRecord('user', {});
Question : ce ne serait pas mieux sur une ligne ? N'en ferait-on pas un standard ?

2017-08-28 13:18 UTC, jbuget commented on live/tests/unit/components/user-logged-menu-test.js
> +        this.register('service:session', Ember.Service.extend({
Proposition : extraire cette méthode dans `test-helpers` pour mutualiser.

2017-08-28 13:18 UTC, jbuget commented on live/tests/unit/routes/board-test.js
> +      findRecord: findRecord
on peut simplifier la ligne en `{ findRecord }`, voire la remonter à la l.21

2017-08-28 13:18 UTC, jbuget commented on live/tests/unit/routes/board-test.js
> +    sinon.assert.calledWith(findRecord, 'user', 12);
est-ce que [l'assertion Sinon](http://sinonjs.org/releases/v3.2.1/assertions/) `calledWithExactly` n'aurait pas eu sa place ici ?

2017-08-28 13:18 UTC, jbuget commented on live/tests/unit/routes/compte-test.js
> +    let storyStub;
coquille : rename `storyStub` en `storeStub`

2017-08-28 19:49 UTC, jbuget commented on live/tests/unit/routes/compte-test.js
> +    let storyStub;
done in another story

2017-08-28 20:32 UTC, jbuget approved these changes

2017-08-28 20:33 UTC, jbuget commented
I've deployed this PR to http://606-autoredirect-from-home-to-logged-home.pix.beta.gouv.fr. Please check it out

2017-08-29 09:12 UTC, jbuget commented
I've deployed this PR to http://606-autoredirect-from-home-to-logged-home.pix.beta.gouv.fr. Please check it out

2017-08-29 09:13 UTC, merged