[#] [FEATURE] Nouvelle bannière d'accueil sur la page de profil d'un utilisateur connecté (US-193)
sgmap/pix pull request #518
Opened 2017-09-04 21:37 UTC by Hypernikao

2017-09-05 08:48 UTC, jbuget commented
I've deployed this PR to http://193-logged-user-panel.pix.beta.gouv.fr. Please check it out

2017-09-05 12:22 UTC, jbuget commented
I've deployed this PR to http://193-logged-user-panel.pix.beta.gouv.fr. Please check it out

2017-09-05 15:00 UTC, MBrandone commented on live/app/components/logged-user-profile-banner.js
> +      }, config.APP.FEEDBACK_PANEL_SCROLL_DURATION);
Du coup, on peut appeler cette variable autrement vu qu'elle n'est plus utiliser uniquement sur feedback panel

2017-09-05 15:00 UTC, MBrandone commented on live/app/styles/components/_user-logged-menu.scss
>  }
Raudrait rechecker l'accessibilité du coup, apparemment le z-index a quelques effets de bords

2017-09-07 13:49 UTC, jbuget commented
I've deployed this PR to http://193-logged-user-panel.pix.beta.gouv.fr. Please check it out

2017-09-07 14:06 UTC, jbuget commented
I've deployed this PR to http://193-logged-user-panel.pix.beta.gouv.fr. Please check it out

2017-09-11 09:10 UTC, jbuget commented
I've deployed this PR to http://193-logged-user-panel.pix.beta.gouv.fr. Please check it out

2017-09-12 08:19 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Utilisateur logué, JV le bandeau d'accueil](https://trello.com/c/KyvUVuiH/193-etq-utilisateur-logu%C3%A9-jv-le-bandeau-daccueil)

2017-09-13 17:47 UTC, jbuget requested changes
Rien de dramatique : 
- un commentaire à supprimer
- un préfixe `_` de méthode à discuter

2017-09-13 17:47 UTC, jbuget commented on live/app/components/logged-user-profile-banner.js
> +    _scrollToProfile() {
Je suis partagé sur le préfixe '_'. D'un côté, c'est une action passée au composant bouton ; de l'autre, le bouton est interne au composant. Je trancherais bien en prenant 5mn avec l'équipe avant ou après le daily.

2017-09-13 17:47 UTC, jbuget commented on live/app/styles/components/_navbar-header.scss
> +  // width: 90%;
Code mort

2017-09-14 08:50 UTC, Hypernikao commented on live/app/styles/components/_navbar-header.scss
> +  // width: 90%;
Done

2017-09-14 08:50 UTC, Hypernikao commented on live/app/components/logged-user-profile-banner.js
> +    _scrollToProfile() {
J'ai retiré le '_'

2017-09-14 13:27 UTC, jbuget approved these changes

2017-09-14 13:50 UTC, merged