[#532] [BUGFIX] Fixer le niveau maximal atteignable au cours d'une évaluation à 5 (US-783).
sgmap/pix pull request #533
Opened 2017-09-13 22:10 UTC by jbuget

2017-09-13 22:10 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [On ne devrait pas pouvoir atteindre le niveau 6](https://trello.com/c/SMlNLRLl/783-on-ne-devrait-pas-pouvoir-atteindre-le-niveau-6)

2017-09-14 15:51 UTC, Akhilian requested changes

2017-09-14 15:51 UTC, Akhilian commented on api/lib/cat/assessment.js
>      return Math.floor(this.pixScore / 8);
Proposition:
5 devient MAX_REACHABLE_LEVEL
8 devient NB_PIX_BY_LEVEL

Et plutôt qu'une condition qu'on ne comprendra plus dans quelques jours:
```js
const estimatedLevel = Math.floor(this.pixScore / NB_PIX_BY_LEVEL);
return (estimatedLevel >= MAX_REACHABLE_LEVEL) ? MAX_REACHABLE_LEVEL : estimatedLevel;
```

2017-09-14 17:31 UTC, jbuget commented on api/lib/cat/assessment.js
>      return Math.floor(this.pixScore / 8);
bien vu, j'y suis allé en mode test-first, mais j'ai oublié la partie refactoring du TDD. #meaCulpa

2017-09-15 08:17 UTC, Akhilian commented on api/lib/cat/assessment.js
>      return Math.floor(this.pixScore / 8);
Np np ;)

2017-09-15 18:05 UTC, jbuget commented
y a un soucis au niveau de l'affichage de GitHub du CircleCi. Il est indiqué comme pending, alors que sur CircleCI il est affiché comme success. 
@Akhilian tu peux valider que j'ai bien pris en compte tes changements stp ?

2017-09-21 08:48 UTC, Akhilian approved these changes

2017-09-21 09:37 UTC, merged