798 ask password reset api
sgmap/pix pull request #541
Opened 2017-09-18 14:46 UTC by MBrandone

2017-09-18 18:47 UTC, jbuget requested changes

2017-09-18 18:47 UTC, jbuget commented on api/lib/domain/errors.js
> +  constructor() {
y a vraiment intérêt à définir un constructeur qui se contente de faire `super` ?

2017-09-18 18:47 UTC, jbuget commented on api/lib/domain/errors.js
> +  userNotFoundError,
mettre les erreurs `internalError` et `userNotFound` en majuscule, comme pour les autres erreurs.

2017-09-18 18:47 UTC, jbuget commented on api/tests/unit/domain/errors_test.js
> +      done();
je pense qu'on n'est pas obligé de passer par `done` qui n'est utile que dans le cas où on veut vérifier des trucs en rapport avec des traitements asynchrones.

2017-09-22 13:43 UTC, Hypernikao commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ User de l'api, JV pouvoir demander la regénération de mon mot de passe et recevoir un mail](https://trello.com/c/NlkedC1r/798-etq-user-de-lapi-jv-pouvoir-demander-la-reg%C3%A9n%C3%A9ration-de-mon-mot-de-passe-et-recevoir-un-mail)

2017-09-25 17:51 UTC, jbuget approved these changes

2017-09-26 15:28 UTC, Akhilian commented on api/db/migrations/20170919181249_reset-password-demands.js
> +    t.string('email');
Il manque l'`index()` sur l'email, dans les cas où on recherchera par l'email.

2017-09-26 15:28 UTC, Akhilian commented on api/lib/application/passwords/password-controller.js
> +  resetDemand(request, reply) {
Je dirais plutôt demandReset parce que j'utiliserais plutôt un verbe d'action plutôt qu'une forme passive.

2017-09-26 15:28 UTC, Akhilian commented on api/lib/domain/services/mail-service.js
> +  const baseUrl = (hostEnv !== 'production') ? `${hostEnv}.` : '';
A valider, mais le header `host` qui devrait faire le taf.
```
headers: 
   { host: 'localhost:3000' }
```

2017-09-26 15:28 UTC, Akhilian commented on api/lib/domain/services/mail-service.js
> +  const baseUrl = (hostEnv !== 'production') ? `${hostEnv}.` : '';
L'avantage, c'est que ça remplace entièrement ${baseUrl}pix.beta.gouv.fr

2017-09-26 15:28 UTC, Akhilian commented on api/lib/domain/services/reset-password-service.js
> +  createDemand() {
On supprime ? :)

2017-09-26 15:28 UTC, Akhilian commented on api/tests/acceptance/application/password-controller_test.js
> +        server.inject(options).then((response) => {
InjectThen et return plutôt que `done()` ? :p
Pareil pour les lignes suivantes :)

2017-09-26 15:28 UTC, Akhilian commented on api/tests/acceptance/application/password-controller_test.js
> +describe('Acceptance | Controller | password-controller', function() {
Ça ressemble à des tests d'intégration pour moi (à cause des stubs).
Mais la limite est pas hyper claire chez nous.

2017-09-26 15:28 UTC, Akhilian commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +          expect(err.name).to.equal('CustomError');
Ça ne marche pas avec instanceOf ? :/

2017-10-02 10:21 UTC, Hypernikao commented on api/db/migrations/20170919181249_reset-password-demands.js
> +    t.string('email');
Done

2017-10-02 10:25 UTC, Hypernikao commented on api/lib/application/passwords/password-controller.js
> +  resetDemand(request, reply) {
On opte pour createResetDemand

2017-10-02 10:27 UTC, Hypernikao commented on api/lib/domain/services/mail-service.js
> +  const baseUrl = (hostEnv !== 'production') ? `${hostEnv}.` : '';
In progress

2017-10-02 10:28 UTC, Hypernikao commented on api/tests/acceptance/application/password-controller_test.js
> +describe('Acceptance | Controller | password-controller', function() {
Affirmatif

2017-10-02 10:30 UTC, Hypernikao commented on api/tests/acceptance/application/password-controller_test.js
> +        server.inject(options).then((response) => {
Done () !

2017-10-02 10:37 UTC, Hypernikao commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +          expect(err.name).to.equal('CustomError');
Ah bah si :) je voulais tenter aussi

2017-10-04 15:51 UTC, jbuget approved these changes

2017-10-04 16:01 UTC, merged