[#666] Add catchall route which redirect 404 to index page (US-818).
sgmap/pix pull request #549
Opened 2017-09-27 15:01 UTC by mackwic

2017-09-27 15:05 UTC, mackwic commented
First commit since a year 🕶

2017-09-28 07:25 UTC, jbuget requested changes
Le nom de la PR ne respecte pas les standards de l'équipe. cf.https://github.com/sgmap/pix/wiki/Conventions-de-nommage

C'est important pour faciliter la rédaction du CHANGELOG et pour montrer le sérieux de Pix dans l'Open Source

2017-09-28 07:25 UTC, jbuget commented on live/tests/acceptance/not-found-redirect-to-index-test.js
> +  it('unexistant page should redirect to home page', () => {
Un `it` commence toujours par "should".
Renommer en "should redirect to home page when entered URL does not exist"

2017-09-28 07:25 UTC, jbuget commented on api/package.json
> +    "sqlite3": "^3.1.12",
A savoir por la prochaine fois : on gère les montées de versions dans des PR de BSR dédiée, sauf si la montée de version de la lib est en rapport avec la story (ce qui ne semble pas être le cas ici).

2017-10-03 15:01 UTC, jbuget approved these changes

2017-10-03 15:01 UTC, merged