[#] [FEATURE] Creation de la page 'mot de passe oublié' (US-763)
sgmap/pix pull request #550
Opened 2017-09-28 15:38 UTC by MBrandone

2017-10-06 14:57 UTC, MBrandone commented
Hello, 

On a tenté le refacto "tout dans la route". On a réussi à le faire "marcher", mais un test d'acceptance ne passait plus (alors que fonctionnellement ça marchait). Puis après avoir demandé l'avis de l'équipe, on était pas chaud pour tout mettre dans la route. Du coup on va garder le composants.

2017-10-12 08:12 UTC, jbuget requested changes

2017-10-12 08:12 UTC, jbuget commented on live/app/templates/password-reset.hbs
> +    <a class="password-reset-page__inscription-button" href="/inscription">S'inscrire <span class="sr-only"> sur Pix</span> </a>
- mettre un `{{link-to}}`
- ajouter un "petit" TA qui vérifie qu'on a bien le lien

2017-10-12 08:12 UTC, jbuget commented on live/app/templates/components/password-reset-form.hbs
> +  <a href="/connexion" class="password-reset__connexion-link">Annuler
- mettre un `{{link-to}}`
- ajouter un TI

2017-10-12 10:25 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ User, JV pouvoir demander la regénération de mon mot de passe](https://trello.com/c/ZswG17om/763-etq-user-jv-pouvoir-demander-la-reg%C3%A9n%C3%A9ration-de-mon-mot-de-passe)

2017-10-13 08:31 UTC, jbuget approved these changes

2017-10-13 09:18 UTC, merged