[#560] [FEATURE] Validation d'une première éprevue QMAIL (US-856).
sgmap/pix pull request #560
Opened 2017-10-17 10:39 UTC by Akhilian

2017-10-24 09:03 UTC, jbuget requested changes

2017-10-24 09:03 UTC, jbuget commented on api/lib/application/qmail/qmail-controller.js
> +        return AnswerRepository.findByChallengeAndAssessment(challengeId, assessmentId);
Renommer `AnswerRepository.**find**ByChallengeAndAssessment` en `AnswerRepository.**get**ByChallengeAndAssessment`. 

Par convention dans les ORM, : 

- get => récupérer 1 Entité
- find => récupérer 1 Collection ou n Entités

2017-10-24 09:03 UTC, jbuget commented on api/lib/application/qmail/qmail-controller.js
> +        const answerDoesNotExists = (answer === null);
ça me paraît compliqué pour faire juste un `if (!answer)`.

2017-10-24 09:03 UTC, jbuget commented on api/lib/domain/errors.js
> +class NotElligibleToQMAILError extends Error {
renommer "NotElligibleTo**QMAIL**Error" en "NotElligibleTo**Qmail**Error" ; jamais d'exception dans le CamelCase pour ne plus jamais se prendre la tête, même avec les abbréviations, sigles, etc.

2017-10-24 09:03 UTC, jbuget commented on api/lib/domain/services/qmail-validation-service.js
> +    if(parsedRules === null) {
ça sert vraiment à quelque chose ? si oui, je préfère la notation standard `if (!parsedRules)`.

2017-10-24 09:03 UTC, jbuget commented on api/tests/acceptance/application/qmail-controller_test.js
> +        return knex('answers').insert([inserted_answer]);
pas obligé de passer par un tableau pour 1 valeur ~ http://knexjs.org/#Builder-insert

2017-10-24 09:03 UTC, jbuget commented on api/tests/unit/application/qmail/qmail-controller_test.js
> +      describe('when analysing the email', () => {
du coup ici c'est un `context` plutôt qu'un `describe` ?

2017-10-24 09:03 UTC, jbuget commented on api/tests/unit/domain/services/qmail-validation-service_test.js
> +          '      OU: \n' +
Remplacer le OU par un ET pour rendre le cas plus intéressant / pertinent

2017-10-24 09:03 UTC, jbuget commented on api/lib/domain/services/qmail-validation-service.js
> +function _validateRulesTwo(email, currentOperator, rules, field) {
Renommer en mieux

2017-10-24 09:03 UTC, jbuget commented on api/lib/domain/services/qmail-validation-service.js
> +    result = fieldUnderTest.search(value) >= 0;
Privilégier `.includes` plutôt que `.search`

2017-10-24 09:03 UTC, jbuget commented on live/app/services/mail-generator.js
> +    const fdqn = (environment !== 'development') ? 'pix-infra.ovh' : 'localhost';
renommer la variable en `fullyQualifiedDomainName`

2017-10-24 12:55 UTC, jbuget requested changes

2017-10-24 12:55 UTC, jbuget commented on live/app/components/challenge-item-qmail.js
> +  _hasError: function() {
on privilégie la forme 

```
_hasError() {
```

2017-10-24 12:55 UTC, jbuget commented on live/tests/unit/components/challenge-item-qmail-test.js
> +  describe('_hasError', function() {
quand il s'agit de méthode, on préfixe par "#" (VS. computed properties => "@")

2017-10-24 12:55 UTC, jbuget commented on live/app/components/challenge-item-qmail.js
> +  _hasError: function() {
au passage, pourquoi ne pas en faire une Computed Property ?

2017-10-24 12:55 UTC, jbuget commented on api/lib/application/qmail/qmail-controller.js
> +        if(answerDoesNotExists)
mettre des accolades autour du `if`

2017-10-24 14:34 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Producteur, je veux pouvoir rédiger des règles de validation d'email](https://trello.com/c/CFaRLENR/856-etq-producteur-je-veux-pouvoir-r%C3%A9diger-des-r%C3%A8gles-de-validation-demail)

2017-10-24 14:34 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Producteur, je veux pouvoir rédiger des règles de validation d'email](https://trello.com/c/CFaRLENR/856-etq-producteur-je-veux-pouvoir-r%C3%A9diger-des-r%C3%A8gles-de-validation-demail)

2017-10-25 08:50 UTC, jbuget approved these changes

2017-10-25 08:50 UTC, merged