[#] [FEATURE] Persistence des acquis validés, invalidés, et non proposés
sgmap/pix pull request #562
Opened 2017-10-18 07:51 UTC by Hypernikao

2017-10-26 09:44 UTC, Hypernikao commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Administrateur Pix, je veux stocker la liste des acquis pour un utilisateur.](https://trello.com/c/Yi36ZyR5/819-etq-administrateur-pix-je-veux-stocker-la-liste-des-acquis-pour-un-utilisateur)

2017-10-30 11:12 UTC, MBrandone requested changes

2017-10-30 11:12 UTC, MBrandone commented on api/tests/acceptance/infrastructure/repositories/skill-repository_test.js
> +      const skillsFormatted = [
je mettrai formattedSkills pour être ISO à l'anglais

2017-10-30 11:12 UTC, MBrandone commented on api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
> +
vu que c'est un Set, je m'attendrais à ce que la variable retourné s'apelle skills (pour comprendre qu'il y en a plusieurs)

2017-10-30 11:12 UTC, MBrandone commented on api/tests/unit/domain/services/assessment-service_test.js
> +              expect([...skills.validatedSkills]).to.deep.equal([...expectedValitedSkills]);
Ca veut dire quoi les [... ]

2017-10-30 11:12 UTC, MBrandone commented on api/tests/unit/domain/services/skills-service_test.js
> +    it('should be a function', () => {
On s'était dit qu le test 'should be a function' peut être enlevé maintenant

2017-10-30 11:12 UTC, MBrandone commented on api/lib/infrastructure/repositories/skill-repository.js
>  function _fetchSkillsFromCompetence(competenceId, cacheKey, resolve, reject) {
:O un repo qui apelle un autre repo. 
C'est vrai que c'est pas nouveau, mais on peut regarder si y a moyen de faire mieux rapidement.

2017-10-30 11:12 UTC, MBrandone commented on api/lib/infrastructure/repositories/skill-repository.js
>  module.exports = {
je suis ok pour avoir une reflexion sur la division cache et db, mais la fonction getFromCompetenceId est susceptible d'appeler la base de données. Donc ça peut etre trompeur de le mettre dans un objet champs 'db'

2017-10-30 11:12 UTC, MBrandone commented on api/tests/unit/infrastructure/repositories/skill-repository_test.js
> +      // then
un peu surpris par le forge et le invoke.
On pourrait pas utiliser save directement ?

2017-10-30 11:12 UTC, MBrandone commented on api/lib/application/assessments/assessment-controller.js
> +      .then(({ assessmentPix }) => {
On est obligé de le nommer assessmentPix ? Je suis plutôt chaud pour garder le nommage assessment. Sinon ça vaudrait dire qu'on met la distinction assessmentPix et assessmentCat dans la partie lib, et je pense qu'il vaut mieux pas.

2017-10-30 11:12 UTC, MBrandone commented on api/lib/application/assessments/assessment-controller.js
> +      .then(({ assessmentPix }) => {
Je viens de voir que le service est plein de assessmentPix ... mais je pense toujours que plus cette distinction se fait loin, mieux c'est

2017-10-30 11:12 UTC, MBrandone commented on api/lib/infrastructure/repositories/skill-repository.js
> +  db: {
j'ai l'impression que c'est long pour juste une sauvegarde.
ce serait pas plus efficace un truk du genre : 
return new Skill
.collection([arraySkills])
.save()

2017-10-30 13:42 UTC, Hypernikao commented on api/lib/application/assessments/assessment-controller.js
> +      .then(({ assessmentPix }) => {
C'est pour faire la distinction entre l'objet Assessment Cat et celui qui est wrapper par Bookshelf. Je suis preneur s'il y a mieux

2017-10-30 13:43 UTC, Hypernikao commented on api/lib/infrastructure/repositories/skill-repository.js
>  function _fetchSkillsFromCompetence(competenceId, cacheKey, resolve, reject) {
Vu avec toi

2017-10-30 13:49 UTC, Hypernikao commented on api/lib/infrastructure/repositories/skill-repository.js
>  module.exports = {
Ok pour un point technique

2017-10-30 14:30 UTC, Hypernikao commented on api/lib/infrastructure/repositories/skill-repository.js
> +  db: {
Pas mieux pour l'instant

2017-10-30 14:31 UTC, Hypernikao commented on api/tests/acceptance/infrastructure/repositories/skill-repository_test.js
> +      const skillsFormatted = [
Done

2017-10-30 14:36 UTC, Hypernikao commented on api/tests/unit/domain/services/assessment-service_test.js
> +              expect([...skills.validatedSkills]).to.deep.equal([...expectedValitedSkills]);
Spread operator :)

2017-10-30 14:37 UTC, Hypernikao commented on api/tests/unit/domain/services/skills-service_test.js
> +    it('should be a function', () => {
ok

2017-10-30 14:38 UTC, Hypernikao commented on api/tests/unit/infrastructure/repositories/skill-repository_test.js
> +      // then
Nop

2017-10-30 14:40 UTC, MBrandone approved these changes

2017-10-30 15:04 UTC, merged