[#590] [TECH] Utilisation de vues privées au niveau des Epreuves (dans Airtable) afin de sécuriser (stabiliser) la plateforme (US-892).
sgmap/pix pull request #591
Opened 2017-11-17 19:12 UTC by jbuget

2017-11-20 09:28 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [Optimiser la sélection des challenges pour une Compétence --> vue protégée airtable](https://trello.com/c/CFlim7bo/892-optimiser-la-s%C3%A9lection-des-challenges-pour-une-comp%C3%A9tence-vue-prot%C3%A9g%C3%A9e-airtable)

2017-11-22 14:39 UTC, mackwic requested changes

2017-11-22 14:39 UTC, mackwic commented on api/lib/cat/assessment.js
> +      challenge => challenge.hardestSkill.difficulty === 2 && challenge.timer === undefined
des petites parenthèses aussi pour faciliter la lecture ?

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service-utils.js
> +    return assessment.nextChallenge ? assessment.nextChallenge.id : null;
pas fan de la ternaire...

Propositions:
```js
// the old classic
if (!assessment.nextChallenge) {
  return null;
}
return assessment.nextChallenge.id;
```

```js
return _.get(assessment, 'nextChallenge.id', null);
```

```js
const { nextChallenge } = assessmentAdapter.getAdaptedAssessment(answersPix, challengesPix, skills);
return nextChallenge.id || null;
```

Question: pourquoi transformer `undefined` en `null` dans le cas non-passant ? Quel intérêt ?

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +  return answerRepository.findByAssessment(assessment.get('id'))
si ça `findByAssessment` pourquoi ça prend un assessment id et pas un Assessment ?

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +    .then(fetchedAnswers => (answers = fetchedAnswers))
missing parens: `(fetchedAnswers) =>`

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +  return answerRepository.findByAssessment(assessment.get('id'))
(comme les autres)

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +    .then(skills => assessmentUtils.getNextChallengeInAdaptiveCourse(answers, challenges, skills));
je suis perplexe... Est-ce que y'a pas de la logique à déplacer dans un repository ? Est-ce qu'il y a une requete SQL par ligne ?

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +      .catch(reject);
normalement pas besoin du catch si tu retourne la promise

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +      resolve(null);
`return null`

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +      resolve(null);
`return null;`

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +      resolve(null);
`return null`

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +    .then(() => courseRepository.get(assessmentPix.get('courseId')))
`courseRepository.getByCourseId` ?

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +    .then(course => (coursePix = course))
`(course)`

2017-11-22 14:39 UTC, mackwic commented on api/lib/domain/services/assessment-service.js
> +    .then(challenges => challengesPix = challenges)
`(challenges) => (challengesPix = challenges)`

2017-11-22 14:39 UTC, mackwic commented on api/lib/infrastructure/repositories/challenge-repository.js
> +    }
je suis surpris qu'il n'y a pas de helper pour ça

2017-11-22 14:39 UTC, mackwic commented on api/lib/infrastructure/repositories/competence-repository.js
> +    }
duplication sans valeur

2017-11-22 14:39 UTC, mackwic commented on api/lib/infrastructure/repositories/competence-repository.js
> +    }
duplication sans valeur

2017-11-22 14:39 UTC, mackwic commented on api/lib/infrastructure/repositories/competence-repository.js
> +    }
exemple de comment résoudre ça:

```js
module.exports = {
  list() {
    return cache(() => airtable.getRecords(AIRTABLE_TABLE_NAME, {}, serializer));
  }
}

function cache(otherFunc) {
  _.memoize.Cache = nodeCacheInstance; // pas besoin de le faire a chaque fois mais simplifie l'exemple
  let memoized = _.memoize(otherFunc);
  return memoized;
}
```

2017-11-22 14:39 UTC, mackwic commented on api/tests/acceptance/application/answer-controller-find_test.js
> +    afterEach((done) => {
tant qu'à faire virer le `done`

2017-11-22 14:39 UTC, mackwic commented on api/tests/acceptance/application/answer-controller-find_test.js
> +    beforeEach((done) => {
virer le `done` tant qu'à faire

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/domain/services/assessment-service_test.js
> +      answerRepository.findByAssessment.restore();
utiliser une sandbox ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
> +   * #findByCompetence
virer le commentaire ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +    sinon.stub(airtable, 'getRecords');
utiliser une sandbox ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          expect(cache.set).to.have.been.calledWith('competence-repository_list', competenceRecords);
je comprends pas pourquoi stuber et mocker alors qu'on peut simplement faire un get sur le cache ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          done();
devrait pas être nécessaire si tu retourne la promesse ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          expect(cache.get).to.have.been.calledWith('competence-repository_list');
pour moi cette assertion teste un détail d'implem non contractuel. Je pense que cette assertion n'est pas nécessaire

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          expect(cache.set).to.have.been.calledWith(`competence-repository_get_${competence.id}`, fetchedCompetence);
meme remarque que tout à l'heure: tu peux simplement get sans mocker

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/skill-repository_test.js
> +   * #findByCompetence
virer le commentaire ?

2017-11-22 14:39 UTC, mackwic commented on api/tests/unit/infrastructure/repositories/skill-repository_test.js
> +          expect(cache.get).to.have.been.calledWith(`skill-repository_find_by_competence_${competence.id}`);
détail d'implem

2017-11-22 14:40 UTC, mackwic commented
surtout de la forme, en terme de logique rien ne m'a choqué. Quelques typos sur les lambdas, mais rien de grave. Un peu de duplication

2017-11-22 17:59 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +  return answerRepository.findByAssessment(assessment.get('id'))
+1 mais c'est trop impactant pour rentrer dans cette PR. je l'ai noté dans le trello de dette (qu'il faudra reventiler ailleurs)

2017-11-22 18:01 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    .then(skills => assessmentUtils.getNextChallengeInAdaptiveCourse(answers, challenges, skills));
Il y a effectivement pas mal de choses à faire. Avec @Akhilian on a entamé une migration progressive vers Clean Architecture, mais on y va petit pas par petit pas. Là je m'enfonçais déjà trop loin.

PS : je crains de te ressortir souvent cette réponse dans les remarques à venir, mais je me suis déjà tapé un tunnel de 2 semaines, ... :-/

2017-11-22 18:02 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    .then(fetchedAnswers => (answers = fetchedAnswers))
il n'y a qu'un paramètre, on peut ne pas mettre de parenthèses. On met des parenthèses si params.length >= 2 ou params.length === 0

2017-11-22 18:02 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +      resolve(null);
+1

2017-11-22 18:08 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +      resolve(null);
Finalement, ça pète trop de tests relous (dont acceptance)... 😞 si tu m'autorises, je laisse en l'état (le code était comme ça avant moi, ça me saoule, mais là c'est trop)

2017-11-22 18:10 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +      .catch(reject);
je sais... #déso

2017-11-22 18:12 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    .then(() => courseRepository.get(assessmentPix.get('courseId')))
😭 
PS : "quand on aura un truc propre", on pourra se contenter de #get(courseId)

Dans Hibernate / Spring, par défaut `#get` cherche par ID. Si on veut récupérer 1 ressource par un autre critère, la convention est `#getByCountryAndCityOrderByStreet`

2017-11-22 18:15 UTC, jbuget commented on api/lib/domain/services/assessment-service.js
> +    .then(challenges => challengesPix = challenges)
je demande confirmation de la règle à l'équipe sur Slack @tech

2017-11-22 18:16 UTC, jbuget commented on api/lib/infrastructure/repositories/challenge-repository.js
> +    }
bien vu, j'ai ajouté une carte au Trello de tech Debt

2017-11-22 18:17 UTC, jbuget commented on api/lib/infrastructure/repositories/competence-repository.js
> +    }
cf. ci-dessus

2017-11-22 18:23 UTC, jbuget commented on api/tests/acceptance/application/answer-controller-find_test.js
> +    beforeEach((done) => {
+1

2017-11-22 18:25 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          done();
c'est ce que je me suis dit. j'ai tenté pas mal de choses, mais je me suis tapé des faux-positifs / négatifs. donc je me suis résigné à utiliser le `done`. si tu as mieux, je prends.

2017-11-22 18:26 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          expect(cache.get).to.have.been.calledWith('competence-repository_list');
je ne suis pas d'accord (pour la première fois de la PR). elle vérifie qu'on appelle la bonne clé et nous protège contre un renommage malheureux (déjà vu). la clé du set est une sorte de contrat pour le get.

2017-11-22 18:27 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/skill-repository_test.js
> +          expect(cache.get).to.have.been.calledWith(`skill-repository_find_by_competence_${competence.id}`);
protection contre un potentiel renommage raté.

2017-11-22 18:30 UTC, jbuget commented on api/tests/unit/domain/services/assessment-service_test.js
> +      answerRepository.findByAssessment.restore();
+1

2017-11-22 18:31 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/challenge-repository_test.js
> +   * #findByCompetence
Je trouve que ça permet de s'y retrouver dans les tests (le fichier est gros). On demande à l'équipe demain après le stand-up

2017-11-22 18:33 UTC, jbuget commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +    sinon.stub(airtable, 'getRecords');
+1

2017-11-23 09:21 UTC, qcattez commented on api/tests/unit/infrastructure/repositories/competence-repository_test.js
> +          done();
Il sert à quoi le `done()` ici ?

2017-11-27 12:56 UTC, merged