[#] [FEATURE] Ajouter un loader quand une question est passée/validée et modifier le "Je passe" (US-898)
sgmap/pix pull request #597
Opened 2017-11-21 10:30 UTC by MelanieMEB

** Ticket Trello : ** https://trello.com/c/BSG4KZ75/898-etq-user-jv-une-zone-je-valide-je-passe-am%C3%A9lior%C3%A9e-avec-un-loader-unique
** RA : ** http://898-button-pass-and-valid-with-loader.pix-dev.ovh/

** Ce qui a été réalisé : **
- Ajout d'un gif
- Ajout de CSS pour le nouveau loader
- Quelque soit le bouton sur lequel on clique, on set (_validateButtonStatus', 'pending') (comme précédemment) pour n'afficher que le loader

2017-11-22 15:04 UTC, mackwic requested changes

2017-11-22 15:04 UTC, mackwic commented on live/app/components/challenge-actions.js
> +      this.set('_validateButtonStatus', 'pending');
extraire la magic value dans une constante en haut de fichier

2017-11-22 15:04 UTC, mackwic commented on live/app/styles/components/_challenge-actions.scss
> +  font-family: $font-lato;
proposer une font alternative pour ceux qui n'ont pas lato ? La fallback font c'est Times New Roman en général, `sans-serif` ça serait mieux.

2017-11-22 15:04 UTC, mackwic commented on live/app/styles/components/_challenge-actions.scss
> +  margin: 7px;
est-ce que c'est encore joli si tu change la taille de la fenetre ?

2017-11-22 15:04 UTC, mackwic commented on live/tests/integration/components/challenge-actions-test.js
> +    it('should be replaced by a loader during treatment', function() {
👍

2017-11-22 15:04 UTC, mackwic commented on live/tests/integration/components/challenge-actions-test.js
> +      this.$(VALIDATE_BUTTON).click();
👍

2017-11-22 15:04 UTC, mackwic commented on live/tests/integration/components/challenge-actions-test.js
> +        return new RSVP.Promise(() => {
pas besoin de retour à la ligne

2017-11-22 16:43 UTC, MelanieMEB commented on live/app/styles/components/_challenge-actions.scss
> +  font-family: $font-lato;
OK

2017-12-01 08:33 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ User, JV une zone "Je valide" / "je passe" améliorée avec un loader unique](https://trello.com/c/BSG4KZ75/898-etq-user-jv-une-zone-je-valide-je-passe-am%C3%A9lior%C3%A9e-avec-un-loader-unique)

2017-12-01 08:58 UTC, Akhilian approved these changes

2017-12-01 09:00 UTC, mackwic approved these changes

2017-12-01 10:15 UTC, merged