[#][FEATURE]Afficher la bannière de certification sur les épreuves. (US-887)
sgmap/pix pull request #600
Opened 2017-11-22 09:31 UTC by MelanieMEB

**Ticket Trello :** https://trello.com/c/YvHXEeVW/887-etq-candidat-jv-voir-mon-userid-sur-le-bandeau-de-chaque-epreuve-dun-test-de-certif-au-lieu-du-titre-du-test
**RA :** http://887-use-certification-banner-in-challenge.pix-dev.ovh/

**Ce qui a été réalisé :**
- Ajout d'un IF dans le template de la route challenge
- Appel de l'user du store pour afficher le nom seulement si c'est un test de certification
- Ajout de tests unitaires sur des parties de challenges.js qui n'étaient pas testés
- Ajout du "type" d'assessment dans l'assessment serializer pour que l'api renvoie le type

**Pour tester :**
- Vu qu'il n'y a pas encore de test de certification qui se lance, il faut lancer un assessment, et modifier ensuite son type dans la base de données, pour que le type soit "CERTIFICATION".

2017-11-22 14:59 UTC, mackwic requested changes

2017-11-22 14:59 UTC, mackwic commented on live/app/routes/assessments/challenge.js
> +      model.isCertification = (type === 'CERTIFICATION');
ça devrait être dans le model, pas dans la route

2017-11-22 14:59 UTC, mackwic commented on live/app/routes/assessments/challenge.js
> +      } else {
else inutile + inconsistant

Proposition 1) Pas de else, ça équivaut au code existant. Ne règle pas l'inconsistence
Proposition 2) `return Promise.resolve(null)` après le if

2017-11-22 14:59 UTC, mackwic commented on live/tests/unit/routes/assessments/challenge-test.js
> +      promise.then(() => {
return

2017-11-22 14:59 UTC, mackwic commented on live/tests/unit/routes/assessments/challenge-test.js
> +      promise.then(() => {
return

2017-11-22 14:59 UTC, mackwic commented on live/tests/unit/routes/assessments/challenge-test.js
> +      promise.then(() => {
return

2017-11-22 14:59 UTC, mackwic commented on live/tests/unit/routes/assessments/challenge-test.js
> +      promise.then((createdModel) => {
return

2017-11-22 14:59 UTC, mackwic commented on live/tests/unit/routes/assessments/challenge-test.js
> +        expect(createdModel.toString()).to.deep.equal(expectedModel.toString());
pourquoi `.toString()` ? pourquoi deep equal sur des strings ?

2017-12-04 15:37 UTC, MelanieMEB commented on live/tests/unit/routes/assessments/challenge-test.js
> +      data: { authenticated: { userId: 12, token: 'VALID-TOKEN' } }
extraire userID dans une constante et l'utiliser l98

2017-12-04 15:42 UTC, MelanieMEB commented on live/tests/integration/components/certification-results-page-test.js
> +      this.render(hbs`{{certification-results-page user=user courseId=courseId}}`);
certificationNumber

2017-12-04 15:42 UTC, MelanieMEB commented on live/tests/integration/components/certification-banner-test.js
> +    const courseId = 'course_id';
certification number

2017-12-04 15:43 UTC, MelanieMEB commented on live/app/templates/components/certification-results-page.hbs
> +  {{certification-banner user=user courseId=courseId}}
certification Number

2017-12-04 15:44 UTC, MelanieMEB commented on live/app/templates/components/certification-banner.hbs
> +    #{{courseId}}
certification number

2017-12-04 15:44 UTC, MelanieMEB commented on live/app/templates/certifications/results.hbs
> +{{certification-results-page user=model.user courseId=model.courseId}}
certification number

2017-12-04 15:44 UTC, MelanieMEB commented on live/app/templates/assessments/challenge.hbs
> +      {{certification-banner user=model.user courseId=model.assessment.certificationNumber}}
certification number

2017-12-04 15:45 UTC, MelanieMEB commented on live/app/routes/assessments/challenge.js
> +    if (!model.assessment.get('isCertification')) {
inverser la condition et les blocks

2017-12-04 16:22 UTC, mackwic approved these changes

2017-12-05 08:25 UTC, merged