[#] [FEATURE] Enregistrement de la date de fin d'une certification (US-986).
sgmap/pix pull request #641
Opened 2018-01-04 09:31 UTC by MelanieMEB

2018-01-04 11:07 UTC, MelanieMEB commented
Question : je me demande si le format de sauvegarde de la date est le bon ? (YYYY-MM-DD HH:mm:ss).
Sur la RA, ça me semble correct.

2018-01-09 09:30 UTC, mackwic requested changes

2018-01-09 09:30 UTC, mackwic commented on api/lib/application/assessments/assessment-controller.js
> +                  moment().format('YYYY-MM-DD HH:mm:ss'));
https://momentjs.com/docs/#/displaying/as-iso-string/ ISO c'est mieux je pense

2018-01-09 09:47 UTC, mackwic requested changes

2018-01-09 09:47 UTC, mackwic commented on api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js
> +          clock = sinon.useFakeTimers(new Date('Mon, 04 Feb 2018'));
utiliser le format officiel: https://stackoverflow.com/a/4321366

2018-01-09 09:47 UTC, mackwic commented on api/lib/application/assessments/assessment-controller.js
> +                  moment().format('YYYY-MM-DD HH:mm:ss'));
nope, mieux vaut le format officiel finalement: https://stackoverflow.com/a/4321366

2018-01-11 13:31 UTC, mlaurent approved these changes

2018-01-12 11:53 UTC, merged