TECH : Upgrade Ember version from ^2.7.0 to ^2.8.0
sgmap/pix pull request #65
Opened 2016-09-27 12:44 UTC by jbuget

- [Ember Release Changelog](https://github.com/emberjs/ember.js/blob/v2.8.0/CHANGELOG.md)
- [Ember Migration guide](http://emberjs.com/blog/2016/09/08/ember-2-8-and-2-9-beta-released.html)

2016-09-27 15:16 UTC, mackwic commented
tu peux pousser un commit vide pour déployer en staging ?

2016-09-28 18:05 UTC, twickham commented
I've deployed this PR to http://tech-upgrade-ember-to-2-8.pix.beta.gouv.fr. Please check it out

2016-09-29 12:13 UTC, mackwic commented
c'est WIP ça non ?

2016-09-29 12:37 UTC, mackwic commented
🐛 Ya un bug: on ne peut pas remplir l'input email du formulaire d'identification.

2016-09-29 12:38 UTC, mackwic requested changes
:bug: le champ email de l'identification marche pas :(

2016-09-29 12:54 UTC, jbuget commented
> le champ email de l'identification marche pas :( 

J'ai l'impression que c'est une régression ember-form-for :-(

Ca me saoule de perdre autant de temp pour 3 pauvres champs.

2016-09-29 13:36 UTC, bdavidxyz requested changes
carton rouge

2016-09-29 13:36 UTC, bdavidxyz approved these changes

2016-09-29 13:37 UTC, bdavidxyz commented
carton rouge était un simple test de review :)

2016-09-29 13:37 UTC, mackwic commented
@jbuget je m'en occupe ce soir, demain c'est réglé

2016-10-05 01:03 UTC, twickham commented
I've deployed this PR to http://tech-upgrade-ember-to-2-8.pix.beta.gouv.fr. Please check it out

2016-10-05 08:17 UTC, twickham commented
I've deployed this PR to http://tech-upgrade-ember-to-2-8.pix.beta.gouv.fr. Please check it out

2016-10-05 09:21 UTC, mackwic commented on live/app/components/identification-form.js
> +  const regExp = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
OMG. 😱 Quelle horreur. May I... https://davidcel.is/posts/stop-validating-email-addresses-with-regex/ ?

2016-10-05 09:24 UTC, mackwic commented on live/app/components/identification-form.js
> +        callActionOnUserIdentified(this);
1) pourquoi tu as sorti les fonctions du components ? Ça éviterai d'avoir à passer le `this`
2) pourquoi meme utiliser des fonctions quand c'est des one-liners ? (particulièrement la dernière)

2016-10-05 09:25 UTC, jbuget commented on live/app/components/identification-form.js
> +  const regExp = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
j'ai pris le premier truc un peu glouton que j'ai trouvé. je m'attendais à ce type de réaction. je prends toute amélioration  qui ne demande pas d'envoi de mail. le but de cette regexp est de faire un contrôle "simple & rapide" sachant qu'effectivement la bonne pratique est d'envoyer un mail de confirmation etc. (cf. stories du futur, un jour, peut-être...)

2016-10-05 09:26 UTC, jbuget commented on live/app/components/identification-form.js
> +        callActionOnUserIdentified(this);
1) pour ne pas les exposer (je me suis beaucoup posé la question, effectivement à cause du this)

2) pour facilier la lecture en mode newspaper ;

je ne suis pas fermé à modifier la 1) ou la 2) si vous préférez

2016-10-05 09:28 UTC, mackwic commented on live/app/templates/index.hbs
> +                {{identification-form onUserIdentified="navigateToHome"}}
pas mal du tout 👍

2016-10-05 09:34 UTC, mackwic commented
Éviter de binder la session au fur et a mesure de la frappe, seulement à la validation:

<img width="881" alt="screen shot 2016-10-05 at 11 33 32" src="https://cloud.githubusercontent.com/assets/558091/19108106/93625854-8aef-11e6-8181-f7eccdc2868c.png">

2016-10-05 09:34 UTC, merged

2016-10-05 09:35 UTC, mackwic commented on live/app/components/identification-form.js
> +  const regExp = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
utilise celle du navigateur: http://stackoverflow.com/questions/11866910/how-to-force-a-html5-form-validation-without-submitting-it-via-jquery