[#] [FEATURE] Affichage des tests réalisés sur le /board au lieu du % (US-946).
sgmap/pix pull request #658
Opened 2018-01-16 08:52 UTC by MelanieMEB

2018-01-18 13:16 UTC, MelanieMEB commented
Changement de la colonne completePercentage > testsFinished
Lors des changements sur la colonne, le ROUND() ne donne pas de nombre sans décimal (résultat sous la forme 8.0), donc j'ai besoin à plusieurs endroits de ROUND coté front pour un affichage correct du résultat.

2018-01-19 14:31 UTC, mackwic commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +        testsFinished: knex.raw('ROUND(??*0.16, 0)', ['completionPercentage'])
- opérateurs infixes => mettre des espaces autour de l'opérateur (ici `*`)
- commentaire XXX qui dit que `??` == binding de la valeur de la row

2018-01-19 14:31 UTC, mackwic commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +          completionPercentage: knex.raw('??*6.25', ['testsFinished'])
meme chose

2018-01-19 14:35 UTC, mackwic approved these changes
OK une fois que les commentaires mineurs ont été pris en compte

2018-01-22 09:34 UTC, MelanieMEB commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +        testsFinished: knex.raw('ROUND(??*0.16, 0)', ['completionPercentage'])
OK !

2018-01-22 09:34 UTC, MelanieMEB commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +          completionPercentage: knex.raw('??*6.25', ['testsFinished'])
OK !

2018-01-23 09:23 UTC, jbuget requested changes

2018-01-23 09:23 UTC, jbuget commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +        testsFinished: knex.raw('ROUND(?? * 0.16, 0)', ['completionPercentage'])
Sortir ce _magic number_ dans une variable nommée pour aider à la compréhension (c'est pas commun 0.16)

2018-01-23 09:23 UTC, jbuget commented on api/db/migrations/20180116161332_modify_column_completedPercentage_to_tests_finished_in_snapshots.js
> +          completionPercentage: knex.raw('?? * 6.25', ['testsFinished'])
Idem, sortir le nombre dans une const bien nommée

2018-01-23 09:23 UTC, jbuget commented on live/app/models/snapshot.js
> +  numberOfTestsFinished: computed('testsFinished', function() {
Je pense qu'on peut rajouter facilement et rapidement 2 petits TU sur cette computed property

2018-01-24 10:08 UTC, MelanieMEB commented on live/app/models/snapshot.js
> +  numberOfTestsFinished: computed('testsFinished', function() {
Deux tests ajoutés

2018-01-24 13:35 UTC, jbuget approved these changes

2018-01-24 13:36 UTC, merged

2018-01-31 09:59 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Organisme, JV que la colonne "% d'avancement" dans /board soit remplacée par "Tests réalisés"](https://trello.com/c/kYwVzNis/946-etq-organisme-jv-que-la-colonne-davancement-dans-board-soit-remplac%C3%A9e-par-tests-r%C3%A9alis%C3%A9s)