[#665] [TECH] Migrer le serializer JSON:API pour les groupe de tests
sgmap/pix pull request #663
Opened 2018-01-23 09:13 UTC by jbuget

2018-01-23 10:09 UTC, qcattez requested changes

2018-01-23 10:09 UTC, qcattez commented on api/lib/infrastructure/serializers/jsonapi/course-group-serializer.js
> +          courseGroup.courses.forEach((course) => {
On est obligé de faire ce traitement ? `nbChallenges` n'est pas déjà à 0 si il n'y a pas de `challenges` ?

2018-01-23 10:09 UTC, qcattez commented on api/lib/infrastructure/serializers/jsonapi/course-group-serializer.js
> +        attributes: ['description', 'imageUrl', 'name', 'nbChallenges'],
Missing `duration`, `isAdaptative`, `sessionCode` et `type`.
On peut pas utiliser le serializer de Course au lieu de recoder la même logique dans ce serializer ?

2018-01-23 10:15 UTC, MBrandone commented on api/tests/unit/infrastructure/serializers/jsonapi/course-group-serializer_test.js
> +        const courseGroup = new CourseGroup();
Yoh ! 
Dans ce test, on utilise new CourseGroup(), qui vient d'un model Airtable. Malgré que l'objet Airtable ressemble pas mal à un objet JSON basique, si on voudrait faire les choses bien jusqu'au bout, je pense qu'il faudrait créer un nouveau domain model courseGroup que l'on utiliserait pour sortir du repo, et en entrée du serializer.
C'est non-bloquant, vu que ce code est peu utilisé.

2018-01-23 16:23 UTC, jbuget commented on api/lib/infrastructure/serializers/jsonapi/course-group-serializer.js
> +          courseGroup.courses.forEach((course) => {
non, car c'est une propriété qu'on rajoute (d'où le `foreach`).
ce que j'aurais pu faire pour rendre ça peut-être  encore plus explicite est un ternaire du type : 
```
course.nbChallenges = (course.challenges) ? course.challenges.length : 0;
```

2018-01-23 16:26 UTC, jbuget commented on api/lib/infrastructure/serializers/jsonapi/course-group-serializer.js
> +        attributes: ['description', 'imageUrl', 'name', 'nbChallenges'],
Je me suis posé la question, mais :

1. je voulais juste faire le moins de modif, ma priorité étant de passer un ancien serializer de plus en mode nouvelle implem
2. j'ai de gros doute que ce code soit encore d'actualité (on n'affiche plus nulle part les Course Groups a.k.a. "défis de la semaine", qu'on ne met plus à jour
3. pour l'instant, on n'a pas encore appelé de serializer dans un serializer, parmi les "nouveaux" serializers

2018-01-23 16:45 UTC, qcattez commented on api/lib/infrastructure/serializers/jsonapi/course-group-serializer.js
> +          courseGroup.courses.forEach((course) => {
J'ai une préférence pour le ternaire mais ça me va comme ça aussi :)

2018-01-23 16:45 UTC, qcattez approved these changes

2018-01-25 09:31 UTC, jbuget commented on api/tests/unit/infrastructure/serializers/jsonapi/course-group-serializer_test.js
> +        const courseGroup = new CourseGroup();
rappel : vu avec Benoit et Benjamin, on va finalement supprimer les CourseGroups

2018-01-25 18:57 UTC, jbuget commented
Je clos et supprime la PR car les `course-groups` sont obsolètes cf. PR #666

2018-01-25 18:57 UTC, closed without merging