[#673] [FEATURE] Ajout d'un endpoint de création de session (US-1028).
sgmap/pix pull request #673
Opened 2018-02-01 14:33 UTC by DaRiviere

2018-02-01 14:36 UTC, DaRiviere commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ PixMaster JV pouvoir créer une session de certification](https://trello.com/c/HIe5M3Kf/1028-etq-pixmaster-jv-pouvoir-cr%C3%A9er-une-session-de-certification)

2018-02-01 17:24 UTC, jbuget requested changes
Ce qui bloque pour moi c'est le fait de voir le vrai nom d'un partenaire (en l'occurrence, Sophie de Nice). A part ça, well done ;-)

2018-02-01 17:24 UTC, jbuget commented on api/lib/infrastructure/data/session.js
> +Bookshelf.plugin('registry');
Remarque valable pour toutes les classes dans `infra/data` pourquoi est-ce qu'on injecte ce plugin ici ?

J'ai l'impression qu'on l'inject du coup plein de fois pour rien.

2018-02-01 17:24 UTC, jbuget commented on api/lib/infrastructure/repositories/session-repository.js
> +function _toDomain(bookshelfSession) {
je suis de moins en moins fan de trouver ce genre de méthode ici. Je pense qu'elle devrait être directement mise dans l'objet BookshelfModel correspondant.

2018-02-01 17:24 UTC, jbuget commented on api/tests/unit/application/session/session-controller_test.js
> +        examiner: 'Sophie Rapetti',
Je propose de ne pas mettre le nom d'une vraie correspondante C2i.

2018-02-01 17:24 UTC, jbuget commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +        examiner: 'Sophie Rapetti',
Là aussi

2018-02-01 17:24 UTC, jbuget commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +    examiner: 'Sophie Rapetti',
Idem, changer le nom pour éviter d'éventuels problèmes de non respect de la vie privée des gens.

2018-02-02 10:33 UTC, Akhilian commented on api/lib/infrastructure/data/session.js
> +Bookshelf.plugin('registry');
En vrai, je ne sais pas à quoi il sert --"
Je regarde si ça fait une différence de l'enlever.

2018-02-02 10:33 UTC, Akhilian commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +    examiner: 'Sophie Rapetti',
J'avoue, c'était un hommage mais tu as raison.

2018-02-02 10:45 UTC, Akhilian commented on api/lib/infrastructure/data/session.js
> +Bookshelf.plugin('registry');
Done, j'ai remonté l'injection du plugin à la racine.

2018-02-05 15:57 UTC, mlaurent commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +
_a_ Session instead of _an_ Session

2018-02-05 15:58 UTC, mlaurent commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +    it('should convert an Session model object into JSON API data', function() {
_a_ Session instead of _an_ Session

2018-02-05 16:22 UTC, mlaurent submitted a review, later dismissed

2018-02-12 15:36 UTC, MelanieMEB commented on api/db/migrations/20180131153634_create_sessions_table.js
> +    t.text('description').defaultTo('');
Ajout de la colonne knex createdAt ?

2018-02-12 15:36 UTC, MelanieMEB commented on api/lib/infrastructure/data/session.js
> +      error: 'Veuillez renseigner une heure de session au format (hh:mm).',
De manière générale, est-ce que la date sera la date locale ou la date UTC ?

2018-02-12 15:36 UTC, MelanieMEB commented on api/tests/unit/application/session/index_test.js
> +describe('Unit | Route | session-router', function() {
Est-ce utile de vérifier l'existence des routes ?
Après, c'est toujours des tests, je garde ^^

2018-02-12 15:43 UTC, DaRiviere commented on api/lib/infrastructure/data/session.js
> +      error: 'Veuillez renseigner une heure de session au format (hh:mm).',
C'est pas ici qu'on doit s'occuper de ça, mais il est vrai que tu ouvres une question intéressante.
A discuter avec @Akhilian et @Benoit

2018-02-12 15:45 UTC, DaRiviere commented on api/tests/unit/application/session/index_test.js
> +describe('Unit | Route | session-router', function() {
Pas super utile en réalité, mais idem "still a test"

2018-02-12 15:48 UTC, DaRiviere commented on api/db/migrations/20180131153634_create_sessions_table.js
> +    t.text('description').defaultTo('');
Vraiment utile sur cette table ? ou norme projet à définir ?

2018-02-12 15:57 UTC, mlaurent commented on api/lib/infrastructure/data/session.js
> +      error: 'Vous n\'avez pas renseignez de centre de certification.',
"Renseigné" plutôt que "Renseignez"

Pareil pour tous les messages d'erreur suivants.

2018-02-12 15:57 UTC, mlaurent commented on api/tests/acceptance/application/session-controller_test.js
> +        method: 'POST', url: '/api/sessions', payload: {
Est-ce qu'on ne pourrait pas sortir une const commune aux deux derniers tests, parce que c'est la même chose ?!

2018-02-12 15:59 UTC, DaRiviere commented on api/lib/infrastructure/data/session.js
> +      error: 'Vous n\'avez pas renseignez de centre de certification.',
Ok je corrige ça !

2018-02-12 16:10 UTC, DaRiviere commented on api/tests/acceptance/application/session-controller_test.js
> +        method: 'POST', url: '/api/sessions', payload: {
On peut en effet, je fais ça !

2018-02-12 16:10 UTC, MBrandone commented on api/tests/unit/infrastructure/models/session_test.js
> +    it('should fail when the date is empty or not in format (jj/mm/yyyy)', () => {
J'aurai bien ajouté un test avec une date bien ecrite mais qui n'existe pas (genre 31/02/2018) pour justifier la grande regex (qui vérifie le formatage et la validité)

2018-02-12 16:16 UTC, DaRiviere commented on api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
> +    it('should convert an Session model object into JSON API data', function() {
Thx

2018-02-12 16:45 UTC, DaRiviere commented on api/tests/unit/infrastructure/models/session_test.js
> +    it('should fail when the date is empty or not in format (jj/mm/yyyy)', () => {
Bonne idée !

2018-02-13 11:20 UTC, mlaurent approved these changes

2018-02-13 14:24 UTC, jbuget approved these changes

2018-02-13 15:51 UTC, merged