[#] [FEATURE] Amélioration du script récupérant les résultats de certification(US-1067).
sgmap/pix pull request #679
Opened 2018-02-12 13:43 UTC by MelanieMEB

- Modification de la route /certification-courses/id/result pour qu'elle récupère les informations en base
- Renommage de l'ancienne route

2018-02-12 14:32 UTC, MelanieMEB commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ PixMaster JV pouvoir utiliser le script de récupération des scores sans planter la prod](https://trello.com/c/7eIWnJZE/1067-etq-pixmaster-jv-pouvoir-utiliser-le-script-de-r%C3%A9cup%C3%A9ration-des-scores-sans-planter-la-prod)

2018-02-15 17:15 UTC, Akhilian requested changes

2018-02-15 17:15 UTC, Akhilian commented on api/lib/application/certificationCourses/certification-course-controller.js
> +        reply(certificationCourseSerializer.serializeResult(certificationResult));
Si la certification n'existe pas, ça provoque une 500 :/

2018-02-15 17:15 UTC, Akhilian commented on api/lib/domain/services/certification-service.js
> +      .then(foundAssessement => {
Ici, `foundAssessement` peut être `null` si l'assessment n'existe pas :/

2018-02-15 17:15 UTC, Akhilian commented on api/lib/domain/services/certification-service.js
> +          listCertifiedCompetences: assessment.marks
J'ai un petit doute sur cette propriété `listCertifiedCompetences`.
Est-ce qu'on parle de "certified competence" pour une compétence qu'on invalide ?

2018-02-15 17:15 UTC, Akhilian commented on api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
> +      attributes: ['pixScore', 'createdAt', 'completedAt', 'listCertifiedCompetences']
Question : 🤔
On sérialize les marks comme une propriété du type `result`. Est-ce que ça vaut le coup de le sérializer comme un sous objet ?

2018-02-15 17:15 UTC, Akhilian commented on api/scripts/get-results-certifications-old.js
> +#! /usr/bin/env node
Pourquoi on garde l'ancien ?

2018-02-15 17:15 UTC, Akhilian commented on api/tests/acceptance/application/certification-course-controller_test.js
> +      server.inject(options, (response) => {
On peux se passer de `done`.

```
// when
const promise = server.inject(options)

// then
return promise.then((response) => {});
```

2018-02-15 17:15 UTC, Akhilian commented on api/tests/acceptance/application/certification-course-controller_test.js
> +      server.inject(options, (response) => {
Ça rend les erreurs du test plus explicite quand le test devient rouge.

2018-02-15 17:15 UTC, Akhilian commented on api/tests/acceptance/application/certification-course-controller_test.js
> +      return knex('assessments').insert({
Ça aurait un intéret de faire des variables de ces données là ?

2018-02-16 13:57 UTC, MelanieMEB commented on api/lib/application/certificationCourses/certification-course-controller.js
> +        reply(certificationCourseSerializer.serializeResult(certificationResult));
Corrigé

2018-02-16 13:59 UTC, MelanieMEB commented on api/scripts/get-results-certifications-old.js
> +#! /usr/bin/env node
Tant que les anciennes certifs n'ont pas été migré sur la table marks, on souhaite pouvoir quand meme les récupérer (script à supprimer quand on aura fait cette migration)

2018-02-16 13:59 UTC, MelanieMEB commented on api/tests/acceptance/application/certification-course-controller_test.js
> +      server.inject(options, (response) => {
Ok

2018-02-16 14:04 UTC, MelanieMEB commented on api/lib/domain/services/certification-service.js
> +          listCertifiedCompetences: assessment.marks
Bonne question... 
La compétence a été certifié, mais non validé. 
listTestedCompetences me parait trop flou.
Pas d'autres idées de noms pour le moment

2018-02-16 14:07 UTC, MelanieMEB commented on api/tests/acceptance/application/certification-course-controller_test.js
> +      return knex('assessments').insert({
Actuellement on ne les utilise que pour ces tests + besoin de l'assessmentId pour construire les marks

2018-02-16 14:55 UTC, MelanieMEB commented on api/lib/domain/services/certification-service.js
> +          listCertifiedCompetences: assessment.marks
markedCompetences ?

2018-02-19 13:25 UTC, Akhilian approved these changes

2018-02-19 15:34 UTC, merged