[#687] [FEATURE] Adapter la colonne "Numero Etudiant" en fonction du type de l'organisation prescripteure ("SUP", "SCO", "PRO")  (US-1087).
sgmap/pix pull request #687
Opened 2018-02-15 23:42 UTC by jbuget

2018-02-15 23:43 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Organisme JV que l'intitulé de la colonne du CSV d'export "Numero Etudiant" change selon que je suis du SUP, SCO ou PRO](https://trello.com/c/9scdMAo0/1087-etq-organisme-jv-que-lintitul%C3%A9-de-la-colonne-du-csv-dexport-numero-etudiant-change-selon-que-je-suis-du-sup-sco-ou-pro)

2018-02-19 13:29 UTC, mlaurent requested changes

2018-02-19 13:29 UTC, mlaurent commented on api/lib/application/organizations/organization-controller.js
> +        // eslint-disable-next-line no-console
Pourquoi le console.error et le disable eslint ?

2018-02-19 13:29 UTC, mlaurent commented on api/lib/infrastructure/converter/snapshots-csv-converter.js
>  const moment = require('moment');
Ca me fait bizarre de devoir lire ce fichier de bas en haut (ordre des fonctions), alors que la lecture d'une fonction se fait de haut en bas ... y a t il une réelle question derrière ça ?!

2018-02-19 13:29 UTC, mlaurent commented on api/tests/unit/infrastructure/converter/snapshots-csv-converter_test.js
> +    it('should return a CSV String with at least the headers line', () => {
Est-ce qu'on ne pourrait pas le nommer du genre : "should return the CSV string with only the header if no snapshots to convert" ... soit en 1 seul bloc 'it', soit avec un context('when no snapshots to convert') ?

2018-02-19 13:29 UTC, mlaurent commented on api/tests/unit/infrastructure/converter/snapshots-csv-converter_test.js
> +    context('Displaying of the first row (table headers)', () => {
Je ne comprends pas trop ce qu'il y a dans le 'context' ... On ne pourrait pas mettre du genre "When there are snapshots to convert" ?

2018-02-20 13:50 UTC, jbuget commented on api/lib/infrastructure/converter/snapshots-csv-converter.js
>  const moment = require('moment');
J'ai créée un ticket à discuter dans le tableau de dette technique

2018-02-21 11:08 UTC, mlaurent approved these changes

2018-02-22 09:58 UTC, merged