[#793] [FEATURE] Sécurisation par défaut des ressources API (US-1094).
sgmap/pix pull request #693
Opened 2018-02-22 21:31 UTC by jbuget

2018-03-01 18:59 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ PixMaster identifié, je veux que les endpoints d'administration ne soient disponibles qu'à moi](https://trello.com/c/f4o8uHbL/1094-etq-pixmaster-identifi%C3%A9-je-veux-que-les-endpoints-dadministration-ne-soient-disponibles-qu%C3%A0-moi)

2018-03-05 17:01 UTC, MelanieMEB approved these changes
La branche a un mauvais numéro d'US

2018-03-05 17:01 UTC, MelanieMEB commented on api/lib/domain/models/User.js
> +  get hasRolePixMaster() {
Pas de test ?

2018-03-07 15:41 UTC, mlaurent requested changes

2018-03-07 15:41 UTC, mlaurent commented on api/db/migrations/20180219191550_create_roles.js
> +      { name: 'PIX_PRODUCER' },
PIX_PRODUCER et PIX_DEV à supprimer car pas utilisés pour le moment ?!
(Qu'en pensez-vous les autres ?)

2018-03-07 15:41 UTC, mlaurent commented on api/lib/infrastructure/repositories/user-repository.js
> +        return bookshelfUser.toDomainEntity();
Est-ce que c'est à l'objet bookshelf de savoir comment se transformer en objet du domaine ?

2018-03-07 15:41 UTC, mlaurent commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +    return knex('users').delete();
C'est vraiment utile de faire un delete dans le before et dans le after ?

2018-03-07 15:41 UTC, mlaurent commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +    it('should be a function', function() {
Je ne vois pas vraiment l'intérêt de faire ce genre de test ...

2018-03-07 15:41 UTC, mlaurent commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +      it('should handle a rejection, when user id is not found', () => {
Est-ce qu'on ne peut pas préciser le type de "rejection" dans le nom du test ?!
"Should return a NotFoundError when user id is not found""

2018-03-07 15:41 UTC, mlaurent commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +      // Given
Alors avec ou sans majuscules les G.given W.when T.then ?

2018-03-07 15:41 UTC, mlaurent commented on api/tests/unit/infrastructure/repositories/user-repository_test.js
> +      const promise = userRepository.isEmailAvailable('email@example.net');
Je m'attendrais à ce que cette fonction me retourne true ou false ...

2018-03-07 15:41 UTC, mlaurent commented on api/lib/application/cache/index.js
> +      pre: [{
Je trouve ça un peu chiant de devoir préciser toujours la même chose dans chaque index.js ... il n'y a pas moyen de faire un genre de mixin, qui "cacherais" les détails d'implem du check de user role ?

2018-03-07 15:41 UTC, mlaurent commented on api/tests/integration/infrastructure/repositories/user-repository_test.js
> +      const user = new DomainUser({
Nommer nos objets domaine "Domain*" est un nouveau standard ?

2018-03-08 13:14 UTC, Akhilian commented on api/tests/unit/script/get-results-certifications_test.js
> +const { describe, it } = require('mocha');
Normalement, ce n'est plus utile de loader describe et it :)

2018-03-09 08:41 UTC, mackwic commented on api/lib/application/cache/index.js
> +      pre: [{
+1

2018-03-09 08:50 UTC, mackwic requested changes

2018-03-09 08:50 UTC, mackwic commented on api/lib/application/metrics/index.js
> +        auth: false,
auth: true !

2018-03-09 08:50 UTC, mackwic commented on api/lib/application/simulateErrors/index.js
> +        auth: false,
auth: true aussi je dirais...

2018-03-13 15:00 UTC, jbuget commented on api/lib/application/metrics/index.js
> +        auth: false,
on laisse ouvert

2018-03-14 13:56 UTC, jbuget commented on api/lib/application/cache/index.js
> +      pre: [{
J'aimerais aussi mais ce n'est pas possible (à ma connaissance, et d'après la doc)

2018-03-14 13:57 UTC, jbuget commented on api/tests/integration/infrastructure/repositories/user-repository_test.js
> +      const user = new DomainUser({
non, pas vraiment, c'est pour distinguer les objets du domaine de ceux techniques en Bookshelf.

2018-03-14 13:58 UTC, jbuget commented on api/lib/application/simulateErrors/index.js
> +        auth: false,
même problématique que la route `/metrics` : ça complexifie vachement Grafana pour un gain / risque pas énorme.

2018-03-15 17:20 UTC, Akhilian requested changes

2018-03-15 17:20 UTC, Akhilian commented on api/lib/application/assessments/index.js
> +      config: {
Il manque un test pour le code 401

2018-03-15 17:20 UTC, Akhilian commented on api/lib/application/cache/index.js
> +    }
```
const SecurityRoutine = {
  HAS_PIX_ROLE : {
    method: securityController.checkUserHasRolePixMaster,
    assign: 'hasRolePixMaster'
  }
};

exports.register = function(server, options, next) {

  server.route([{
    method: 'DELETE',
    path: '/api/cache',
    config: {
      pre: [ SecurityRoutine.HAS_PIX_ROLE ],
      handler: CacheController.removeCacheEntry,
      tags: ['api']
    }
  }
  ]);

  return next();
};
```

Est-ce que ça vous parait mieux ? @mackwic @mlaurent

2018-03-15 17:20 UTC, Akhilian commented on api/lib/application/cache/index.js
> +    }
Où on centralise quelque part SecurityRoutine

2018-03-15 17:20 UTC, Akhilian commented on api/lib/application/healthcheck/index.js
>  exports.register = function(server, options, next) {
Pas de tests d'acceptance

2018-03-16 17:40 UTC, Akhilian approved these changes

2018-03-16 17:40 UTC, Akhilian approved these changes

2018-03-17 10:15 UTC, jbuget commented on api/lib/application/healthcheck/index.js
>  exports.register = function(server, options, next) {
Ajoutés.

2018-03-17 10:46 UTC, jbuget commented on api/lib/application/assessments/index.js
> +      config: {
Ajouté.

2018-03-17 11:10 UTC, jbuget commented on api/lib/application/cache/index.js
> +    }
Apparemment, ce n'est pas si simple que ça. Y a des tests qui pètent de façon chelou. Je propose de se laisser ça pour un point tech ou un BSR prochain.

2018-03-19 13:51 UTC, mackwic commented on api/lib/application/cache/index.js
> +      pre: [{
une fonction JS utilitaire qu'on défini nous meme ?

2018-03-19 13:52 UTC, mackwic commented on api/tests/integration/infrastructure/repositories/user-repository_test.js
> +      const user = new DomainUser({
du coup c'est un standard d'équipe je dirais ?

2018-03-19 13:53 UTC, mlaurent approved these changes

2018-03-19 13:53 UTC, mackwic approved these changes

2018-03-19 13:59 UTC, merged