[#] Script d'extraction anonymisée des données d'évaluation (US-1113).
sgmap/pix pull request #697
Opened 2018-03-01 11:10 UTC by mackwic

2018-03-05 16:08 UTC, MelanieMEB reviewed
Globalement ça me va. 
Je comprends ce que fait le script (même si python et moi...).
A voir pour qu'on puisse tous l'utiliser simplement.

2018-03-05 16:08 UTC, MelanieMEB commented on scripts/anonymous-extract/README.md
> +- Avoir ouvert un tunnel vers la db de scalingo en utilisant le script `scripts/backup-db/open-tunnel.sh`
Donc pas utilisables actuellement sur la prod directement ?

2018-03-05 16:43 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Chercheur Big Data JV avoir un dump anonymisé des assessments/answers de PIX](https://trello.com/c/qSINOo2G/1113-etq-chercheur-big-data-jv-avoir-un-dump-anonymis%C3%A9-des-assessments-answers-de-pix)

2018-03-05 16:52 UTC, jbuget requested changes
Il faudrait une page dans Confluence pour indiquer : 

- pourquoi / pour qui ce script ?
- comment l'utiliser (en mode "je n'ai plus qu'à copier-coller des commandes, aussi SSH soitent-elles")

2018-03-06 09:39 UTC, mackwic commented on scripts/anonymous-extract/README.md
> +- Avoir ouvert un tunnel vers la db de scalingo en utilisant le script `scripts/backup-db/open-tunnel.sh`
du coup non

2018-03-06 10:17 UTC, mackwic commented
Passage de la capit dans une page confluence et fermeture de la PR: https://1024pix.atlassian.net/wiki/spaces/DEV/pages/42008577/Anonymiser+des+donn+es+de+la+BDD+Production

2018-03-06 10:17 UTC, closed without merging