[#699] [FEATURE] Ajout d'une route pour modifier les résultats d'une certification (US-1088).
sgmap/pix pull request #699
Opened 2018-03-05 08:41 UTC by MelanieMEB

**Objectif de l'US** : Ajout d'une route POST /api/assessment-results pour mettre à jour le résultat d'un certification.

**A été réalisé dans la base** : 
- Renommer la table Marks en Competence-Marks
- L'ajout d'une table Assessment-results : cette table contient le résultat d'un assessment (pixScore et Level), ainsi que les informations sur qui a calculé ce résultats. Elle est reliés aux Competences-Marks.
- Déplacement d'informations entre les tables Certification-courses /Assessments/Assessment-resutls et mise à jour des informations. La table Certification-Course ne contenant plus que les informations liés au passage de la certification (qui ? quand ? sur quels questions ?) . La table Assessment contient les informations liés au passage de l'assessment (Qui ? Quand ? Sur quel Course ? Status started ou completed ?). La table Assessment-Results contient les informations des résultats (la "copie") : les notes, qui a modifié les notes, le status du résultats (validated/rejrected).

2018-03-09 16:21 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ PixMaster JV pouvoir modifier un score PIX et/ou un niveau obtenu en certification par un candidat sur une ou plusieurs compétences](https://trello.com/c/qtTMLlfn/1088-etq-pixmaster-jv-pouvoir-modifier-un-score-pix-et-ou-un-niveau-obtenu-en-certification-par-un-candidat-sur-une-ou-plusieurs-comp)

2018-03-13 09:52 UTC, MelanieMEB commented
Besoin d'ajouter les erreurs pour : 
Niveau > 5
PixScore > 64
PixScore est un nombre
Compétence N'existe pas

2018-03-14 09:19 UTC, Akhilian requested changes

2018-03-14 09:19 UTC, Akhilian commented on api/lib/application/assessment-results/assessment-result-controller.js
> +    const assessmentResult = request.payload.data.attributes;
Sérialisation du payload pour obtenir un objet du domaine + modification du service en conséquence.

2018-03-14 09:19 UTC, Akhilian commented on api/lib/application/assessment-results/assessment-result-controller.js
> +      .then(reply)
On ne renvoie rien pour le moment.

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/models/Assessment.js
> +      return sortedAssessmentResult[0];
On le fait avec lodash et .first() ?

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/models/AssessmentResult.js
>    }
Re-valider qu'il est nécessaire de passer par assign()

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/models/Profile.js
>          if (competence.status === 'notCompleted') {
On ajoute un 
```// TODO: Standardiser l'usage de status pour une compétence```

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-rating-service.js
> +        assessmentService.getSkills(assessmentId),
Ajouter un TODO pour standardiser les appels au service.

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-rating-service.js
> +          level = -1;
Seulement pour une certification

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-rating-service.js
> +        assessment.state = 'completed';
assessment.setCompleted()

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-rating-service.js
> +          level = -1;
Bascule dans le constructeur

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-result-service.js
> +  save(assessmentResultInfo) {
Après la sérialisation, ce sera un Objet du domaine.

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-service.js
>  async function fetchAssessment(assessmentId) {
On met un `@depecrated` devant ?

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-service.js
> +      .then((resultCompute) =>{
On pourrait décomposer en `{ pixScore, level }`

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/assessment-service.js
> +  return assessment.state === 'completed';
Quick win : ```return assessment.isCompleted()```
Sinon; on supprime

2018-03-14 09:19 UTC, Akhilian commented on api/lib/domain/services/certification-service.js
> +      result.status = assessment.status;
Something weird.
assessment.status => .state ?

2018-03-14 09:19 UTC, Akhilian commented on api/lib/infrastructure/repositories/assessment-result-repository.js
> +    return new BookshelfAssessmentResult(assessmentResult)
Ne pas sauvegarder les marks ici.

2018-03-14 09:19 UTC, Akhilian commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +  changeCompletedDate(certificationCourseId, completedAt = null) {
changeCompletionDate

2018-03-14 09:19 UTC, Akhilian commented on api/package.json
> +    "lint:fix": "./node_modules/.bin/eslint lib tests --fix",
On pourrait ajouter script aussi

2018-03-14 09:19 UTC, Akhilian commented on api/tests/acceptance/application/assessment-result-controller_test.js
> +      knex('competence-marks').delete().then(() => knex('assessment-results').delete());
Il manque un return ici (et ligne ensuite).

2018-03-14 09:19 UTC, Akhilian commented on api/tests/acceptance/application/assessment-result-controller_test.js
> +    it('should save a assessment-results and 3 marks', () => {
J'ajouterais un cas où j'ajoute un nouvel assessment-result avec le bon status.

2018-03-14 09:19 UTC, Akhilian commented on api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
> +    before(() => knex('assessment-results').delete());
Pas utile normalement.

2018-03-14 09:19 UTC, Akhilian commented on api/tests/unit/domain/services/assessment-rating-service_test.js
>          validatedSkills: _generateValitedSkills(),
generateValitedSkills => HEIN ?!

2018-03-14 09:19 UTC, Akhilian commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +      assessmentService.getSkills.rejects(new NotFoundError());
when getSkills raise a notFoundError because the assessment does not exist

2018-03-14 09:19 UTC, Akhilian commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +        const savedCompetenceMark = assessmentRepository.save.firstCall.args;
Peut etre juste testé le 'state' vu que c'est le sujet du test

2018-03-14 09:19 UTC, Akhilian commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +        status: 'started',
state

2018-03-14 09:19 UTC, Akhilian commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +      // TODO: Remove
// TODO: Remove the TODO

2018-03-14 09:56 UTC, MelanieMEB commented on api/lib/domain/models/Assessment.js
> +      return sortedAssessmentResult[0];
ok

2018-03-14 09:56 UTC, MelanieMEB commented on api/lib/domain/models/Profile.js
>          if (competence.status === 'notCompleted') {
ok

2018-03-14 09:56 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
>          validatedSkills: _generateValitedSkills(),
ok

2018-03-14 09:56 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +      assessmentService.getSkills.rejects(new NotFoundError());
ok

2018-03-14 09:56 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +        const savedCompetenceMark = assessmentRepository.save.firstCall.args;
ok

2018-03-14 09:56 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +      // TODO: Remove
OK

2018-03-14 10:03 UTC, MelanieMEB commented on api/lib/application/assessment-results/assessment-result-controller.js
> +      .then(reply)
ok

2018-03-14 10:10 UTC, MelanieMEB commented on api/lib/domain/models/AssessmentResult.js
>    }
Je passais par Assign car je fais des tests sur createdAt, qui fait parti de l'objet qu'une fois en base de données. Si je l'assigne ici, je devrais mettre la date lors de la création. 

A voir

2018-03-14 10:24 UTC, MelanieMEB commented on api/lib/domain/services/assessment-rating-service.js
> +        assessmentService.getSkills(assessmentId),
Pas fait de todo mais directement modifié

2018-03-14 10:28 UTC, MelanieMEB commented on api/lib/domain/services/assessment-rating-service.js
> +        assessment.state = 'completed';
OK

2018-03-14 10:32 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
>  async function fetchAssessment(assessmentId) {
OK

2018-03-14 10:41 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
> +      .then((resultCompute) =>{
OK

2018-03-14 10:43 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
> +  return assessment.state === 'completed';
Supprimé !

2018-03-14 10:47 UTC, MelanieMEB commented on api/lib/domain/services/certification-service.js
> +      result.status = assessment.status;
Changé

2018-03-14 10:49 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +  changeCompletedDate(certificationCourseId, completedAt = null) {
OK

2018-03-14 11:04 UTC, MelanieMEB commented on api/tests/acceptance/application/assessment-result-controller_test.js
> +      knex('competence-marks').delete().then(() => knex('assessment-results').delete());
ok

2018-03-14 11:05 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
> +    before(() => knex('assessment-results').delete());
ok

2018-03-14 11:14 UTC, MelanieMEB commented on api/tests/acceptance/application/assessment-result-controller_test.js
> +    it('should save a assessment-results and 3 marks', () => {
ok

2018-03-14 14:31 UTC, MelanieMEB commented on api/lib/application/assessment-results/assessment-result-controller.js
> +    const assessmentResult = request.payload.data.attributes;
OK

2018-03-21 10:21 UTC, MBrandone requested changes

2018-03-21 10:21 UTC, MBrandone commented on api/lib/application/assessment-results/assessment-result-controller.js
> +      .then(() => reply())
Yoh, j'arrive peut-être un peu tard. Dans le standard JSON API, quand on crée une ressource, il faut qu'on retourne un objet, au moins avec un type : http://jsonapi.org/format/#crud-creating.
Je pense que cet endpoint va être utilisé par le front Ember, donc ce serait cool si il respecte le standard.

2018-03-21 10:21 UTC, MBrandone commented on api/tests/acceptance/application/assessment-result-admin-controller_test.js
> +    const options = {
Yoh, j'ai l'impression qu'on fait un payload de JSON API à moitié ici : l'objet data, un type ...
mais les relations sont dans l'objet attributes, et y a un tableau dedans (pas interdit, mais pas conseillé). 

De plus, on devrait ne pouvoir sauvegardé qu'un seul type de ressource (j'ai l'impression qu'ici, on sauvegarde des competences with marks également).

Je serai pour : 

- soit avoir un payload qui respecte JSONAPI totalement dans le cas où un front devra se brancher; 
- soit s'affranchir des règles JSON API que l'on s'est mi si l'endpoint ne sera brancher à aucun front (enlever le data, le type, l'attributes, et ne garder qu'un objet en payload pour simplifier)

2018-03-21 10:21 UTC, MBrandone commented on api/lib/application/assessment-results/assessment-result-controller.js
> +// TODO: Should be removed and replaced by a real serializer
Dans la norme JSON API, je pense que dans un endpoint POST, on ne peut sauvegarder qu'une seule ressource à la fois. Et je pense que c'est une bonne pratique (j'ai peur que ça devienne une usine à gaz cet endpoint).

2018-03-21 10:21 UTC, MBrandone commented on api/lib/application/assessment-results/assessment-result-controller.js
> +// TODO: Should be removed and replaced by a real serializer
Et en vrai, ça aurait été cool de déjà avoir des serializers pour ces deux ressources. 
Malgré qu'on a déjà une énorme difficulté, c'est que le format d'entrée est pas JSON API, donc on peut pas utiliser notre json-api-deserializer.

2018-03-21 10:21 UTC, MBrandone commented on api/lib/domain/services/assessment-result-service.js
> +function evaluateFromAssessmentId(assessmentId) {
Je sais pas si cette fonction a été ajoutée ou déplacer, mais j'ai du mal à la comprendre.
Je serai pour extraire des fonctions privés pour chaque Promesse à l'intérieur de cette grande fonction.

2018-03-21 10:21 UTC, MBrandone commented on api/lib/domain/services/assessment-service.js
> +async function getSkills(assessment) {
Pour toutes les fonctions qui ont été ajoutés dans ce fichier (je ne sais pas si elles ont été déplacé ou crée). Mais elles sont très longues (plus de 20 lignes). Je les aurais bien raccourci en extrayant des fonctions privés.

2018-03-21 10:21 UTC, MBrandone commented on api/lib/domain/services/assessment-service.js
> +  if (_isNonScoredAssessment(assessment)) {
Ce if pourrai se faire avant le bloc d'instruction au-dessus. Ça éviterait de faire un appel à la base pour rien si c'est un assessment pas scoré.

2018-03-21 10:21 UTC, MBrandone commented on api/lib/domain/services/assessment-service.js
> +      let skillsReport = {
On pourrait définir cette variable plus haut. Elle serait utilisé à la ligne 153 du coup aussi. On gagnerait 2-3 lignes.

2018-03-21 10:21 UTC, MBrandone commented on api/lib/domain/errors.js
> +class ValidationError extends Error {
On pourrait lui donner un nom un peu plus précis, j'ai l'impression que c'est du ObjectValidationError.
Pour qu'on soit plus serein sur la réutilisation.

2018-03-21 10:21 UTC, MBrandone commented on api/tests/integration/infrastructure/repositories/assessment-repository_test.js
>      it('should retrieve the assessment with its marks for the given certificationId', () => {
Dans le nom du test, ce serait cool de mettre result, pour qu'il n'y ait plus de confusion sur le terme métier en anglais à la place de mark.

2018-03-21 10:21 UTC, MBrandone commented on api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
> +      const promise = certificationCourseRepository.changeCompletionDate(20, '2018-01-01');
J'ai été surpris à la relecture par le magicNumber 20, on peut extraire dans des variables explicites ?

2018-03-21 10:21 UTC, MBrandone commented on api/tests/unit/domain/models/CompetenceMark_test.js
> +
Je comprend pas comment ce test passe xD, la validation est pas appelé dans le constructor mais les validations se font quand même ? Y a un truk magique ?

2018-03-21 10:21 UTC, MBrandone commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +          const savedCompetenceMark = competenceMarkRepository.save.firstCall.args;
on peut définir cette const plus haut ? dans le given ou when

2018-03-21 10:21 UTC, MBrandone commented on api/tests/unit/domain/services/assessment-rating-service_test.js
>  const { expect, sinon } = require('../../../test-helper');
Le fichier mérite d'être renommé je pense. Y a pas son équivalent implementation.

2018-03-21 10:21 UTC, MBrandone commented on live/app/models/assessment.js
> +  rating: belongsTo('assessment-result'),
on pourrait renommer le champs result du coup ?

2018-03-23 16:30 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
>  const { expect, sinon } = require('../../../test-helper');
Fait

2018-03-23 16:31 UTC, MelanieMEB commented on api/tests/unit/domain/services/assessment-rating-service_test.js
> +          const savedCompetenceMark = competenceMarkRepository.save.firstCall.args;
OK

2018-03-23 16:33 UTC, MelanieMEB commented on api/tests/unit/domain/models/CompetenceMark_test.js
> +
Bah oui c'est magique ! ^^
C'est surtout un test qui vérifie juste que l'objet est construit, il n'y a pas d'autres validation.

2018-03-23 16:34 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
> +      const promise = certificationCourseRepository.changeCompletionDate(20, '2018-01-01');
J'ai extrait la magic number

2018-03-23 16:38 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
> +async function getSkills(assessment) {
C'est du déplacement et c'est déjà du découpage en faite (en plus petite, mais encore encore assez petite).

Je propose un refacto futur

2018-03-23 16:39 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
> +  if (_isNonScoredAssessment(assessment)) {
+1 fait

2018-03-23 16:40 UTC, MelanieMEB commented on api/lib/domain/services/assessment-service.js
> +      let skillsReport = {
+1 fait

2018-03-26 10:19 UTC, MelanieMEB commented on live/app/models/assessment.js
> +  rating: belongsTo('assessment-result'),
OK !

2018-03-26 10:19 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/assessment-repository_test.js
>      it('should retrieve the assessment with its marks for the given certificationId', () => {
ok

2018-03-26 10:26 UTC, MelanieMEB commented on api/lib/domain/errors.js
> +class ValidationError extends Error {
Ok pour ObjectValidationError

2018-03-26 10:28 UTC, MelanieMEB commented on api/lib/domain/services/assessment-result-service.js
> +function evaluateFromAssessmentId(assessmentId) {
Elle était déjà là, je l'ai juste renommé et déplacé.

2018-03-26 10:36 UTC, MelanieMEB commented on api/lib/application/assessment-results/assessment-result-controller.js
> +// TODO: Should be removed and replaced by a real serializer
Dans l'utilisation actuelle (via postman), ca serait difficile d'envoyer plusieurs requetes, ca risque de créer d'autres problemes.

Je pense que le mieux est de les ajouter quand on sera au clair avec le front

2018-03-27 12:33 UTC, mlaurent requested changes

2018-03-27 12:33 UTC, mlaurent commented on api/db/migrations/20180222110032_create_table_competences-marks.js
> +      t.text('area_code').notNull();
Pourquoi mettre des underscores ici, plutôt que du CamelCase ?

2018-03-27 12:33 UTC, mlaurent commented on api/lib/application/assessment-results/assessment-result-controller.js
> +          return reply();
On ne spécifie rien ici comme type et message d'erreur ?

2018-03-27 12:33 UTC, mlaurent commented on api/lib/domain/services/user-service.js
> +      competence.pixScore = assessment.getLastAssessmentResult().pixScore;
Est-ce qu'on ne pourrait cacher cette "navigation transitive" par un assessment.getPixScore() qui aurait comme comportement de récupérer le pix score du last result ?
Est-ce qu'on veut que le user-service sache que le pix score vient du last assessment result de l'assessment, ou simplement le récupérer de l'assessment ?

2018-03-27 12:33 UTC, mlaurent commented on api/lib/infrastructure/data/assessment-result.js
> +  validations: {
On ne fait pas la validation avec du Joi dans l'entitée métier ici ?

2018-03-27 12:33 UTC, mlaurent commented on api/lib/infrastructure/repositories/competence-mark-repository.js
> +  return new CompetenceMark(bookshelfModel.toJSON());
La tendance actuelle (sans être la norme) est de faire la transformation de Bookshelf vers domain dans l'objet bookshelf lui même -> bookshelfModel.toDomain().
A (rererere)revoir avec l'équipe

2018-03-27 12:33 UTC, mlaurent commented on api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
> +    it('should persist the mark in db', () => {
mark -> assessment result (à remplacer dans le titre des autres TUs aussi)

2018-03-27 12:33 UTC, mlaurent commented on api/tests/unit/application/assessment-results/assessment-results-controller_test.js
> +          expect(logger.error).to.have.been.calledWith(undefinedError);
C'est une règle chez nous de devoir logguer les erreurs ?

2018-03-27 12:33 UTC, mlaurent commented on api/tests/unit/infrastructure/serializers/jsonapi/assessment-result-serializer_test.js
> +          type: 'assessment-results'
L'object s'écrit AssessmentResult au singulier, et le type au pluriel ... ne devrait on pas avoir les 2 au singulier ou au pluriel ?

2018-03-27 13:13 UTC, MBrandone approved these changes

2018-03-27 13:14 UTC, MelanieMEB commented on api/db/migrations/20180222110032_create_table_competences-marks.js
> +      t.text('area_code').notNull();
Bonne question !

2018-03-27 13:15 UTC, MelanieMEB commented on api/lib/application/assessment-results/assessment-result-controller.js
> +          return reply();
Il faut renvoyer un message avec un code spécial

2018-03-27 13:17 UTC, MelanieMEB commented on api/lib/domain/services/user-service.js
> +      competence.pixScore = assessment.getLastAssessmentResult().pixScore;
assessment.getPixScore()  & assessment.getLevel()

2018-03-27 13:19 UTC, MelanieMEB commented on api/lib/infrastructure/data/assessment-result.js
> +  validations: {
Question point tech

2018-03-27 13:22 UTC, MelanieMEB commented on api/tests/unit/application/assessment-results/assessment-results-controller_test.js
> +          expect(logger.error).to.have.been.calledWith(undefinedError);
Tests à supprimer ?

2018-03-27 13:31 UTC, MelanieMEB commented on api/tests/unit/infrastructure/serializers/jsonapi/assessment-result-serializer_test.js
> +          type: 'assessment-results'
Laisser le S

2018-03-27 13:42 UTC, MelanieMEB commented on api/lib/application/assessment-results/assessment-result-controller.js
> +          return reply();
Renvoie maintenant un 412

2018-03-27 13:42 UTC, MelanieMEB commented on api/lib/domain/services/user-service.js
> +      competence.pixScore = assessment.getLastAssessmentResult().pixScore;
fait

2018-03-27 13:44 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/competence-mark-repository.js
> +  return new CompetenceMark(bookshelfModel.toJSON());
Fait

2018-03-27 13:45 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
> +    it('should persist the mark in db', () => {
Fait

2018-03-27 14:05 UTC, mlaurent approved these changes

2018-03-29 09:01 UTC, mackwic requested changes
dater les migrations au jour de la mep

2018-03-29 09:11 UTC, mackwic requested changes

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180221150236_move_status_from_certification_to_assessment.js
> +      table.text('state');
a indexer

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180221150236_move_status_from_certification_to_assessment.js
> +    table.text('status');
a indexer

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180221162245_create_assessment_results_table.js
> +      t.integer('assessmentId').unsigned().references('assessments.id');
index

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180221164430_link_marks_to_assessment_results.js
> +    table.foreign('assessmentResultId').references('assessment-results.id');
index

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180222110055_migrate_old_marks_in_competence-marks.js
> +      t.integer('assessmentId').unsigned().references('assessments.id');
index

2018-03-29 09:11 UTC, mackwic commented on api/db/migrations/20180222110055_migrate_old_marks_in_competence-marks.js
> +      t.integer('assessmentResultId').unsigned();
index

2018-04-03 09:56 UTC, merged