[] Réparation du script de suppression des utilisateurs (US-1120)
sgmap/pix pull request #705
Opened 2018-03-09 13:40 UTC by mlaurent

A noter : pour le moment, et après discussion avec Benoit, on refuse la suppression d'un utilisateur qui a déjà passé une certification.

2018-03-09 13:41 UTC, mlaurent commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Dev, je veux corriger le script de suppression pour les comptes contentant des marks](https://trello.com/c/HBeeNT7F/1120-etq-dev-je-veux-corriger-le-script-de-suppression-pour-les-comptes-contentant-des-marks)

2018-03-12 13:42 UTC, MelanieMEB approved these changes
Ok pour moi de manière générale

2018-03-12 13:42 UTC, MelanieMEB commented on api/tests/unit/script/delete-user_test.js
> +        // arrange
Petite question : Pourquoi le AAA par rapport au GWT ?

2018-03-12 13:42 UTC, MelanieMEB commented on api/tests/unit/script/delete-user_test.js
> +      it('should return neutral query when assessmentIds is an empty array', () => {
Le test attend que l'on renvoie une erreur, ce qui me parait différent d'une requête neutre si je regarde le test seul. 
"Should throw an error when ... " ?

2018-03-12 13:42 UTC, MelanieMEB commented on api/tests/unit/script/delete-user_test.js
> +      it('should return neutral query when assessmentIds is an empty array', () => {
Ce commentaire peut se retrouver sur les autres tests qui lèvent une erreur

2018-03-15 14:18 UTC, jbuget requested changes
même commentaires que @MelanieMEB

2018-03-15 14:18 UTC, jbuget commented on api/tests/unit/script/delete-user_test.js
> +        expect(() => subject.delete_feedbacks_from_assessment_ids(assessment_ids)).to.throw(Error);
on peut séparer en deux l'action et l'assertion : 

```js
// when (oui, parceque le standard sur Pix est GWT)
const promise = subject.delete_feedbacks_from_assessment_ids(assessment_ids);

// then
return promise
  .then(() => expect.fail('Expected an error to have been thrown'))
  .catch((err) => {
    expect(err).to.be.an.instanceof(XXX);
  });
```

2018-03-15 14:18 UTC, jbuget commented on api/tests/unit/script/delete-user_test.js
> +        queryBuilderMock.expects('delete_feedbacks_from_assessment_ids').never();
pourquoi mettre ces assertions ici plutôt que dans la section plus bas (même combat pour AAA que GWT sur ce coup)

2018-03-15 14:28 UTC, jbuget approved these changes

2018-03-19 08:33 UTC, merged