[#707] Modifications pour Scalingo (US-1092)
sgmap/pix pull request #707
Opened 2018-03-12 17:07 UTC by mackwic

2018-03-27 15:15 UTC, Akhilian requested changes

2018-03-27 15:15 UTC, Akhilian commented on api/db/knexfile.js
> +    ssl: ('true' === process.env.DATABASE_SSL_ENABLED)
Variable d'environment à mettre en place à la main ?
Au moins à documenter

2018-03-27 15:15 UTC, Akhilian commented on api/lib/infrastructure/logger.js
> -    path: settings.logging.path,
La variable .path n'est plus utilisée

2018-03-27 15:15 UTC, Akhilian commented on api/package.json
> +    "node": "8.6.0",
En production on est en version 7.10.1.
Est-ce que c'est compatible ? Montée de version à faire sur les machines de production ?

2018-03-27 15:15 UTC, Akhilian commented on live/package.json
> +    "node": "8.6.0",
Même question qu'au dessus ?

2018-03-27 15:15 UTC, Akhilian commented on package.json
> +  "cacheDirectories": [
Pas sûr que ça marche avec les MEP sur la prod v2.
On fait un `npm install` mais que ce passe t-il pour l'ajout de nouvelles dépendances ?

2018-04-04 09:43 UTC, mackwic commented
Bougée vers https://github.com/1024pix/pix/pull/6

2018-04-04 09:43 UTC, closed without merging