[#] [BUGFIX] Correction des erreurs de validation à la création de compte (US-1128).
sgmap/pix pull request #710
Opened 2018-03-14 17:40 UTC by Akhilian

2018-03-15 13:31 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [Corriger l'erreur 500 sur la création d'un utilisateur](https://trello.com/c/ILUGnxZ3/1128-corriger-lerreur-500-sur-la-cr%C3%A9ation-dun-utilisateur)

2018-03-15 13:46 UTC, MelanieMEB requested changes

2018-03-15 13:46 UTC, MelanieMEB commented on api/lib/application/users/user-controller.js
> +          return reply(validationErrorSerializer.serialize(err)).code(422);
Boom.badData ?

2018-03-15 13:46 UTC, MelanieMEB commented on api/lib/application/users/user-controller.js
> +const { ValidationError } = require('bookshelf-validate/lib/errors');
renommer as BookshelfValidationError

2018-03-15 13:46 UTC, MelanieMEB commented on api/lib/application/users/user-controller.js
> +          return reply(validationErrorSerializer.serialize(err)).code(422);
Pas de test sur le reply when bookshelfUtils.isUniqConstraintViolated.rejected?

2018-03-15 13:46 UTC, MelanieMEB commented on api/lib/application/users/user-controller.js
>      if (!_.has(request, 'payload') || !_.has(request, 'payload.data.attributes')) {
Ajout d'une fonction 
``_hasPayloadAndAttributes(request) {
if (!_.has(request, 'payload') || !_.has(request, 'payload.data.attributes'))
 {return Promise.reject()}
else {
return Promise.resolve();
}
}``

et déplacement de la reply Bad Request

2018-03-15 14:46 UTC, Akhilian commented on api/lib/application/users/user-controller.js
> +          return reply(validationErrorSerializer.serialize(err)).code(422);
💀

2018-03-15 14:51 UTC, Akhilian commented on api/lib/application/users/user-controller.js
> +          return reply(validationErrorSerializer.serialize(err)).code(422);
Pas de sérialisation Boom dans ce cas => Pas de JSONAPI ;)

2018-03-23 14:39 UTC, Akhilian commented on api/lib/application/users/user-controller.js
> +          return reply(validationErrorSerializer.serialize(err)).code(422);
Si, il y en a un ;)

2018-03-23 15:48 UTC, MelanieMEB approved these changes

2018-03-23 15:49 UTC, merged