[#720] [FEATURE] 1052 import certification data from csv (US-1052).
sgmap/pix pull request #717
Opened 2018-03-22 09:43 UTC by jbuget

2018-03-28 09:41 UTC, MelanieMEB requested changes

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +// TODO create US
A supprimé ?

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +      /*
Completement supprimer si pas encore (et surement jamais) utilisé

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +          // 'status': certification.status,
Supprimer les commentaires inutiles

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +function createAndStoreCertifications(options) {
La fonction reçoit les certifications déjà créé, donc c'est juste storeCertifications ? Ou plutot saveCertificationsInformation ? storeCertificationsInformation?

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +            console.log('Téléversement des certifications sur le serveur : OK');
Sortir la gestion d'erreur dans une fonction ?

2018-03-28 09:41 UTC, MelanieMEB commented on api/scripts/import-certifications-from-csv.js
> +      id: parseInt(dataRow['ID de certification']),
Peut etre sortir les headers dans un tableau au dessus

2018-03-28 09:41 UTC, MelanieMEB commented on api/tests/acceptance/scripts/import-certifications-from-csv_test.js
> +      const expectedCertifications = [{
Mettre le expected dans le given ?

2018-03-28 09:41 UTC, MelanieMEB commented on api/tests/acceptance/scripts/import-certifications-from-csv_test.js
> +    it('should call PATCH /api/certification-courses/:id three times, when there are three certifications', () => {
Dans le then, on ne voit pas vraiment la vérification des trois appels (si c'est possible)

2018-03-29 08:59 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +// TODO create US
yep 👍

2018-03-29 08:59 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +      /*
done 🐢 ✔️

2018-03-29 09:00 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +          // 'status': certification.status,
🐢 ✔️

2018-03-29 09:03 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +function createAndStoreCertifications(options) {
Bien d'accord, on à rename

2018-03-29 09:17 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +            console.log('Téléversement des certifications sur le serveur : OK');
🐢 ✔️

2018-03-29 09:17 UTC, DaRiviere commented on api/scripts/import-certifications-from-csv.js
> +      id: parseInt(dataRow['ID de certification']),
🐢 ✔️

2018-03-29 09:20 UTC, DaRiviere commented on api/tests/acceptance/scripts/import-certifications-from-csv_test.js
> +      const expectedCertifications = [{
🐢 ✔️

2018-03-29 09:23 UTC, DaRiviere commented on api/tests/acceptance/scripts/import-certifications-from-csv_test.js
> +    it('should call PATCH /api/certification-courses/:id three times, when there are three certifications', () => {
Maintenant si 😸

2018-03-29 09:27 UTC, MelanieMEB approved these changes

2018-03-29 10:01 UTC, mlaurent requested changes

2018-03-29 10:01 UTC, mlaurent commented on api/scripts/import-certifications-from-csv.js
> +const Papa = require('papaparse');
Pourquoi le P majuscule ? On nomme les lib required avec une minuscule habituellement ...

2018-03-29 13:30 UTC, mlaurent approved these changes

2018-03-29 13:38 UTC, merged