[#] [TECH] Ajout d'un script de suppression d'évaluation (US-1174).
sgmap/pix pull request #720
Opened 2018-03-28 14:38 UTC by Akhilian

2018-03-28 14:39 UTC, Akhilian commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ PixMaster, JV supprimer un assessment pour plusieurs utilisateurs](https://trello.com/c/dVX3hDXa/1174-etq-pixmaster-jv-supprimer-un-assessment-pour-plusieurs-utilisateurs)

2018-03-29 09:33 UTC, mlaurent requested changes

2018-03-29 09:33 UTC, mlaurent commented on api/scripts/delete-assessment.js
> +  client.logged_query = function(query) {
Je n'avais pas bien compris que logged_query exécutait la query ... ne peut-on pas renommer en "query_and_log" ?

2018-03-29 09:40 UTC, mlaurent approved these changes

2018-03-29 10:23 UTC, DaRiviere requested changes

2018-03-29 10:23 UTC, DaRiviere commented on api/scripts/delete-assessment.js
> +  client.query_and_log = function(query) {
Extract common code in other module

2018-03-29 10:23 UTC, DaRiviere commented on api/tests/unit/script/delete-assessment_test.js
> +      it('should delete feedbacks', () => {
The following 4 tests to not test that the XXX are deleted but that the query is created. 

Only the 'should exectue all queries' actually tests that the client is called. 

So maybe change all the tests to add a verification that the client is called with the specific query in every test.

2018-03-29 10:23 UTC, DaRiviere commented on api/tests/unit/script/delete-assessment_test.js
> +          queryBuilderMock.verify();
Maybe the two asserts are redundant, just test that the clientStub is called with the right query string could be enough ?

2018-03-29 12:20 UTC, Akhilian commented on api/tests/unit/script/delete-assessment_test.js
> +      it('should delete feedbacks', () => {
Done :D

2018-03-29 13:30 UTC, Akhilian commented on api/tests/unit/script/delete-assessment_test.js
> +          queryBuilderMock.verify();
Done !

2018-03-29 16:14 UTC, DaRiviere approved these changes

2018-03-29 16:40 UTC, merged