US-178 : nombre d'épreuves par test sur la home page
sgmap/pix pull request #73
Opened 2016-10-04 09:36 UTC by bdavidxyz

2016-10-04 10:01 UTC, twickham commented
I've deployed this PR to http://178-number-of-challenges.pix.beta.gouv.fr. Please check it out

2016-10-04 13:45 UTC, mackwic requested changes

2016-10-04 13:45 UTC, mackwic commented on live/tests/acceptance/2-voir-liste-tests-test.js
> +    numberOfCourse = 4;
`let numberOfCourse` plus haut non ?
.+ typo: courseS ?

2016-10-04 13:45 UTC, mackwic commented on live/tests/acceptance/2-voir-liste-tests-test.js
> +    courseWithAllData = courses[1];
pareil, à déclarer en dehors du scope. Je suis surpris que Eslint laisse passer ça

2016-10-05 09:49 UTC, bdavidxyz commented on live/tests/acceptance/2-voir-liste-tests-test.js
> +    numberOfCourse = 4;
Exact, correction en cours

2016-10-05 09:53 UTC, twickham commented
I've deployed this PR to http://178-number-of-challenges.pix.beta.gouv.fr. Please check it out

2016-10-05 10:04 UTC, twickham commented
I've deployed this PR to http://178-number-of-challenges.pix.beta.gouv.fr. Please check it out

2016-10-05 10:14 UTC, merged