TECH : Add new route in API for getting next challenge of assessment
sgmap/pix pull request #89
Opened 2016-10-25 09:53 UTC by jilljenn

Ajout de la route ``/api/assessments/{id}/next`` qui fait appel au service ``getAssessmentNextChallengeId``.

2016-10-27 08:00 UTC, bdavidxyz reviewed
supprimer code commenté, re

2016-10-27 08:00 UTC, bdavidxyz commented on api/app/repositories/assessment-repository.js
> +
Supprimer le code commenté

2016-10-27 08:37 UTC, jbuget requested changes

2016-10-27 08:37 UTC, jbuget commented on api/app/controllers/assessments.js
> +          .then((challenge_id) => {
Privilégier le nommage en camelCase et préciser qu'il s'agit du next challenge id. Ma proposition (à challenger) :
```
"challenge_id" --> "nextChallengeId"
```

2016-10-27 08:37 UTC, jbuget commented on api/app/controllers/assessments.js
> +          assessmentService.getAssessmentNextChallengeId(assessment, null)
Je suis mitigé sur le fait de passer `null` en dernier argument d'une méthode en JavaScript.
J'ai tendance à penser que moins on met de code, mieux on se porte.
WDYT ?

2016-10-27 08:37 UTC, jbuget commented on api/app/controllers/assessments.js
> +          .catch((error) => reply(Boom.badImplementation(error)));
Le truc merveilleux avec les promesses, c'est qu'[il suffit d'une seule instruction `catch` en fin (ou en cours) de chaîne](http://odetocode.com/blogs/scott/archive/2015/10/01/javascript-promises-and-error-handling.aspx). Ex : 
```javascript
doWork1()
    .then(doWork2)
    .then(doWork3) 
    .then(doWork4)
    .catch(errorHandler);
```

2016-10-27 08:37 UTC, jbuget commented on api/app/repositories/assessment-repository.js
> +        return resolve(assessment);
En JavaScript, avec les lambdas, si la fonction consiste en une seule instruction return, alors on peut utiliser la syntaxe [retour implicite](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Fonctions/Fonctions_fléchées#Gestion_du_corps_de_la_fonction) : 
```javascript
// before
doWork(() => {
    return myResult;
});

// after
doWork(() => myResult);
```

2016-10-27 08:37 UTC, jbuget commented on api/app/repositories/assessment-repository.js
> +        return reject(error);
idem que ci-dessus

2016-10-27 08:37 UTC, jbuget commented on api/app/services/assessment-service.js
> +          resolve(selectNextChallengeId(course, currentChallengeId))
Attention, l'écriture initiale utilisait un retour implicite (cf. remarque ci-dessus). En passant par un retour explicite (avec utilisation d'accolades), il faut bien penser à utiliser le mot clé `return`.

2016-10-28 09:04 UTC, jilljenn commented on api/app/repositories/assessment-repository.js
> +
Done.

2016-10-28 09:06 UTC, jilljenn commented on api/app/controllers/assessments.js
> +          assessmentService.getAssessmentNextChallengeId(assessment, null)
C'est surtout incorrect en l'état ; c'est temporaire.

2016-10-28 09:08 UTC, jilljenn commented on api/app/repositories/assessment-repository.js
> +        return resolve(assessment);
Done.

2016-10-28 09:08 UTC, jilljenn commented on api/app/repositories/assessment-repository.js
> +        return reject(error);
Done.

2016-10-28 09:10 UTC, jilljenn commented on api/app/controllers/assessments.js
> +          .then((challenge_id) => {
Done.

2016-10-28 09:10 UTC, jilljenn commented on api/app/controllers/assessments.js
> +          .catch((error) => reply(Boom.badImplementation(error)));
Done.

2016-10-28 09:10 UTC, jilljenn commented on api/app/services/assessment-service.js
> +          resolve(selectNextChallengeId(course, currentChallengeId))
OK.

2016-10-28 09:36 UTC, jilljenn commented on api/app/controllers/assessments.js
> +          assessmentService.getAssessmentNextChallengeId(assessment, null)
OK ça a été corrigé. Maintenant, la fonction prend `request.params.challengeId`.

2016-10-28 09:44 UTC, twickham commented
I've deployed this PR to http://tech-route-assessment-next.pix.beta.gouv.fr. Please check it out

2016-11-02 14:01 UTC, bdavidxyz commented on api/tests/acceptance/controllers/assessments_test.js
> +                "recLt9uwa2dR3IYpi",
Les id sont illisibles. En mode test : Devraient avoir pour id "id_of_next_available_rec" par exemple.

2016-11-02 14:08 UTC, jilljenn commented on api/tests/acceptance/controllers/assessments_test.js
> +                "recLt9uwa2dR3IYpi",
Done.

2016-11-02 14:11 UTC, bdavidxyz approved these changes
C'est ok pour moi

2016-11-02 14:15 UTC, twickham commented
I've deployed this PR to http://tech-route-assessment-next.pix.beta.gouv.fr. Please check it out

2016-11-02 14:28 UTC, merged